### ISSUE TITLE
(Async) Cluster: `get_random_connection` can panic

### ISSUE THREAD

**Issue by kamulos** [redis-rs/redis-rs#1003]
The function `get_random_connection` can panic when the `ConnectionMap` is empty. This can easily trigger in case there is an error while reestablishing a connection in `refresh_connections`. See [here](https://github.com/redis-rs/redis-rs/pull/834#issuecomment-1850414630) for an especially bad interaction between a timeout and the resulting panic.

The fact that this needs fixing is acknowleged in a comment alongside the function:

```rust
// TODO: This function can panic and should probably
// return an Option instead:
fn get_random_connection<C>(connections: &ConnectionMap<C>) -> (String, ConnectionFuture<C>)
```

On first glance it seems to me that the correct way to solve it is to retun a `Result` or `Option`. As a user of the library I would expect to get a normal `Err(IoError)` if the necessary connection is not available or in this case no connection at all is available.

I can try to open a PR in the coming days, but the code-flow is not trivial. So if someone with more experience in this code could have a look at this issue first, it would be great :)

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/968 will solve this.

**Comment by nihohit** [comment]
@kamulos I believe this ticket can be closed. This issue was fixed in 0.25.0

**Comment by kamulos** [comment]
Yes, that's true! Thank you for all your work :heart:

**Comment by iukky** [comment]
I got the same problem with "Sync" Cluster Client.
It will panic with "Connections is empty" when I restart the redis cluster.

**Comment by nihohit** [comment]
@iukky 
https://github.com/redis-rs/redis-rs/pull/1233
