### ISSUE TITLE
add sentinel support in readme

### ISSUE THREAD

**Issue by alisterd51** [redis-rs/redis-rs#1009]
Good morning,
I noticed that Sentinel support was added in a previous ticket.
however, an indication with example code is missing from the readme file.
Can you add it please?

**Comment by nihohit** [comment]
Hi, @Syphixs @alisterd51, are the docs added here https://github.com/redis-rs/redis-rs/pull/1082/commits/9b91e06f93ef9a4ff11860451cbac4054889b173 sufficient?
