### ISSUE TITLE
Read timeouts on ConnectionManager in aio.rs

### ISSUE THREAD

**Issue by pmantica11** [redis-rs/redis-rs#1013]
Hello,

Thank you for the amazing work! I was wondering if there was a way to set up a read timeout against the ConnectionManager in aio.rs, just like we can set a connection level timeout here: https://docs.rs/redis/latest/redis/struct.Connection.html#method.set_read_timeout.

I checked and it doesn't seem like there is. Any idea on how to implement this?

**Comment by nihohit** [comment]
It is possible, just set the `response_timeout` field.

https://github.com/redis-rs/redis-rs/blob/8640ffcb20c52e57d628c2a71541e4cf91a22259/redis/src/aio/connection_manager.rs#L58C5-L58C21
https://github.com/redis-rs/redis-rs/blob/8640ffcb20c52e57d628c2a71541e4cf91a22259/redis/src/client.rs#L411

**Comment by pmantica11** [comment]
Thank you so much! That was exactly what I was looking for. The only issue is that it seems that this code was recently merged and hasn't been released to crates.io. Do you know when this code will be released?

**Comment by pmantica11** [comment]
Is it safe to just pull the crate from the main github branch?

**Comment by nihohit** [comment]
Yes, it should be safe to use the code directly from github.

**Comment by nihohit** [comment]
@pmantica11 can this issue be closed?

**Comment by pmantica11** [comment]
Yes
