### ISSUE TITLE
allow disabling setinfo

### ISSUE THREAD

**Issue by rukai** [redis-rs/redis-rs#1019]
since https://github.com/redis-rs/redis-rs/pull/945 setinfo commands are sent at startup.
A config to enable/disable this would be appreciated as some people do not want to pay the cost of running those 2 commands on connection init.

**Comment by nihohit** [comment]
@rukai how much of a cost are these calls?

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1036
