### ISSUE TITLE
Does `ClusterClient::new()` work with ElastiCache's configuration endpoint?

### ISSUE THREAD

**Issue by 4kimov** [redis-rs/redis-rs#1023]
From my understanding, ElastiCache for Redis provides one [Configuration endpoint](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html) + individual endpoints for each shard.

I've been using individual endpoints in my test env, but I'm wondering if it's possible to provide one main configuration endpoint to `ClusterClient::new()` so that it automatically figures out what shards are underneath it?

**Comment by jaymell** [comment]
Yes, it's fine. The client will attempt to use whatever initial nodes you provide to build the cluster topology.

**Comment by 4kimov** [comment]
@jaymell Thank you for the answer. So just to clarify: providing one entry in the vector (configuration endpoint) is enough for the client to map out / use all the shards underneath?

**Comment by jaymell** [comment]
Yes, that's correct.
