### ISSUE TITLE
Opt-out client set info when creating new connection

### ISSUE THREAD

**Issue by PureWhiteWu** [redis-rs/redis-rs#1034]
https://github.com/redis-rs/redis-rs/blob/main/redis/src/connection.rs#L933

`CLIENT SET-INFO` will be called in a pipeline twice when creating a new connection, and this will takes about 2-4ms to complete in our environment.

Redis is commonly used for low latency stuffs and this can lead to a significant latency increase especially when retry is added, which greatly impacts the pct99 latency(the p99 latency of our service before adding this behavior is only about 2-3ms).

Can this be designed as an option or something that can be opt-out by feature(such as the `tcp_nodelay` feature)?

This is important for us. Thanks!

**Comment by nihohit** [comment]
Sure, PRs are welcome - I think that an opt-out feature makes sense here.

On a side note, are you using short-lived connections, that one-time costs are too high for you? If so, consider reusing your connections, if that's possible. Especially if you're also using TLS, you're probably paying more on client creation than on a few calls.

**Comment by PureWhiteWu** [comment]
> Are you using short-lived connections, that one-time costs are too high for you? 

No, I'm using connection pool (deadpool), but when encounter errors, the connection cannot be reused anymore because there may be some residual data in the connection, so creating a new connection is necessary.

Thus this does not impact the average latency, but will impact the tail latency.

**Comment by Ggiggle** [comment]
I'm willing to implement this opt-out feature.

**Comment by nihohit** [comment]
> I'm willing to implement this opt-out feature.

Much appreciated, thanks!

> No, I'm using connection pool (deadpool), but when encounter errors, the connection cannot be reused anymore because there may be some residual data in the connection, so creating a new connection is necessary

Is this with `aio::Connection`? If so, that class is deprecated from the next version, exactly because of this failure mode. You'll want to switch to `aio::MultiplexedConnection` / `aio::ConnectionManager`, who are much more error tolerant.
