### ISSUE TITLE
pubsub subscription with channel(2) but get data when channel full

### ISSUE THREAD

**Issue by seal90** [redis-rs/redis-rs#1054]
I try use gprc proxy reids,  first i sub "hello" then i publish to "hello" data, my postman get the sub data after I publish every three times. 
the code like this:
https://github.com/seal90/tonic_learn/blob/main/src/redis/server.rs

then i change redis to stream , i can get data every second, the code like this:
https://github.com/seal90/tonic_learn/blob/main/src/stream/server.rs

so i think maybe the client exists problem

**Comment by nihohit** [comment]
can you please recreate this in a minimal example, without the extra dependencies?

**Comment by seal90** [comment]
https://github.com/seal90/tonic_learn/blob/main/src/minimal/server.rs
I try just use tokio tokio-stream redis the problem also exists, when i start the log like this
send ok
send ok
receive ok, data: "hello"
receive ok, data: "hello"
send ok
send ok
receive ok, data: "hello"
receive ok, data: "hello"

**Comment by seal90** [comment]
thank you
