### ISSUE TITLE
How to SUBSCRIBE using ConnectionManger

### ISSUE THREAD

**Issue by esemeniuc** [redis-rs/redis-rs#1059]
Issue: network connectivity is flaky across the open internet. I would like to use [ConnectionManager](https://docs.rs/redis/latest/redis/aio/struct.ConnectionManager.html) to auto reconnect when the connection drops. However, I cannot use `conn.into_pubsub()` on ConnectionManager. 

Current solution: At best, I am able to connect with `get_async_connection` below, which doesn't reconnect. How should I handle network issues reliably?

```rust
    async fn get_event_stream_raw(&self) -> RedisResult<impl Stream<Item = redis::Msg>> {
        let mut conn = self.client.get_async_connection().await?;
        let channel = self.format_key(); // eg REGION:KEY
        redis::cmd("CLIENT") // for debugging via `CLIENT LIST` command
            .arg("SETNAME")
            .arg(&channel)
            .query_async::<_, ()>(&mut conn)
            .await?;
        let mut pubsub = conn.into_pubsub();
        pubsub.psubscribe(channel).await?;
        Ok(pubsub.into_on_message())
    }
```

**Comment by nihohit** [comment]
ATM you can't use a connection manager for pubsub. We plan to enable this
as part of resp 3 support once that will be merged.

**Comment by esemeniuc** [comment]
Thank you for the update. Any suggestions to re-establish connections if it drops in the meantime?

**Comment by nihohit** [comment]
I don't have experience there, sorry. I guess that you'll have to create a
new pubsub connection.

**Comment by nihohit** [comment]
@esemeniuc if you want to pull in `main`, you can use the `PushManager` with `ConnectionManager` and connect to pubsub. Notice that you'd still need to resubscribe after disconnects.
