### ISSUE TITLE
If I want to decode `Value::Data` myself , where Can I find the document.

### ISSUE THREAD

**Issue by yuyang-ok** [redis-rs/redis-rs#1068]
I am doing some staff with this lib.
How Can I decode `Data`  ??

https://docs.rs/redis/0.24.0/src/redis/types.rs.html#149

**Comment by jaymell** [comment]
Hi. I'm not sure exactly what you're trying to do, but if your goal is to be able to derive your own types from bytes, you'll probably need to get bytes directly from the redis query result and deserialize that yourself using `serde_json` or a similar crate. If you can explain more what you're trying to do, we can try to provide a bit more guidance.

**Comment by nihohit** [comment]
Alternatively, if you believe that the data is in UTF8 (which is true for Redis' output, but not necessarily for data you pushed) you can call `String::from_utf8` on the data, to get it in string form.

**Comment by yuyang-ok** [comment]
@jaymell @nihohit thanks, I am quit new to this lib.Maybe I missing understand this.
