### ISSUE TITLE
Bug: ResponseError: Parse error at 1 Unexpected `84` Unexpected `72`

### ISSUE THREAD

**Issue by xxhZs** [redis-rs/redis-rs#1075]
I use 
```
self.pipe.set
self.pipe.query_async(self.conn.as_mut().unwrap()).await?;
self.pipe.clear();
```
There's a slight chance of that happening, any suggestions for troubleshooting, much appreciated!

ResponseError: Parse error at 1
Unexpected `84`
Unexpected `72`

Or is it possible to print more information, when this happens I don't have any way to get why the problem arose

**Comment by nihohit** [comment]
Hi, please post more information. On what version of the library did this happen? Which Redis server are you communicating with? What's 'self.conn'?
At the very least, please paste a complete code snippet, with the relevant types.

My guess is that 'self.conn' is 'aio::Connection'. If I'm right, please upgrade to the latest version, and replace it with a 'aio::MultiplexedConnection'.

**Comment by xxhZs** [comment]
> Hi, please post more information. On what version of the library did this happen? Which Redis server are you communicating with? What's 'self.conn'? At the very least, please paste a complete code snippet, with the relevant types.
> 
> My guess is that 'self.conn' is 'aio::Connection'. If I'm right, please upgrade to the latest version, and replace it with a 'aio::MultiplexedConnection'.


> let client = config.common.build_client()?;
        let conn = Some(client.get_async_connection().await?);
        let pipe = redis::pipe();
       while xxx {
       self.pipe.set(k, v),
        self.pipe.del(k),
        }
        self.pipe.query_async(self.conn.as_mut().unwrap()).await?;
        self.pipe.clear();

**Comment by nihohit** [comment]
right, so upgrade to the latest version and use `get_multiplexed_async_connection` instead of `get_async_connection`.

**Comment by xxhZs** [comment]
> right, so upgrade to the latest version and use `get_multiplexed_async_connection` instead of `get_async_connection`.

So is this a known solution to a known problem, or is it an attempt to

**Comment by nihohit** [comment]
known solution to a known problem, which is why aio::Connection was deprecated.
Can this ticket be closed?

**Comment by xxhZs** [comment]
> known solution to a known problem, which is why aio::Connection was deprecated. Can this ticket be closed?

thank you help

**Comment by xxhZs** [comment]
Hello, I need to use cluster now, then redis ClusterClient doesn't have `get_multiplexed_async_connection `, I have to use `get_async_connection `again, will this problem happen again?

**Comment by nihohit** [comment]
no, the function has a similar name, but it doesn't return the same type.
can this issue be closed?

**Comment by xxhZs** [comment]
Thank you very much for your help
