### ISSUE TITLE
Parsing into_on_message to pass it to actix-web HttpResponse streaming

### ISSUE THREAD

**Issue by EvilWatermelon** [redis-rs/redis-rs#1136]
I want to stream the new values of subscribed key via HttpResponse `streaming()` of actix-web. How can I do this?

```rust
let subscribe: PubSub = RedisCache::create_client().get_async_pubsub().await.unwrap();
subscribe.psubscribe("").await.unwrap();
let msg = subscribe.into_on_message();

    HttpResponse::Ok().streaming()
```
This is not possible because `streaming()` requires `Stream<Item = Result<Bytes, E>> + 'static` and `into_on_message()` returns `impl Stream<Item = Msg>`. How can I parse that?

**Comment by nihohit** [comment]
Why not add a map to the stream, and map from `Msg` to `Bytes`?

**Comment by EvilWatermelon** [comment]
Can you give me an example?

**Comment by nihohit** [comment]
I don't know what's your schema, so this is a mapping from `Msg` to some message that contains all of the `Msg`'s data, and then to `bytes::Bytes`:

```rs
let mut pubsub_stream = pubsub_conn.into_on_message();
let mapped_stream = pubsub_stream.map(|msg| {
    let str_msg = format!(
        "Channel: {}, pattern: {}, message: {}",
        msg.get_channel_name(),
        msg.get_pattern::<String>().unwrap_or_default(),
        msg.get_payload::<String>().unwrap_or_default()
    );
    bytes::Bytes::from(str_msg)
});
```

Hopefully this will help you with using your own schema for the message.

**Comment by EvilWatermelon** [comment]
Yes, that helped. Thanks a lot!

**Comment by nihohit** [comment]
Listen, I can't help you with the API of another crate, with which I don't have any experience.

If you want it to be a `Result`, replace `bytes::Bytes::from(str_msg)` with `Ok(bytes::Bytes::from(str_msg))`, but that would only make your program compile, it won't make it correct. I don't know what are your requirements, and I doubt that this hack is what you need. If you're having issues with compiling Rust, I think that you should read up about Rust - everything I wrote here has very little to do with `redis-rs`, it's mostly about how to convert types in Rust. This isn't the place for such a discussion.
I recommend the Rust [discord server](https://discord.com/invite/rust-lang) or [subreddit](https://www.reddit.com/r/rust/) for general Rust questions.
