### ISSUE TITLE
Expiration time integer types inconsistent with `SetExpiry`

### ISSUE THREAD

**Issue by ahmadbky** [redis-rs/redis-rs#1150]
Hello, I just noticed that the integer types for the expiration times were not updated for the [`SetExpiry`](https://docs.rs/redis/0.25.3/redis/enum.SetExpiry.html) enum, which still relies on `usize`s (see #589).

I believe it needs an update too, but I can't tell if these can accept negative values or not.

Thanks 😄

**Comment by jaymell** [comment]
None of these will be negative, so changing them to `u64` is appropriate I think. Wanna open a PR?

**Comment by ahmadbky** [comment]
Yes no problem, I can do it.
