### ISSUE TITLE
Err(Password authentication failed- AuthenticationFailed)

### ISSUE THREAD

**Issue by PandaManPMC** [redis-rs/redis-rs#1154]
I can confirm that the username and password are correct, but rs cannot connect. My redis version is 6.26.
Err(Password authentication failed- AuthenticationFailed)

```
    let info = ConnectionInfo {
        addr: ConnectionAddr::Tcp("192.168.1.5".to_string(), 6379),
        redis: RedisConnectionInfo {
            db: 10,
            username: Some("rust1".to_string()),
            password: Some("rust1_abc1234".to_string()),
        },
    };
    println!("{:?}", info);
    let client = redis::Client::open(info)?;
    let mut con = client.get_connection()?;

```

**Comment by nihohit** [comment]
@PandaManPMC that's very weird. 

- Which version of the crate do you use? 
- Can you reproduce this in a test?
- I see that you don't use TLS - can you check the sent TCP traffic and see whether the authentication info is sent to the server?

**Comment by PandaManPMC** [comment]
> @PandaManPMC that's very weird.
> 
> * Which version of the crate do you use?
> * Can you reproduce this in a test?
> * I see that you don't use TLS - can you check the sent TCP traffic and see whether the authentication info is sent to the server?

redis = "0.25.3"

I still haven't solved this problem.

I use golang go-redis/v9 to connect to redis without any problem.

rust I'm stuck at this step.

**Comment by PandaManPMC** [comment]
> > @PandaManPMC that's very weird.
> > 
> > * Which version of the crate do you use?
> > * Can you reproduce this in a test?
> > * I see that you don't use TLS - can you check the sent TCP traffic and see whether the authentication info is sent to the server?
> 
> redis = "0.25.3"
> 
> I still haven't solved this problem.
> 
> I use golang go-redis/v9 to connect to redis without any problem.
> 
> rust I'm stuck at this step.

I use the above code to connect to the redis 5.x version correctly.
Therefore, I think redis-rs is not friendly to support higher versions of redis.

**Comment by nihohit** [comment]
> I think redis-rs is not friendly to support higher versions of redis.

Well, there are plenty of users for this library, including me, who don't have any problem with using it with ACL, as this test demonstrates - https://github.com/redis-rs/redis-rs/blob/e567df0490f36a275dec9afaa160ca20e240bb55/redis/tests/test_basic.rs#L49 , so I think you're wrong.

As I mentioned, you can either create a reproducing example, or post here TCP traces, in order to help me help you. Without that there isn't a lot I can suggest.

**Comment by PandaManPMC** [comment]
In the end, I did not solve this problem because it was impossible for me to change the redis version used, which would be too costly (my project is developed using golang and has been used online, and I am currently trying to use rust to develop the tools required for some services).

I switched to fred.rs and it works fine with the same configuration.
