### ISSUE TITLE
in cluster mode, tls mode is replaced after certs() is called

### ISSUE THREAD

**Issue by MyBitterCoffee** [redis-rs/redis-rs#1161]
redis-rs version: 0.25.3

For ClusterClientBuilder, if we call tls(TlsMode::Insecure) first, a following certs() call will set builder_params.tls to  Some(TlsMode::Secure) [src/cluster_client.rs:282].

So, as a user,  we should call certs() first and call tls(TlsMode::Insecure) later. 
But the document does not mention it.

Maybe checking builder_params.tls before setting it in the call of certs() is a better choice.

**Comment by nihohit** [comment]
Hi, thanks for reporting this. Do you think you can open a PR with a fix?

**Comment by nihohit** [comment]
fixed by https://github.com/redis-rs/redis-rs/pull/1166
