### ISSUE TITLE
Porposal: New Clients sharding to connect to multiple Redis Nodes but sharding at client level

### ISSUE THREAD

**Issue by pfreixes** [redis-rs/redis-rs#1181]
Hi, I would like to have your opinion about introducing a new first class Redis Client type for connecting to multiple Redis nodes but implementing all sharding strategy at client level. This implementation would go side by side with the current client which connects to one single Reids node and the Cluster strategy which connects to multiple Redis nodes but delegates the sharding strategy to the cluster.

# Why implementing a version which does the sharding at client side?

Currently when using Cluster mode for Redis comes with some operation burden which reduces freedom at the client side, and specifically everything related to all actions for mutating the topology of the cluster. Specifically the operations for making the cluster larger or shrinking requires some choreography for reassigning slots manually by using the Redis Cluster commands. While this could be an option for clusters that do not change a lot becomes an operational burden for workloads that can and want to change the topology much often.

When using sharding at client level, the client can easily change the topology by adding or removing nodes with the tradeoff of having some degree of keys rebalancing across all nodes. Ideally a % value ~ of the % of nodes added ore removed when using algorithms like consistent hashing or rendezvous hashing.

This is a tradeoff that some workloads are willing to pay.

# Other benefits of implementing the sharding at client side.

Implementing the sharding at client side also unlocks other features like for example promoting the reads from closest replicas when possible, which could be achieved by allowing to the users to provide as an input a list of servers that could be enriched with the data-center location for later on implementing multiple writes (write to all data-centers) and reading from the closest node by default.

If there is some interest on adding this feature I would like to work on a PR for introducing this new client flavour.

**Comment by nihohit** [comment]
That sounds interesting, but I'm not sure that it's worth the maintenance
cost.
Are you aware of any other client, including in other languages, that
offers such an API?
Currnetly the cluster client handles MOVED errors and disconnects - would
this be also handled by the user? If so, what's the difference between this
client and just holding a hashmap of Multiplexed connections?

**Comment by pfreixes** [comment]
any feedback on this one @nihohit ?

**Comment by jaymell** [comment]
I also think the idea is interesting, but as nihohit alluded to, I'm also not interested in the maintenance burden here. Maybe this would better be handled by a separate crate for now?

**Comment by pfreixes** [comment]
Thanks for the feedback @jaymell really appreciate Ill go to the latest point

> So, I think that @jaymell's suggestion of starting with a separate crate is a good idea. - it's what we've done with the async cluster connection. It will allow us to see whether there's interest in the community, and to slowly review this - and then, once the connection is mostly ready, we could discuss merging it into this repo. Hopefully by then our tests will be stabler too.

I was considering this too. Ill go in that way since will allow me to ship also faster and we can circle back in the future in case there is tractions and there is interest on having this merged as part of the general Redis project.
