### ISSUE TITLE
add ability to specify count for scan match

### ISSUE THREAD

**Issue by alekspickle** [redis-rs/redis-rs#1201]
Right now the only thing scan match accepts is a pattern, and while for simplicity it's great, it would be nice to be able to add count to force scan to return more results.
```

127.0.0.1:6379> set kek1 nope
OK
127.0.0.1:6379> set kek2 nope
OK
127.0.0.1:6379> set kek3 nope
OK
127.0.0.1:6379> set kek4 nope
OK
127.0.0.1:6379> scan 0 match kek*
1) "42"
2) 1) "kek3"
127.0.0.1:6379> scan 0 match kek* count 100
1) "0"
2) 1) "kek3"
   2) "kek4"
   3) "kek1"
   4) "kek2"
127.0.0.1:6379>

```

I can sketch a PR but would be glad to hear an opinion on what can it look like
I guess the most obvious path is to add new `scan_match_n`

**Comment by nihohit** [comment]
if we add a function for each option, we'll get 7 different functions - scan, scan_match, scan_match_count, scan_match_count_type, scan_match_type, scan_count_type, scan_type.
IMO it's better to just use `scan_options`, like `set_options`, and use an options struct that defines the requested behavior.

**Comment by nihohit** [comment]
closed, since PR was merged.
