### ISSUE TITLE
output stops around 15k messages. Can you please help with what's wrong with this example?

### ISSUE THREAD

**Issue by jayeshpk1** [redis-rs/redis-rs#1212]
```
mod message;
mod message_handler;
mod redis_publisher;
mod redis_subscriber;

 extern crate redis;

#[tokio::main]
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("service started");

    if let Err(error) = redis_subscriber::subscribe(String::from("order")) {
        println!("{:?}", error);
        panic!("{:?}", error);
    } else {
        println!("connected to queue");
    }
    let mut sum = 0;
    let mut price: f32= 0.0;
    for n in 1..100000 {
        price += 1.0;
        
    redis_publisher::publish_message(message::Message::new(
        message::Order::new("T-Shirt".to_string(), 
        3, 
        price)))?;

    }
    
    println!("published");

    Ok(())
}
```

Cargo.toml
[dependencies]
tokio = { version = "*", features = ["full"] }
redis = "*"

**Comment by nihohit** [comment]
I'm sorry, but it would be hard to help here without compiling code. Can you provide a full example?

**Comment by jayeshpk1** [comment]
Thanks. updated the code

**Comment by nihohit** [comment]
no, this still won't compile - what are all the `mod`s you're referencing? can you create a sample repository, or better yet, recreate this in redis-rs' tests?

**Comment by nihohit** [comment]
and I hope it's clear - you're referencing 4 `mod`s here. If they're large, we won't go over them to find your bug. Please post a **minimal** sample repository.

**Comment by jayeshpk1** [comment]
This example has rest of the code https://github.com/paoloposso/rust_redis_pubsub/tree/main/src

**Comment by nihohit** [comment]
ok, what am I supposed to see in this code example? how does it demonstrate the issue?

I see 3 messages published, and that 3 messages are printed to console with "published" printed somewhere in-between. This is expected. Then the program hangs, because redis_subscrober spawned a task that never completes.

What issue does this demonstrate?

**Comment by jayeshpk1** [comment]
Please increase the loop to 1,000,000 and run.

**Comment by nihohit** [comment]
which loop? there's no loop in main.rs.

**Comment by jayeshpk1** [comment]
you can see the loop in the main.rs I posted above

**Comment by nihohit** [comment]
You're right, this does reproduce as given. But, when I removed the serde dependency, this doesn't reproduce - I ran the code to 600K operations, and counting.
Why do you think this is an issue with the redis crate?

**Comment by nihohit** [comment]
Sorry, I made a mistake - the example still gets stuck at the end of the loop, regardless of how large the loop is - probably because of the spawned task that never completes. Once I changed the spawned task to complete with
```rs
pub fn subscribe(channel: String) -> Result<(), Box<dyn Error>> {
    let _ = tokio::spawn(async move {
        let client = redis::Client::open("redis://localhost").unwrap();

        let mut con = client.get_connection().unwrap();
        let mut i = 0;
        let _: () = con
            .subscribe(&[channel], |msg| {
                i += 1;
                let received: String = msg.get_payload().unwrap();

                println!("{received}");

                return if i == 157126 {
                    ControlFlow::Break(())
                } else {
                    ControlFlow::Continue
                };
            })
            .unwrap();
    });

    Ok(())
}
```
the application completed successfully.

**Comment by nihohit** [comment]
@jayeshpk1 was your issue solved? can this issue be closed?
