### ISSUE TITLE
provide two-stage api for MultiplexedConnection

### ISSUE THREAD

**Issue by Hexilee** [redis-rs/redis-rs#1215]
Hi, I have some redis pipelines, they must be executed in ordered, so I should execute them like this:

```rust
for pipe in pipelines {
    let () = pipe.query_async(&mut conn).await?;
}
```

However, in above code I must wait for the last response before sending next request, the QPS is affected by latency between my program and redis server.

When I try to execute them concurrently:

```rust
let mut handles = Vec::new();
for pipe in pipelines {
    let conn = conn.clone();
    let handle = tokio::spawn(async move {
        pipe.query_async(&mut conn).await
    });
    handles.push(handle);
}

for handle in handles {
    let () = handle.await??;
}
```
By above code my program can handle high QPS, but the tokio runtime cannot ensure the pipelines are executed in the order I spawn them out.

I read the [source code](https://github.com/redis-rs/redis-rs/blob/main/redis/src/aio/multiplexed_connection.rs#L328) of MultiplexedConnection and find it's implemented by `mpsc::channel` and `oneshot::channel`. So, I figure out I could send the pipelines into the req channel but not wait for response immediately, which can ensure the stable execution order and wait for response concurrently.

Here is the use-case I really need:

```rust
let mut handles = Vec::new();
for pipe in pipelines {
    let handle = pipe.send_query_async(&mut conn).await?; // the pipeline was sent to channel
    handles.push(handle);
}

for handle in handles {
    let () = handle.await??;
}
```

Are there some workarounds or plans to support it?

**Comment by nihohit** [comment]
Sorry, i don't understand what are you asking for. Can you please elaborate what is being asked, what are the benefits, intended usecase, etc.?
The most important question is why this should be implemented in this crate, and not constructed separately on top of the abstractions we provide.

**Comment by Hexilee** [comment]
@nihohit Thanks for your reply, I have change my description. You are welcome to ask me for more details.

**Comment by nihohit** [comment]
Did you try using redis::pipeline?
https://docs.rs/redis/0.25.4/redis/#pipelining

**Comment by Hexilee** [comment]
I have used, but the cmds are endless, I commit pipelines in a period.

**Comment by nihohit** [comment]
The simple solution is to chunk the continuous requests, or just use task::spawn /UnorderedStream in order to run them concurrently. 

This scenario doesn't fit the multiplexed connection's intended use case, and I don't think any of the maintainers will implement this.
I suggest you implement this yourself, ifnl not with the suggestions above then with a ValueCodec on top of a TCP stream, and if you'll get a well-defined abstraction with a clear usecase and robust implementation, we can discuss upstreaming it into the redis crate.

**Comment by Hexilee** [comment]
Thanks, i'm going to try the `ValueCodec` and raw TCP stream in my fork repo.
