### ISSUE TITLE
Things to complete for 0.26v

### ISSUE THREAD

**Issue by nihohit** [redis-rs/redis-rs#1216]
## bug fixes

- https://github.com/redis-rs/redis-rs/pull/1202
- https://github.com/redis-rs/redis-rs/pull/1222
- https://github.com/redis-rs/redis-rs/pull/1127

## features

- https://github.com/redis-rs/redis-rs/pull/1082
- https://github.com/redis-rs/redis-rs/pull/1149
- https://github.com/redis-rs/redis-rs/pull/1096
- https://github.com/redis-rs/redis-rs/pull/1094
- https://github.com/redis-rs/redis-rs/pull/1093
- https://github.com/redis-rs/redis-rs/pull/1251
- https://github.com/redis-rs/redis-rs/pull/1265

## nice to have

- https://github.com/redis-rs/redis-rs/pull/1264
- https://github.com/redis-rs/redis-rs/pull/1263
- https://github.com/redis-rs/redis-rs/pull/1193
- https://github.com/redis-rs/redis-rs/pull/1160
- https://github.com/redis-rs/redis-rs/pull/1218
- https://github.com/redis-rs/redis-rs/pull/1259
- https://github.com/redis-rs/redis-rs/pull/1233
- https://github.com/redis-rs/redis-rs/pull/1232

## testing-related

- https://github.com/redis-rs/redis-rs/pull/1145
- https://github.com/redis-rs/redis-rs/pull/1200
- https://github.com/redis-rs/redis-rs/pull/1214
- https://github.com/redis-rs/redis-rs/pull/1140

**Comment by westYY123** [comment]
Hello, I wonder if the 0.26v is the next version of 0.25.4, And when will this version be available? Will this version contains the fix of  [issue1147](https://github.com/redis-rs/redis-rs/issues/1147)? Thanks

**Comment by nihohit** [comment]
> the 0.26v is the next version of 0.25.4

Yes, unless there will be another hot-fix we'll want to send

> when will this version be available?

When it will be ready. This isn't a paid job, and we don't work by a schedule 🤷 

> Will this version contains the fix of https://github.com/redis-rs/redis-rs/issues/1147?

No one has contributed a fix for this, so ATM no. I don't believe doing this will be complex, some of the code can be copied from https://github.com/amazon-contributing/redis-rs/pull/145, so if you're interested in this you're welcome to contribute a fix.

**Comment by westYY123** [comment]
yes I do have completed one implementation, and we are validating whether it works, if it does, I'd be happy to contribute a fix

**Comment by elichai** [comment]
Can we get an example on how to do `PubSub` with `ConnectionManager` please? :)

**Comment by nihohit** [comment]
@elichai no need to ask twice :)
if anyone got here because of the question, the answer was posted here - https://github.com/redis-rs/redis-rs/issues/1409#issuecomment-2567633780
