### ISSUE TITLE
ConnectionManager with broken pipe

### ISSUE THREAD

**Issue by dinhSKM** [redis-rs/redis-rs#1223]
redis v0.25.3

on k8s I have: ConnectionManager with tokio -> HA proxy -> HA redis pods

Issue:
Sometime when send command to the redis-server, its return with the `broken pipe`
<img width="842" alt="image" src="https://github.com/redis-rs/redis-rs/assets/109545292/60e0470e-4883-4a0a-9c26-2b2d135a5bf7">

The connection is reconnected for sending another request, however the request with broken pipe is dropped.
Can I ask is there any way to workaround with the broken pipe issue or retry to send the failed command?

Thanks a lot for your help!!!

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/issues/885#issuecomment-1623756119

**Comment by dinhSKM** [comment]
tks for replying, i will try out the workaround in that thread
