### ISSUE TITLE
Issue with a simple GET command

### ISSUE THREAD

**Issue by PaulDotSH** [redis-rs/redis-rs#1227]
Hi, the following coding snippet
```rs
  if let Ok(encoded) = redis::cmd("GET")
        .arg(&encoded_filter)
        .query_async::<_, Vec<u8>>(&mut conn)
        .await {}
```
ALWAYS returns Ok, even when the key is NOT present in redis, it just choses to return an empty vec. Why does this happen? How can I fix it?

**Comment by nihohit** [comment]
Cast to Option<Vec<u8>> instead. A missing key isn't an error.

**Comment by nihohit** [comment]
@PaulDotSH is the issue solved?

**Comment by PaulDotSH** [comment]
Fixed by the comment from @nihohit
