### ISSUE TITLE
[Redis Cluster] How scan by every nodes

### ISSUE THREAD

**Issue by Cheban1996** [redis-rs/redis-rs#1230]
How i understand scan is a command for single redis node
I have a question how use lib redis-rs and scan on by every node?
Maybe someone knows if there will be a feature added to automatically start scanning each node?

**Comment by nihohit** [comment]
Hi, cluster scan is ill-defined and problematic - just see to what efforts the Amazon fork goes to enable such a feature - https://github.com/amazon-contributing/redis-rs/pull/141. It might be merged eventually, but it's a hard feature, and it won't be merged soon.

If you're using the async cluster, you can use the `route_command` function to route your requests to separate nodes, and scan each one. It won't maintain coherency if you'll experience topology changes during the scan, but it should be good enough.
I expect that the sync cluster will also receive such functionality eventually, but it's not there ATM.

**Comment by Cheban1996** [comment]
> Hi, cluster scan is ill-defined and problematic - just see to what efforts the Amazon fork goes to enable such a feature - [amazon-contributing#141](https://github.com/amazon-contributing/redis-rs/pull/141). It might be merged eventually, but it's a hard feature, and it won't be merged soon.
> 
> If you're using the async cluster, you can use the `route_command` function to route your requests to separate nodes, and scan each one. It won't maintain coherency if you'll experience topology changes during the scan, but it should be good enough. I expect that the sync cluster will also receive such functionality eventually, but it's not there ATM.

Thanks for response

**Comment by nihohit** [comment]
update - routing to specific nodes is enabled in the sync cluster by this PR - https://github.com/redis-rs/redis-rs/pull/1233
