### ISSUE TITLE
is there a reason test_block_on_all_panics_from_spawns test is not marked as #[should_panic]?

### ISSUE THREAD

**Issue by alekspickle** [redis-rs/redis-rs#1234]
Just noticed it when testing locally and there is an easy attribute that makes test go green if it panics, just wondering if there is something preventing you from simply marking it with `#[should_panic]`.

**Comment by nihohit** [comment]
sure, you can open a PR to change that.

**Comment by alekspickle** [comment]
just wanted to check if this is intentional ;)
