### ISSUE TITLE
Allow multiple key arguments in certain high level commands (ex. SUNIONSTORE)

### ISSUE THREAD

**Issue by AzureMarker** [redis-rs/redis-rs#125]
Example: [SUNIONSTORE](https://github.com/mitsuhiko/redis-rs/blob/master/src/commands.rs#L513).

The two arguments should implement ToRedisArgs, but should not be the same type:
```
    |               .sunionstore(String::from("something"), lists.iter()
    |  _____________________________________________________^ starting here...
    | |                 .map(|item| format!("{}{}", item, "test"))
    | |                 .collect::<Vec<String>>()
    | |_________________________________________^ ...ending here: expected struct
 `std::string::String`, found struct `std::vec::Vec`
    |
    = note: expected type `std::string::String`
               found type `std::vec::Vec<std::string::String>`
```
```rust
fn sunionstore<K: ToRedisArgs>(dstkey: K, keys: K) {...}
```
Here, both `String` and `Vec<String>` implement `ToRedisArgs`, so they should satisfy the function generics, except that the function requires that they be the same type `K: ToRedisArgs`. Since the first argument is `String`, the function expects the second argument to be `String` as well.

There are a few other such functions, such as `sdiffstore`, which have the same problem.

**Comment by Mcat12** [comment]
Taking a second look at this, the issue may be more in how the function is supposed to be used. I have seen this function implemented in one form on redis-py:
```python
sunionstore("something", [l + "test" for l in lists])
```
And so I expected that it would be implemented in the same manner on redis-rs. However, it appears that it is instead supposed to be implemented as:
```rust
sunionstore(String::from("something"), "list1 list2").unwrap();
```
or
```rust
sunionstore(String::from("something"), lists.iter()
    .map(|item| format!("{}{}", item, "test"))
    .collect::<Vec<String>>()
    .join(" ")
).unwrap();
```

**Comment by AzureMarker** [comment]
@MaxOhn Thanks for fixing this 5 year old issue!
