### ISSUE TITLE
Alternatives to aio::Connection in combination with WATCH

### ISSUE THREAD

**Issue by dbrgn** [redis-rs/redis-rs#1257]
In an async application I'm working on, we mainly use an multiplexed async connection.

However, there is a case where this is a bad idea: `WATCH` transactions (see https://github.com/redis-rs/redis-rs/issues/565). When multiplexing multiple commands while a transaction is ongoing, the transaction-commands and non-transaction-commands will be interleaved, resulting in unsound behavior (because transactions are tracked per connection).

For this case, I used a regular `aio::Connection` so far:

```rust
// The shared (multiplexed) connection is passed in to this function. However, this connection
// should not be used with transactions, since transactions with WATCH (CAS) are not compatible
// with multiplexing. See https://github.com/redis-rs/redis-rs/issues/565 for details. Instead,
// we open a new connection.
let mut conn = init_secondary_redis_client(config.clone())?
    .get_async_connection()
    .await?;

// Watch reflection queue key for modifications (optimistic locking, see
// https://redis.io/docs/manual/transactions/#optimistic-locking-using-check-and-set)
redis::cmd("WATCH")
    .arg(rq_key.as_ref())
    .query_async(&mut conn)
    .await?;

// Create transaction pipeline
let mut transaction = redis::pipe();
transaction.atomic();

// (...)

transaction
    .query_async::<_, ()>(&mut conn)
    .await
    .context("Could not finish transaction while unloading messages")?;
```

However, that type is now deprecated since 0.25: https://github.com/redis-rs/redis-rs/pull/889

Because `aio::Connection` is not cloneable, it isn't really possible to accidentally multiplex commands while executing the transaction. However, if I'd switch to `aio::MultiplexedConnection` instead (as suggested by the deprecation warning), the type system wouldn't give me that guarantee anymore because the connection can be freely cloned.

What is the best solution in this case? "Use the multiplexed connection and be careful not to share it"? I guess that would be possible, but isn't really in the spirit of using Rust's type system to prevent potential errors.

Another option would be wrapping the multiplexed connection in a non-cloneable wrapper type and implementing `ConnectionLike` for that type.

A third option would be using a sync connection instead. But since Redis calls are I/O code, I am very wary of that option, since the blocking I/O would block other active asynchronous code.

**Comment by nihohit** [comment]
> Another option would be wrapping the multiplexed connection in a non-cloneable wrapper type and implementing ConnectionLike for that type.

this.

**Comment by nihohit** [comment]
I assume from the lack of response that this solution is sufficient.
