### ISSUE TITLE
Retrieving error response string from a RedisError

### ISSUE THREAD

**Issue by kex103** [redis-rs/redis-rs#126]
Is there a way to look up the server's response when a RedisError of kind ResponseError is returned? I believe the detail can be printed out, but I'm not sure if there's another way I can retrieve it?

**Comment by badboy** [comment]
An error kind does not carry any information directly.
So you need the actual error variant. You can get its description using `description()` or rely on the `Display` trait to get a formatted error message: `format!("{}", error)`.

**Comment by kex103** [comment]
Ah, the problem is that description() merely gives a generic message for an error response from redis, and not the error message. It's ErrorRepr::WithDescriptionAndDetail's "detail" that has that information, and as far as I can tell, it's only available via the Display implementation, so parsing the format output does work.
Is there another way I can extract the "detail" out of that enum?

Thanks for the response!

**Comment by badboy** [comment]
Nope, seems we don't expose that at all

**Comment by kex103** [comment]
What do you think about these two possibilities?
A. add a "detail()" or "server_response()" to RedisError, which returns Option<String>.
B. Nest WithDescriptionAndDetail with another Error (that contains only the detail), and return that nested Error with Error's cause() implementation. That nested Error needs a From<ErrorKind, String> implementation, however.

It seems that ExtensionError may have a similar difficulty retrieving the detail.

**Comment by nihohit** [comment]
`kind`, `detail`, and `description` are all supported under `RedisError`. Is there more missing functionality?
