### ISSUE TITLE
How to dynamically reconstruct a Redis client based on cluster information?

### ISSUE THREAD

**Issue by lithbitren** [redis-rs/redis-rs#1260]
Is it possible to obtain cluster information using Redis commands like CLUSTER INFO or CLUSTER SLOTS, and then utilize this information to dynamically recreate a client without disrupting the web service's handle to the Redis client? Could you provide an example scenario, such as initially having a cluster consisting of three masters and three slaves, totaling six nodes, followed by a master node experiencing a network failure, leading to a slave node being promoted to master. Additionally, how should the web service side handle situations where operations staff dynamically scale the cluster up or down?

In essence, I'm seeking guidance on adapting the redis-rs client in real-time to reflect changes in the Redis cluster topology, ensuring uninterrupted service operation throughout these adjustments.

**Comment by nihohit** [comment]
Why is this necessary? The cluster clients already handle topology changes internally.

**Comment by lithbitren** [comment]
> Why is this necessary? The cluster clients already handle topology changes internally.

Oh, I wasn't aware that the internal auto-update feature exists. Could you point me to where in the documentation I can read about this? I'm curious about the mechanism behind how the updates occur and how I can observe on the Redis client side that the topology has indeed been updated?

**Comment by nihohit** [comment]
I think that our documentation is lacking here - it probably isn't documented, and should be. Another task to the list :)
You can see this clearly in the tests - tests like 
https://github.com/redis-rs/redis-rs/blob/37eccc288b8b1a59372b27fcd17cc94455bac394/redis/tests/test_cluster.rs#L452
https://github.com/redis-rs/redis-rs/blob/37eccc288b8b1a59372b27fcd17cc94455bac394/redis/tests/test_cluster_async.rs#L333
(and many more!) that verify the connection's behavior on topology changes.
