### ISSUE TITLE
 The remote host forcibly closed an existing connection. (os error 10054)

### ISSUE THREAD

**Issue by Misaka299** [redis-rs/redis-rs#1287]
I bought a vps server with debain12 pre-installed on the system.
I installed redis using apt update + apt install redis.
But I can't link using this library.
I can link normally using the rustrover plugin and read and write successfully.

```rust
#[test]
fn test() {
    println!("{}", CFG.redis.url.clone());
    let client = Client::open(CFG.redis.url.clone()).unwrap();
    let mut conn = client.get_connection().unwrap();
    conn.set_write_timeout(Some(Duration::from_secs(1))).unwrap();
    conn.set_read_timeout(Some(Duration::from_secs(1))).unwrap();
    println!("{}", conn.check_connection());
    let _: () = conn.set("xxx", "ddd").unwrap();
}
```
result:
```log
redis://XXX.XXX.XXX.XXX:6379/
false

called `Result::unwrap()` on an `Err` value: The remote host forcibly closed an existing connection. (os error 10054)
thread 'redis::test' panicked at src\redis.rs:58:40:
called `Result::unwrap()` on an `Err` value: The remote host forcibly closed an existing connection. (os error 10054)
```
I replaced the ip in the log with * instead of the * configured in the config file.

redis info
```cmd
127.0.0.1:6379> info server
# Server
redis_version:7.0.15
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:8fef3e995a542118
redis_mode:standalone
os:Linux 6.1.0-7-amd64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:12.2.0
process_id:1277
process_supervised:systemd
run_id:e61b1c4d25087bc6c07dc85f86a25b3ea6fc3931
tcp_port:6379
server_time_usec:1723192250595299
uptime_in_seconds:1916
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:11916218
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0
```

**Comment by nihohit** [comment]
Can you check the server-side logs to see what went wrong?
Maybe the server requires a TLS connection and you've passed an address that doesn't use TLS, or the other way around?

**Comment by Misaka299** [comment]
There is no information printed in the log. I tried to connect to the redis deployed on my local server (from the docker image) and it can be connected normally.

I did not deliberately modify the configuration related to tls, etc. I used the default configuration.


Now I modified the redis settings and added username and password verification. The error becomes os error 10060.

```rust
#[test]
fn test() {
    let client = Client::open(ConnectionInfo {
        addr: ConnectionAddr::Tcp(CFG.redis.host.clone(), CFG.redis.port),
        redis: RedisConnectionInfo {
            db: 0,
            username: CFG.redis.username.clone(),
            password: CFG.redis.password.clone(),
            protocol: ProtocolVersion::RESP3,
        },
    }).unwrap();
    println!("{:?}", client);
    let mut conn = client.get_connection().unwrap();
    conn.set_write_timeout(Some(Duration::from_secs(1))).unwrap();
    conn.set_read_timeout(Some(Duration::from_secs(1))).unwrap();
    println!("{}", conn.check_connection());
    let _: () = conn.set("xxx", "ddd").unwrap();
}
```

Am I missing something or is it version related?

**Comment by nihohit** [comment]
both error codes are from the server, so there isn't a lot that can be done from the client side without understanding why the server/ server's OS rejected the connection. I suggest ensuring that the server logs events, and looking at the server logs in order to understand what happened here.

**Comment by Misaka299** [comment]
But I can connect normally using the redis plugin in rustrover. So I think this may be a problem in the (code) connection process.

**Comment by nihohit** [comment]
Maybe it's a problem on the client side, but again - here isn't a lot that can be done from the client side without understanding why the server/ server's OS rejected the connection. If you can't provide logs, I can't know what redis-rs did differently from the plugin.

**Comment by Misaka299** [comment]
There is no need to solve this problem for the time being, so I will close it first. If there is a need later, I will reopen it and try to provide relevant log information.
