### ISSUE TITLE
When building a ClusterClient using urls, the url param protocol=resp3 has no effect.

### ISSUE THREAD

**Issue by dorentus** [redis-rs/redis-rs#1288]
```rust
let nodes = vec![
  "redis://127.0.0.1:7000?protocol=resp3",
];

let cluster_client = ClusterClientBuilder::new(nodes).build();
```

`cluster_client.cluster_params.protocol` is excepted to be `ProtocolVersion::RESP3` as specified in url params. However it's `ProtocolVersion::RESP2` here.

----

This is because `ClusterClientBuilder` intializes `builder_params` using defaults [here](https://github.com/redis-rs/redis-rs/blob/main/redis/src/cluster_client.rs#L134).

And then inside method `pub fn build(self) -> RedisResult<ClusterClient>`, neither the `builder_params.protocol` property is updated using `first_node.redis.protocol` as other properties do, nor the `redis.protocol` property of each node is checked to be the same among all initial nodes.

Instead, each node's `redis.protocol` is overwritten to `cluster_params.protocol` [here](https://github.com/redis-rs/redis-rs/blob/main/redis/src/cluster_client.rs#L215), which is, unless `use_protocol` been called, the default value `ProtocolVersion::RESP2` initialized in `new`.

**Comment by nihohit** [comment]
indeed, and this is also inconsistent with the behavior for passwords &usernames.
