### ISSUE TITLE
r2d2 pooling for SentinelClient

### ISSUE THREAD

**Issue by smf8** [redis-rs/redis-rs#1294]
Hi, 

Currently, there is no support for SentinelClient in `r2d2.rs`. Adding 
```rust
#[cfg(feature = "sentinel")]
impl_manage_connection!(
    crate::sentinel::SentinelClient,
    crate::Connection
);
```
will fix the compile issue for using `r2d2::Pool<sentinel::SentinelClient>`. Is there any runtime issue for using r2d2 pool with this approach?

**Comment by nihohit** [comment]
from a brief look, it looks feasible. would you like to open a PR?

**Comment by smf8** [comment]
I think we can close it as completed :)
