### ISSUE TITLE
FromRedisValue got warning for rust edition 2024

### ISSUE THREAD

**Issue by TaQuanMinhLong** [redis-rs/redis-rs#1311]
Hi, I've just upgraded to rust 1.81.0 and got this warning from the compiler

```rs
// in edition 2024, the requirement `!: FromRedisValue` will failrustc(dependency_on_unit_never_type_fallback)
pipe.query_async(&mut conn).await?;
```

**Comment by TaQuanMinhLong** [comment]
Sorry for bothering, turns out from now on we need explicite type annotation for return type as `()` in fn with generic return type RV

**Comment by nihohit** [comment]
You can replace query_async with exec_async in order to get rid of the type annotations in this case
