### ISSUE TITLE
ClusterClient fails to connect

### ISSUE THREAD

**Issue by erikschul** [redis-rs/redis-rs#1331]
I'm using KeyDB.

I'm having issues connecting to a cluster using ClusterClient.
```
let nodes = vec![
    "redis://192.168.100.100:6371",
    "redis://192.168.100.100:6372",
    "redis://192.168.100.100:6373",
];

let client = ClusterClient::new(nodes)?;
let mut con = client.get_async_connection().await?;
```

but normal async works fine:
```
let mut con = redis::Client::open("redis://192.168.100.100:6371")?
  .get_async_connection()
  .await?;
```

And `redis-cli` connects correctly to each endpoint, issuing `INFO` command.

Any idea why?

**Comment by nihohit** [comment]
Interesting. I can't reproduce this in the testing suite locally using the test below, and I don't have experience with KeyDB - does it follow the Redis Cluster spec? What kind of errors do you see? Did you check that other clients, maybe in different languages, manage to connect to the DB?

```rs
#[test]
fn test_cluster_connect_with_ip_string() {
    let cluster = TestClusterContext::new();
    let addresses: Vec<_> = cluster
        .nodes
        .iter()
        .map(|address| {
            format!(
                "{}://127.0.0.1:{}",
                match address.addr {
                    redis::ConnectionAddr::Tcp(_, _) => "redis",
                    redis::ConnectionAddr::TcpTls { .. } => "rediss",
                    redis::ConnectionAddr::Unix(_) => unreachable!(),
                },
                match address.addr {
                    redis::ConnectionAddr::Tcp(_, port) => format!("{port}"),
                    redis::ConnectionAddr::TcpTls { port, insecure, .. } =>
                        format!("{port}/{}", if insecure { "#insecure" } else { "" }),
                    redis::ConnectionAddr::Unix(_) => unreachable!(),
                }
            )
        })
        .collect();
    println!("{addresses:?}");

    block_on_all(async move {
        let client = ClusterClient::new(addresses).unwrap();
        let mut con = client.get_async_connection().await.unwrap();

        redis::cmd("SET")
            .arg("{x}key1")
            .arg(b"foo")
            .exec_async(&mut con)
            .await
            .unwrap();
        redis::cmd("SET")
            .arg(&["{x}key2", "bar"])
            .exec_async(&mut con)
            .await
            .unwrap();

        assert_eq!(
            redis::cmd("MGET")
                .arg(&["{x}key1", "{x}key2"])
                .query_async(&mut con)
                .await,
            Ok(("foo".to_string(), b"bar".to_vec()))
        );
        Ok::<_, RedisError>(())
    })
    .unwrap();
}
```

**Comment by erikschul** [comment]
Not a bug.

It seems that the Redis cluster spec cannot distinguish between public and private network.
The internal cluster communication must use the same IP as the clients use, because the MOVED will use the private IP.
There is a configuration `cluster-announce-ip` but it also affects the internal cluster, so the cluster tries to use this IP for internal communication.

This works with `redis-rs` and `keydb`.
However, since the server will return MOVED, it will work with ClusterClient.

It seems that KeyDB has been abandoned (zero contributions recently), so I switched to Valkey, which also works.
Valkey is working on fixing this problem.

**Question:** does ClusterClient just follow redirects? Or does it use hash slots information to query the correct server?
`valkey-cli` will just follow redirects, but the docs suggest that:

> A serious client is able to do better than that, and cache the map between hash slots and nodes addresses, to directly use the right connection to the right node. The map is refreshed only when something changed in the cluster configuration, for example after a failover or after the system administrator changed the cluster layout by adding or removing nodes."

**Comment by nihohit** [comment]
>  Or does it use hash slots information to query the correct server?

Yes, the cluster client hashes the topology view, and refreshes it when receiving MOVED errors.
