### ISSUE TITLE
Should implement `FromRedisValue` for `hashbrown` collections

### ISSUE THREAD

**Issue by feelingsonice** [redis-rs/redis-rs#1358]
Because `hashbrown` is common enough. Shouldn't be difficult?

**Comment by nihohit** [comment]
Since Rust 1.36 the standard HashMap is the same as `hashbrown`. AFAIK having a `hashbrown` dependency only makes sense in a  library/app that doesn't depende on `std`, and `redis-rs` depends on `std`, so I don't see the logic here.

**Comment by feelingsonice** [comment]
>Since Rust 1.36 the standard HashMap is the same as hashbrown
That's cool. Did not know that :)

I guess the practicality of this is that `hashbrown` is still being used in a lot of crates out there. The library I'm working with forces me to use `hashbrown` and it'd take a lot of annoying work to replace it with std hashmap because I'd need to replace its default hasher (since std hashmap still defaults to the SipHash 1-3 hashing). 

Would it make sense to gate this behind a feature flag?

**Comment by nihohit** [comment]
sure, if it's a feature without any additional dependency beyond `hashbrown`.

**Comment by nihohit** [comment]
released in 0.27.5
