### ISSUE TITLE
Allow deleting multiple keys at once

### ISSUE THREAD

**Issue by ashduino101** [redis-rs/redis-rs#1371]
Would it be possible to implement a delete function that takes an array of keys as an argument? It appears [to be possible](https://redis.io/docs/latest/commands/del/). Strangely, I wasn't able to build a multi-arg DEL command directly with this crate that played well with a redis server, though.

**Comment by nihohit** [comment]
Hi, what problems do you have deleting multiple keys? This code works, so I don't see an issue.

```rs
let _: () = con.mset(&[("key1", "val1"), ("key2", "val2")]).unwrap();
let res: Vec<Option<String>> = con.mget(&["key1", "key2"]).unwrap();
assert_eq!(
    res,
    vec![Some("val1".to_string()), Some("val2".to_string())]
);
let res: u64 = con.del(&["key1", "key2"]).unwrap();
assert_eq!(res, 2);
let res: Vec<Option<String>> = con.mget(&["key1", "key2"]).unwrap();
assert_eq!(res, vec![None, None]);
```

**Comment by nihohit** [comment]
I assume from the lack of response that the issue is solved.
