### ISSUE TITLE
`PubSub.get_message()` always timeouts after a EAGAIN is received on the socket once

### ISSUE THREAD

**Issue by cleo-proton** [redis-rs/redis-rs#1375]
Hi !

I am using `PubSub.get_message()` to receive events. Doing so, I think I discovered a bug. 

When messages are available for `get_message()` to return, it returns them just fine. However, if at some point there are no messages to be returned (e.g. because no publish happened) the socket returns a timeout error.  Until here everything works as it should.

However, when calling `get_message()` again a timeout error is returned again no matter whether a message was published or not. Even when messages were published between the first timeout and the subsequent call to `get_message()`, all subsequent calls to `get_message()` return a timeout error.

I believe the bug was introduced between v0.27.3 and v.0.27.4.

Here is a rough simplification of what I am doing that triggers the bug: 

```rust
let pubsub = redis::Client::open("http://127.0.0.1:6379")?.get_connection()?.as_pubsub();
pubsub.subscribe("value")?;
pubsub.set_read_timeout(Some(Duration::from_secs(5)))?;

loop {
  // some reset stuff happening here not involving pubsub

  let msg = match pubsub.get_message() {
      Ok(msg) => msg,
      Err(e) => {
          // Ignore timeout errors, return other ones.
          if e.is_timeout() {
              continue;
          } else {
              return Err(e);
          }
      }
  };

  // do something with msg
}
```

Here is a summary of an strace showing what happens under the hood. Notice the double `recvfrom` after the first timeout.
```
# initialization of the pubsub socket
[pid] connect(5, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
...
# The first n times a message is received this happens:
recvfrom(5, "VALUE", 127, 0, NULL, NULL) = 46
...
# The first time it timeouts:
recvfrom(5, 0x7f72180013b1, 111, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
...
# When subsequent messages arrive this happens:
recvfrom(5, "VALUE", 127, 0, NULL, NULL) = 46
recvfrom(5,  0x7f72180013b1, 111, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
...

```

I believe this double `recvfrom` is introduced by [these changes](https://github.com/redis-rs/redis-rs/compare/redis-0.27.3...redis-0.27.4#diff-6860dcaeb168b0205d6e3e321cb65b6d6aa6db20c3e499c9b1046f826a5ca3b2R1420-R1440)

Since I am not highly familiar with the codebase I did not venture into opening a pull request with a fix but perhaps this could be fixed by editing redis/src/connection.rs:1439 to 
```
} else if io_error.kind() != io::ErrorKind::WouldBlock {
```

Please reach out if you need more information :)

**Comment by nihohit** [comment]
Thanks for reporting this! are you able to pull this fix and see whether it fixes your issue?
https://github.com/redis-rs/redis-rs/pull/1379

**Comment by cleo-proton** [comment]
Seems to work like a charm :)

Thanks a lot !

Do you know if that's going to be put in the next release for cargo and, if so, when the next release is planned ?

Thanks a lot again !

**Comment by nihohit** [comment]
@cleo-proton https://github.com/redis-rs/redis-rs/pull/1386 :)

**Comment by nihohit** [comment]
version 0.27.5 released with the fix. Thanks for reporting the issue!

**Comment by svix-jplatte** [comment]
Is this the reason 0.27.4 was yanked? Would be nice if the GitHub release notes for it could be updated to note the yank reason.

**Comment by nihohit** [comment]
Good idea, I didn't consider that. Thanks!
