### ISSUE TITLE
Redis returns empty map/vec instead of Nil, so Option<T> doesn't work

### ISSUE THREAD

**Issue by YukiTamashi** [redis-rs/redis-rs#1413]
I have a custom type implementing FromRedisValue, and when there's no data inserted for given Key, it returns an empty hashmap or vec when running HGETALL instead of Nil.
Tried for both options, as well as Option<Hashmap<String, String>>.
Only way I got returning option to work was checking for v.clone().into_sequence().is_ok_and(|x| x.is_empty())

Since it could be relevant, this was all running deadpool_redis, with redis running latest image on docker.

**Comment by nihohit** [comment]
Sorry, your issue isn't clear. Can you provide a minimal reproducing example?

**Comment by nihohit** [comment]
and please notice the [HGETALL docs](https://redis.io/docs/latest/commands/hgetall/) - 
"Array reply: a list of fields and their values stored in the hash, or an empty list when key does not exist"
so it looks like `redis-rs` parses correctly the received output from the DB.

**Comment by nihohit** [comment]
Great, happy to help :)
