### ISSUE TITLE
Vectors are converted incorrectly

### ISSUE THREAD

**Issue by karipov** [redis-rs/redis-rs#1418]
I'm trying to implement search with vector embeddings, and my hunch is that redis-rs isn't converting the embedding vector correctly. Below is the general query, where `@embedding` is a `VECTOR FLAT TYPE FLOAT 32 DIM 1536` field.

```
FT.SEARCH
    my_idx "(*)=>[KNN "10" @embedding $vector AS score]"
    PARAMS 2 vector "<VECTOR BLOB HERE>"
    SORTBY score ASC
    DIALECT 4
```

Here's how I wrote it using `redis-rs` (let's ignore the search result for now).

```rust
pub async fn search_embedding(embedding: Vec<f32>, num_results: usize) {
    redis::cmd("FT.SEARCH").arg(REDIS_INDEX)
        .arg(format!("\"(*)=>[KNN {} @embedding $query_vector AS score]\"", num_results))
        .arg("PARAMS").arg(2).arg("query_vector").arg(embedding) // <--- I think the issue is here
        .arg("SORTBY").arg("score").arg("ASC")
        .arg("DIALECT").arg(4)
        .query_async(&mut con).await?;
}
```
Output, which I assume it's unhappy about the vector encoding:
```
Unknown: argument `-0.009208069` at position 5
```

I think what Redis expects is some blob-ified vector representation, but `.arg(embedding)` isn't converting the vector correctly. How could I fix this? Any help would be appreciated.

Some docs + links to how the same query is done in Python:
- https://redis.io/docs/latest/develop/interact/search-and-query/query/vector-search/
- https://redis.io/docs/latest/develop/get-started/vector-database/
- https://cookbook.openai.com/examples/vector_databases/redis/getting-started-with-redis-and-openai

**Comment by karipov** [comment]
Solved using this wonderful Reddit post: https://www.reddit.com/r/rust/comments/17mq12b/how_to_parse_complex_redis_response/

Essentially, had to convert the embedding to a byte sequence like so:
```
 let raw_types: Vec<u8> = embedding.iter().flat_map(|&f| f.to_ne_bytes()).collect();
```

**Comment by Stephen-X** [comment]
> Solved using this wonderful Reddit post: https://www.reddit.com/r/rust/comments/17mq12b/how_to_parse_complex_redis_response/
> 
> Essentially, had to convert the embedding to a byte sequence like so:
> 
> ```
>  let raw_types: Vec<u8> = embedding.iter().flat_map(|&f| f.to_ne_bytes()).collect();
> ```

Thanks for leaving a note here! Just FYI, I'd recommend use of `to_le_bytes()` explicitly. Redis only uses little endian, see also https://github.com/redis/jedis/issues/3127.
