### ISSUE TITLE
response_timeout overrides connection_timeout when connecting

### ISSUE THREAD

**Issue by RockyGitHub** [redis-rs/redis-rs#1442]
Hello,

I want to sue the ConnectionManager for auto reconnects, but I found that the connection hangs/timeouts when I use this over "get_multiplexed_tokio_connections()"

I dug a little further and found that the connection manager uses a closure container `client.get_multiplexed_async_connection_with_config(&connection_config).await`. I believe this is incompatible because when I change this line to `client.get_multiplexed_tokio_connection().await`, it is suddenly working.
Line 371 of connection_manager.rs

Is ConnectionManager no longer supported with tokio?

**Comment by nihohit** [comment]
I'm sorry, I don't understand the issue you're facing. What does " I found that the connection hangs/timeouts when I use this over "get_multiplexed_tokio_connections()"" mean? can you provide a complete reproduction, preferably using the crate's test system (see test_async.rs).

In any case, `connection-manager` works with tokio, and is tested with Tokio in the CI regularly. I double checked, and tested the connection manager with `get_tokio_connection_manager` instead of `get_connection_manager`, and that works too, so I couldn't reproduce the issue.

**Comment by RockyGitHub** [comment]
Hi nihohit, thanks for your response and for looking into this!

To clarify, the "hang/timeout" is referring to calling .await on "get_connection_manager_with_config(config).await".  The connection isn't made and it continues to retry. I shouldn't have said hang/stuck, it fails/errors with `value: timeout`

I just checked and connecting to a localhost redis is working just fine (my rust app is connecting to it) using ConnectionManager. But when I connect to my deployment, the connection manager doesn't work. I have to switch the internal call as I described in the OP, or simply skip the connection manager and use the `get_multiplexed_tokio_connection()` for it to connect

It is super duper strange that the ConnectionManager won't connect to the deployed redis but the MultiplexedConnection will..  I can create a reproduction but tbh it's nothing more than make a client, config, connection manager, println. 

#[tokio::main(flavor = "multi_thread")]
async fn main() {
```rs
    let client = redis::Client::open(
        "redis://core-dev.us.cache.amazonaws.com:6379",
    )
    .unwrap();

    let cm_config = ConnectionManagerConfig::new()
        .set_response_timeout(Duration::from_millis(100))
        .set_connection_timeout(Duration::from_millis(100))
        .set_max_delay(100);

    let mut con = client
        .get_connection_manager_with_config(cm_config)
        .await
        .unwrap();

    println!("made it here!");
}
```

I am still baffled that the difference of it working is in connecting to a deployment or to localhost. Yet it totally works fine to my deployment if using multiplxedconnection tokio.

**Comment by RockyGitHub** [comment]
oh my golly gee, the issue is in my config!

If response timeout is too low, it won't connect..! I suppose it's confusing that response_timeout can override the connection_timeout, perhaps that's my "issue #" here instead. (I originally had a higher connection_timeout, but response was low)

**Comment by RockyGitHub** [comment]
This feels like a very minor confusion type of issue so I'm just gonna close it. In reality, connection timeout and response timeout will always be similar if not the same in a normal configuration, I think.

**Comment by nihohit** [comment]
Interestingly enough, I can connect even when setting response_timeout to be 0, so I'm not sure how to reproduce this issue.
