### ISSUE TITLE
Multiplexed connection driver unexpectedly terminated

### ISSUE THREAD

**Issue by sssemil** [redis-rs/redis-rs#1446]
Getting `WithDescription(IoError, "Multiplexed connection driver unexpectedly terminated")` when sending a lot of requests. Any idea on how to work around this issue? Thanks.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a retry mechanism to the MultiplexedConnection struct to handle unexpected termination of the multiplexed connection driver. This includes adding a new method for retrying connections and modifying the send_packed_command and send_packed_commands methods to use this retry mechanism.

You can review changes in this commit: https://github.com/mnmnk43434/redis-rs-redis-rs-1446/commit/4d5b2ee895cdc22391c4af9c950e90df20e73f4c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by nihohit** [comment]
@sssemil can you provide a working, self contained example of this happening?
In any case, if you're looking for automatic reconnection, try using `ConnectionManager` instead of `MultiplexedConnection`.

**Comment by sssemil** [comment]
> @sssemil can you provide a working, self contained example of this happening? In any case, if you're looking for automatic reconnection, try using `ConnectionManager` instead of `MultiplexedConnection`.

Think it was just too many connections created too quickly, I switched to using a pool of connections instead, which solved all my issues. Will check out `ConnectionManager`, looks helpful, thanks!

**Comment by nihohit** [comment]
Did you create a connection per-request? That could overwhelm the system, yes.
