### ISSUE TITLE
Problem with passwords that contain special characters

### ISSUE THREAD

**Issue by CoRfr** [redis-rs/redis-rs#152]
While trying to use a password provided by Azure redis, I am having trouble since it doesn't seem to handle it properly.

The connection string looks like: `"redis://:RanDoMStRIng=@bugredis.redis.cache.windows.net:6379/"`
So here the password is `RanDoMStRIng=`, but it is percent encoded by default by `url` so it actually tries to use `RanDoMStRIng%3D` as a password, which eventually fails.

My understanding is that we should `percent_decode` the password before using it.

I have never coded in rust before an hour ago, so I'm gonna try to do a PR on this but can't promise anything.

**Comment by badboy** [comment]
At that point you might just want to directly construct a [`ConnectionInfo`](https://github.com/mitsuhiko/redis-rs/blob/b5909f5eb9a374853befd37ecb63b4999f54306b/src/connection.rs#L70), as "RanDoMStRIng%3D" is just as well an acceptable password as is "RanDoMStRIng=", so doing any decoding will just lead to the reverse problem for someone else.

**Comment by CoRfr** [comment]
`RanDoMStRIng%3D` is a perfectly valid password as well, but as passed in the URL `redis://:RanDoMStRIng%3D@...` means that password is `RanDoMStRIng=`.
To pass `RanDoMStRIng%3D` through the URL you would need to encode the %, resulting in `redis://:RanDoMStRIng%253D@...`.

**Comment by lilydjwg** [comment]
I have this issue too. My Redis has a `@` in it, so I cannot pass my Redis connection info as a URL because this crate will use the wrong encoded password.

It's suboptimal to parse the URL on my own, or not to use an URL, because a URL is much easier to pass as a setting.

FYI diesel has already [fixed](https://github.com/diesel-rs/diesel/pull/1058) this kind of bugs last year.

**Comment by badboy** [comment]
Convinced. I reviewed the PR, it needs some changes but I'm happy to move forward with the general idea.

**Comment by max-sixty** [comment]
Is this closed by #163?

**Comment by badboy** [comment]
It probably is.

**Comment by DevineLiu** [comment]
We should add some simple examples, build conn via struct.
eg:
```rust
let coninfo = redis::ConnectionInfo {
            addr: redis::ConnectionAddr::Tcp("127.0.0.1".into(), 6379),
            redis: redis::RedisConnectionInfo {
                db: 0,
                username: None,
                password: env::var("REDIS_PASSWORD").ok(),
            },
        }
let client = redis::Client::open(coninfo)?;
let mut con = client.get_connection()?;
```

**Comment by djc** [comment]
Going to close this as it looks like the core issue is closed. (TBH I don't think an example is worth it for something basic like this.)
