### ISSUE TITLE
Nil response from bulk query

### ISSUE THREAD

**Issue by davechallis** [redis-rs/redis-rs#174]
I've got some code of the form:

    debug!("start query");
    let r: redis::Value = redis::pipe()
        .atomic()
        .exists("my_key")
        .hget("my_key", "my_field")
        .query(&conn).unwrap();
    debug!("response: {:?}", r);
    let (exists, field): (bool, Option<String>) = redis::from_redis_value(&r).unwrap();

However, on a busy system with multiple clients (some using transactions), sometimes the response to the bulk query above is `Nil`, which causes the `from_redis_value` call to panic (with `Response was of incompatible type: "Not a bulk response" (response was nil)`).

The log output from my application's logging contains:

    start query
    response: nil

However, looking at the commands Redis executes using `redis-cli monitor` shows that it never receives/executes the following expected commands:

    MULTI
    EXISTS "my_key"
    HGET "my_key" "my_field"
    EXEC

Are there any circumstances where a Nil response from the above code is expected, or where the redis crate could return `Ok` for a query which failed in some way?

Do you have any advice or recommendations on debugging/investigating this further in the redis crate?

In the meantime, I'll carry on trying to get a minimal fully working example (at the moment it's only occurring in the middle of a fairly complex app).

**Comment by davechallis** [comment]
Update: I modified the code to include an artificial query to better help trace what was being executed on a single connection. So example query now looks like:

    debug!("start query");
    let _: () = conn.exists("my_key").unwrap();
    let r: redis::Value = redis::pipe()
        .atomic()
        .exists("my_key")
        .hget("my_key", "my_field")
        .query(&conn).unwrap();
    debug!("response: {:?}", r);
    let (exists, field): (bool, Option<String>) = redis::from_redis_value(&r).unwrap();

Tracing the commands on that connection using `redis-cli monitor` appears to show that nothing gets executed in the atomic pipe, output is:

    1543503181.845563 [0 172.17.0.1:34328] "EXISTS" "my_key"
    1543503181.847037 [0 172.17.0.1:34328] "MULTI"
    1543503181.847044 [0 172.17.0.1:34328] "EXEC"

i.e. both the `EXISTS` and `HGET` commands are missing for some reason.

**Comment by jwilm** [comment]
Which version of the crate are you using?

**Comment by davechallis** [comment]
@jwilm sorry, my bad, forgot to include that.

redis crate version: 0.9.1
redis-server version: 5.0.0

**Comment by nihohit** [comment]
Cannot recreate this. closing as out of date.
