### ISSUE TITLE
query_async cannot be used with redis clustering

### ISSUE THREAD

**Issue by stew** [redis-rs/redis-rs#178]
With redis clustering, if you try to `GET` a key from a redis node which is actually stored on another part of the cluster, you get back a MOVED response:

    MOVED: 10975 10.61.179.133:6379

as an ExtensionError. The problem is that because the `query_async` method consumes the connection and only returns the connection with a successful result, it means I cannot reuse this connnection after this routine error message. In my case, I expect the reply to be a MOVED error most of the time for my first request, which means I have to re-open connections constantly.

Would it make sense to also modify `query_async` to also return the connection on the error side of the `Result`?

**Comment by badboy** [comment]
It probably should, as there are definitely more recoverable error responses that could happen.

**Comment by Marwes** [comment]
Never got caught by this since I only use the shared connection which can be cloned, but yes this should be fixed for the normal connection.

**Comment by adelbertc** [comment]
@Marwes Can you elaborate on what you mean by shared connection? Or do you mean using the synchronous API instead of the async one?

**Comment by Marwes** [comment]
https://docs.rs/redis/0.9.1/redis/async/struct.SharedConnection.html allows cloning and running multiple queries concurrently on a single connection. So since it can be cloned I usually just ignore the returned connection.

**Comment by jensenn** [comment]
A lot has happened since this issue was opened. I would like to use clustering + async, but couldn't quite figure out the magic combination to do that. Is it possible in the current code?

**Comment by Marwes** [comment]
@jensenn There is now https://crates.io/crates/redis_cluster_async. Might merge it back into redis-rs at some point.

**Comment by jensenn** [comment]
If not, with some architectural direction, I could possibly take a shot at it.

**Comment by jensenn** [comment]
I've seen that one, but I can no longer see the original repository. I actually ran into an issue with that crate where it doesn't handle EVAL and EVALSHA correctly for computing the correct keyslot. I considered committing a fix, but it looks to be gone.

**Comment by Marwes** [comment]
Fixed the link to it https://github.com/Marwes/redis-cluster-async

**Comment by jensenn** [comment]
Oh, sorry. I just realized that you are the owner! Now that I know it is still maintained, I will look at giving you a pull request to get EVAL and EVALSHA working.

**Comment by yiv** [comment]
@Marwes when I use redis-cluster-async to handle stream from cluster, I got this error: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: An error was signalled by the server: 14466 127.0.0.1:7002', src/main.rs:41:149
```



```
cmd("XREAD").arg(opts).arg("STREAMS").arg(keys.clone()).arg(ids.clone()).query_async::<Connection, StreamReadReply>(&mut con).await.unwrap();
```

**Comment by Marwes** [comment]
I haven't tested it using streams so there is probably some bugs there. Might select the wrong key for sharding.

**Comment by yiv** [comment]
@Marwes 
This is my key:
> channel:bot:137225053866557440

Yes, the key matters. I try it with other key, for example: 
> channel:bots:137225053866557440
It  works fine.

But use non-async cluster connection in redis-rs, all work fine.

**Comment by yiv** [comment]
I have located the issue, It's because of function **slot_for_command** return a wrong slot number. The function didn't get the correct argument position when handle Redis command **XREAD** and **XREADGROUP**, after add a match arm to the function like below, it works well 

* before
```

fn slot_for_command(cmd: &Cmd) -> Option<u16> {
    match get_cmd_arg(cmd, 0) {
        Some(b"EVAL") | Some(b"EVALSHA") => {
            get_cmd_arg(cmd, 2).and_then(|key_count_bytes| {
                let key_count_res = std::str::from_utf8(key_count_bytes)
                    .ok()
                    .and_then(|key_count_str| key_count_str.parse::<usize>().ok());
                key_count_res.and_then(|key_count| {
                    if key_count > 0 {
                        get_cmd_arg(cmd, 3).map(|key| slot_for_key(key))
                    } else {
                        // TODO need to handle sending to all masters
                        None
                    }
                })
            })
        }
        Some(b"SCRIPT") => {
            // TODO need to handle sending to all masters
            None
        }
        _ => get_cmd_arg(cmd, 1).map(|key| slot_for_key(key)),
    }
}
```

* after 
```
fn slot_for_command(cmd: &Cmd) -> Option<u16> {
    match get_cmd_arg(cmd, 0) {
        Some(b"EVAL") | Some(b"EVALSHA") => {
            get_cmd_arg(cmd, 2).and_then(|key_count_bytes| {
                let key_count_res = std::str::from_utf8(key_count_bytes)
                    .ok()
                    .and_then(|key_count_str| key_count_str.parse::<usize>().ok());
                key_count_res.and_then(|key_count| {
                    if key_count > 0 {
                        get_cmd_arg(cmd, 3).map(|key| slot_for_key(key))
                    } else {
                        // TODO need to handle sending to all masters
                        None
                    }
                })
            })
        }
        Some(b"SCRIPT") => {
            // TODO need to handle sending to all masters
            None
        }
        Some(b"XREAD") | Some(b"XREADGROUP") => {
            let streams_position = cmd.args_iter().position(|arg| match arg {
                redis::Arg::Simple(arg) => arg == b"STREAMS",
                _ => false,
            })?;
            get_cmd_arg(cmd, streams_position+1).map(|key| {
                slot_for_key(key)
            })
        }
        _ => get_cmd_arg(cmd, 1).map(|key| slot_for_key(key)),
    }
}
```

**Comment by nihohit** [comment]
there's now an async implementation for a cluster connection.
