### ISSUE TITLE
Connection pooling support for async operation

### ISSUE THREAD

**Issue by suraj99p** [redis-rs/redis-rs#218]
I need to write a redis client working in  async mode. We would like to run inside a mpsc receiver and for each request fire the command to redis. We do not want to create  a connection for each client as it will have overhead for each command, we would like to create a pool and keep a persistent TCP connection and multiplex commands on this.

**Comment by Marwes** [comment]
https://docs.rs/redis/0.11.0-beta.1/redis/aio/struct.SharedConnection.html is meant for this use case, it can be cloned and used from everywhere (already uses channels under the hood).

**Comment by suraj99p** [comment]
How do specify pool size or number of connections?

**Comment by Marwes** [comment]
It is just a single connection but that connection does not block further requests while there are are requests in flight. So you can run as many requests as you want on it (you are bound only by IO and single threaded CPU performance on the client and server).

**Comment by suraj99p** [comment]
Ok how do i ensure that connection is still valid and not broken?

**Comment by Marwes** [comment]
Sending https://redis.io/commands/ping would be the simplest way (but be aware that doing any connection check before sending the actual message is no guarantee that the connection won't be broken when the actual message is sent).

**Comment by suraj99p** [comment]
So how do i manage all these scenarios, can you plz guide me how to design this connection manager?

**Comment by suraj99p** [comment]
So cases i can think of are
1) get a new shared connection when previous connection is closed?
2) ping at a given interval, i cant ping before sending each request. That will be a overkill and impact my throughput
3) graceful shutdown and close socket on program close

Any other cases I need to handle apart from these 3?

**Comment by Marwes** [comment]
You can send messages on the connection and when you receive an error which warrants a reconnection, then re-connect and swap the old connection with the new connection in your "Manager". If a request needs to be ran again after an error you make sure to run that on the new connection.

**Comment by Marwes** [comment]
If you have multiple requests in flight when the connection goes down you should also be careful that you only reconnect once.

**Comment by Marwes** [comment]
> ping at a given interval, i cant ping before sending each request. That will be a overkill and impact my throughput

Can be useful if you have periods of downtime and don't want the first request after downtime to (potentially) need to retry if the connection has closed. Otherwise I wouldn't bother with it as any frequently used connection are more likely to report errors on a normal request instead.

**Comment by suraj99p** [comment]
do you plan to implement a connection manager for above use case in near future?

**Comment by suraj99p** [comment]
> 
> 
> > ping at a given interval, i cant ping before sending each request. That will be a overkill and impact my throughput
> 
> Can be useful if you have periods of downtime and don't want the first request after downtime to (potentially) need to retry if the connection has closed. Otherwise I wouldn't bother with it as any frequently used connection are more likely to report errors on a normal request instead.

Agreed. I think we need not have this ping mechansim

**Comment by Marwes** [comment]
I have something like you described at work so it is unfortunately proprietary, it could probably be made open source but it isn't really in shape for that as it is and needs approvals etc. Not going to have time for it in the close future in any case.

It is only ~100 lines of code at least so re-implementing isn't to bad.

**Comment by importcjj** [comment]
try https://github.com/importcjj/mobc/tree/master/redis

**Comment by mattcollier** [comment]
I see that the async API has landed on master: https://github.com/mitsuhiko/redis-rs/pull/232
I have also looked over the tests: https://github.com/mitsuhiko/redis-rs/blob/master/tests/test_async.rs

It's unclear to me if a connection pool is needed or wanted with this latest code.  It appears to me that passing a `MultiplexedConnection` instance around is the thing to do?

More specifically, if used in conjunction with actix, would passing the `MultiplexedConnection` to a route handler be the thing as here?

https://github.com/actix/examples/blob/master/r2d2/src/main.rs#L47

**Comment by Marwes** [comment]
Connection pooling is pretty much redundant for async queries (unless sending all request on one socket saturates it somehow, allowing multiple connections to perform better).

Having reconnection support may be useful still though.

> More specifically, if used in conjunction with actix, would passing the MultiplexedConnection to a route handler be the thing as here?

Yes, I think so.

**Comment by dbrgn** [comment]
Hi @Marwes, thanks already for the information you gave in here.

I'm also currently implementing an asynchronous web service with long-running connections that uses Redis a lot. If I understand you correctly:

- On startup of the server, I'd create a client and derive a single `MultiplexedConnection` from that
- When using `get_multiplexed_async_connection`, I have to ensure to pass the driver to the executor (e.g. `tokio::spawn(driver)`)
- Every time a client connects, I'd clone that connection and pass the cloned instance to the connection handler
- The `MultiplexedConnection` wraps a `Pipeline`
- The `Pipeline` is essentially a stream + a sink
- If the connection fails for some reason, then every command executed on that multiplexed connection will fail with an `ErrorKind::IoError`, there is no automatic reconnection logic in case of connection loss

Is that correct so far? If yes, then I'd assume that:

- I would need some kind of proxy object that wraps the `MultiplexedConnection` and allows sending commands
- All commands would go through that proxy
- If a connection error occurs, I would need to terminate all affected client connections with an error
- The manager would then throw away the old connection and create a new one internally
- As soon as the connection is re-established, all future commands would succeed again

Am I on the right path?

**Comment by Marwes** [comment]
> Is that correct so far? If yes, then I'd assume that:

Yep.

> I would need some kind of proxy object that wraps the MultiplexedConnection and allows sending commands

You probably want some sort of wrapper that knows when to reconnect, yes. The exact API may differ depending on what you want to do on errors (retry the command or just fail the request).

> If a connection error occurs, I would need to terminate all affected client connections with an error

I don't think cancellation is needed. If a connection error occurs, then each request will fail and the issuer of the request can then do its own error handling.

> The manager would then throw away the old connection and create a new one internally
As soon as the connection is re-established, all future commands would succeed again

Yep. https://docs.rs/futures/0.3.1/futures/future/trait.FutureExt.html#method.shared can be useful here. Letting each call to "get_connection" just await on a `Shared` re-connect attempt.

**Comment by dbrgn** [comment]
@suraj99p is your use case covered by #278? It's part of the 0.16 release.

**Comment by nihohit** [comment]
@suraj99p, is this issue still relevant? if not, I'll close it.
