### ISSUE TITLE
zscan not implemented on MultiplexedConnection?

### ISSUE THREAD

**Issue by nazar-pc** [redis-rs/redis-rs#297]
```
error[E0599]: no method named `zscan` found for mutable reference `&mut redis::aio::MultiplexedConnection` in the current scope
  --> src/redis_client_wrapper.rs:34:14
   |
34 |             .zscan::<&str, (String, String)>(key)
   |              ^^^^^ method not found in `&mut redis::aio::MultiplexedConnection`
   |
   = note: the method `zscan` exists but the following trait bounds were not satisfied:
           `&mut redis::aio::MultiplexedConnection : redis::commands::Commands`
           `redis::aio::MultiplexedConnection : redis::commands::Commands`
```

Other related commands are available though.

**Comment by badboy** [comment]
Indeed we currently don't define these functions for the async part, only the sync part, see this:

https://github.com/mitsuhiko/redis-rs/blob/1ea0bd0c2e7b450eb5279995142fd64e5db0fa69/src/commands.rs#L48-L60

We probably should support that.

**Comment by GopherJ** [comment]
I ran into similar issue:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_multiplexed_tokio_connection().await?;
    let mut pubsub = con.as_pubsub();
    pubsub.subscribe("channel_1")?;
    pubsub.subscribe("channel_2")?;

    loop {
        let msg = pubsub.get_message()?;
        let payload: String = msg.get_payload()?;
        println!("channel '{}': {}", msg.get_channel_name(), payload);
    }
    Ok(())
}

```

**Comment by badboy** [comment]
> I ran into similar issue:

Same, it's not implemented. I don't have time to do that.

**Comment by swilcox3** [comment]
I'd like to bump this as well.  I'd like to SSCAN over my set and return the entries in a `futures::Stream` because this particular set could potentially get very large.  I've gotten far enough that I can wrap the regular `redis::Connection` in a `try_stream` and call that successfully in a sync context:
```
pub fn get_latest_obj_list(
    mut conn: redis::Connection,
    file: String,
) -> impl Stream<Item = Result<String, ObjError>> {
    try_stream! {
        let latest_list = latest_obj_list(&file);
        let mut cmd = redis::cmd("SSCAN");
        let mut iter: redis::Iter<String> = cmd.arg(latest_list).cursor_arg(0).clone().iter(&mut conn)?;
        for id in iter {
            yield id;
        }
    }
}
```
However, I can't call this in an async context because `redis::Connection` is not `Send`.  
```
error: future cannot be sent between threads safely
   --> objects\src\main.rs:78:9
    |
78  |         tokio::spawn(async move {
    |         ^^^^^^^^^^^^ future is not `Send`
    | 
   ::: C:\Users\purfe\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.17\src\task\spawn.rs:127:21
    |
127 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
    = help: the trait `std::marker::Send` is not implemented for `dyn redis::connection::ConnectionLike`
note: future is not `Send` as this value is used across an await
   --> objects\src\cache.rs:134:5
    |
134 | /     try_stream! {
135 | |         let latest_list = latest_obj_list(&file);
136 | |         let mut cmd = redis::cmd("SSCAN");
137 | |         let mut iter: redis::Iter<String> = cmd.arg(latest_list).cursor_arg(0).clone().iter(&mut conn)?;
    | |                                                                                             --------- has type `&mut dyn redis::connection::ConnectionLike`
...   |
140 | |         }
141 | |     }
    | |     ^
    | |     |
    | |_____await occurs here, with `&mut conn` maybe used later
    |       `&mut conn` is later dropped here
```

I understand you're busy, my workaround for now is just to use `smembers` and return a stream over that instead.  A feature request for some future time would be to implement the *SCAN related methods on MultiplexedConnection, perhaps returning a `futures::Stream` instead of a `redis::Iter` if that's easier.

**Comment by badboy** [comment]
Again, if you need that I highly appreciate a pull request.
I don't have the time nor the need to implement it, but I might be able to squeeze in a review if there is code to review.

**Comment by swilcox3** [comment]
Welp, I took a look at it, tried to make an AsyncIter to go along with Iter, and made it implement futures::Stream instead of Iterator.  Unfortunately, you can't call async functions inside a `poll_next` implementation, so you can't use the MultiplexedConnection in there.  The other idea I had was to just return a `try_stream!` directly from the AsyncCommands implementation of *SCAN methods, but that doesn't work because it bypasses your whole Cmd infrastructure.  So basically, while technically possible to do, it would require a pretty big refactor of large parts of the crate.  I guess I'll stick with `smembers`.

**Comment by swilcox3** [comment]
Welp, I took a look at it, tried to make an AsyncIter to go along with Iter, and made it implement futures::Stream instead of Iterator.  Unfortunately, you can't call async functions inside a `poll_next` implementation, so you can't use the MultiplexedConnection in there.  The other idea I had was to just return a `try_stream!` directly from the AsyncCommands implementation of *SCAN methods, but that doesn't work because it bypasses your whole Cmd infrastructure.  So basically, while technically possible to do, it would require a pretty big refactor of large parts of the crate.  I guess I'll stick with `smembers`.

**Comment by Marwes** [comment]
@swilcox3 You should be able to do it by using https://docs.rs/futures/0.3.5/futures/stream/fn.try_unfold.html and returing `Pin<Box<dyn Stream>>` from the function. Then you can call async functions freely.

**Comment by swilcox3** [comment]
OK, I've got this implementation now:
```
#[cfg(feature = "aio")]
pub struct AsyncIter<T: FromRedisValue> {
    batch: Vec<T>,
    cursor: u64,
    con: crate::aio::MultiplexedConnection,
    cmd: Cmd,
}
use crate::aio::ConnectionLike as AsyncConnection;

#[cfg(feature = "aio")]
impl<T: FromRedisValue> AsyncIter<T> {
    #[inline]
    pub fn stream(self) -> impl futures::Stream<Item = T> {
        // we need to do this in a loop until we produce at least one item
        // or we find the actual end of the iteration.  This is necessary
        // because with filtering an iterator it is possible that a whole
        // chunk is not matching the pattern and thus yielding empty results.
        futures::stream::unfold(self, |mut cur_self| async move {
            loop {
                if let Some(v) = cur_self.batch.pop() {
                    return Some((v, cur_self));
                };
                if cur_self.cursor == 0 {
                    return None;
                }

                let rv = unwrap_or!(
                    cur_self.con.req_packed_command(&cur_self.cmd).await.ok(),
                    return None
                );
                let (cur, mut batch): (u64, Vec<T>) =
                    unwrap_or!(from_redis_value(&rv).ok(), return None);
                batch.reverse();

                cur_self.cursor = cur;
                cur_self.batch = batch;
            }
        })
    }
}
```
That compiles.  So I added an `iter_async` function to `Cmd`:
```
    #[cfg(feature = "aio")]
    #[inline]
    pub async fn iter_async<T: FromRedisValue>(
        self,
        mut con: crate::aio::MultiplexedConnection,
    ) -> RedisResult<AsyncIter<T>> {
        let rv = con.req_packed_command(&self).await?;

        let (cursor, mut batch) = if rv.looks_like_cursor() {
            from_redis_value::<(u64, Vec<T>)>(&rv)?
        } else {
            (0, from_redis_value(&rv)?)
        };

        batch.reverse();
        Ok(AsyncIter {
            batch,
            cursor,
            con,
            cmd: self,
        })
    }
```
The main problem with these is that they require `MultiplexedConnection` in particular, because `req_packed_command` can't be called on a trait object.  It also requires a move, not a `&mut`.  
This causes problems in the `AsyncCommands` implementation.  I tried to do it like this:
```
            #[inline]
            async fn scan<RV: FromRedisValue>(self) -> RedisResult<AsyncIter<RV>> {
                let mut c = cmd("SCAN");
                c.cursor_arg(0);
                let iter = c.iter_async(self).await;
                iter
            }
```
This gives me the error:
```
 pub trait AsyncCommands : crate::aio::ConnectionLike + Send + Sized {
167  | |             $(
168  | |                 $(#[$attr])*
169  | |                 #[inline]
...    |
215  | |                 let iter = c.iter_async(self).await;
     | |                                         ^^^^ expected struct `aio::MultiplexedConnection`, found type parameter `Self`
...    |
255  | |             }
256  | |         }
```
Any ideas?  Or do we just leave it off AsyncCommands and only expose it through the Cmd interface?

**Comment by Marwes** [comment]
You can remove the `Sized` bound from `ConnectionLike` and it should work without being limited on `MultiplexedConnection`

**Comment by swilcox3** [comment]
OK, I removed the `Sized` bound, that seems to work.  If we don't own the connection, though, we get this error:
```
error[E0482]: lifetime of return value does not outlive the function call
  --> src\cmd.rs:86:28
   |
86 |     pub fn stream(self) -> impl futures::Stream<Item = T> {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the return value is only valid for the lifetime `'a` as defined on the impl at 84:6
  --> src\cmd.rs:84:6
   |
84 | impl<'a, T: FromRedisValue> AsyncIter<'a, T> {
   |      ^^
```
What I believe this means is that the borrow checker is worried that we'll return a stream which has its own lifetime, and that the reference to the connection inside the stream could be dropped before the stream is dropped.  I'm not sure how to annotate a `impl Stream` return value with a lifetime though.  Is that possible?

**Comment by swilcox3** [comment]
Passing in a Box<dyn ConnectionLike> works, haven't figured out how to expose it to AsyncCommands yet, it's got some weird lifetime errors.  I made a test function anyways:
```
#[test]
fn test_async_scanning() {
    let ctx = TestContext::new();
    block_on_all(async move {
        ctx.multiplexed_async_connection()
            .and_then(|mut con| {
                async move {
                    let mut unseen = std::collections::HashSet::new();

                    for x in 0..1000 {
                        redis::cmd("SADD")
                            .arg("foo")
                            .arg(x)
                            .query_async(&mut con)
                            .await?;
                        unseen.insert(x);
                    }

                    let iter = redis::cmd("SSCAN")
                        .arg("foo")
                        .cursor_arg(0)
                        .clone()
                        .iter_async(Box::new(con))
                        .await
                        .unwrap();

                    let stream = iter.stream();
                    futures::pin_mut!(stream);
                    while let Some(x) = stream.next().await {
                        // type inference limitations
                        let x: usize = x;
                        unseen.remove(&x);
                    }

                    assert_eq!(unseen.len(), 0);
                    Ok(())
                }
            })
            .map_err(|err| panic!("{}", err))
            .await
    })
    .unwrap();
}
```
Unfortunately, I'm on Windows, so I don't have `redis-server` available from command line and the tests don't work.  I usually run redis in Docker.  But whatever, this implementation seems to work.  Is passing in a Box a no-go?

**Comment by Marwes** [comment]
`impl futures::Stream<Item = T> + 'a` works to bound the `Stream`.

Returning a boxed stream is okay, and necessary to let the method be defined on the trait itself just as the ones defined for the sync connection

**Comment by swilcox3** [comment]
OK great, thanks for your help.  Pull request at https://github.com/mitsuhiko/redis-rs/issues/297

**Comment by kennetpostigo** [comment]
Does this allow cloning a pubsub connection? Was the pull request merged? (The link above points to this ticket not a pr)

**Comment by nihohit** [comment]
async support for ZSCAN is merged.
