### ISSUE TITLE
pubsub support for MultiplexedConnection?

### ISSUE THREAD

**Issue by GopherJ** [redis-rs/redis-rs#303]

**Comment by nihohit** [comment]
What's the need here?
MultiplexedConnection's architecture doesn't allow for simple Pub/Sub, since it's strictly send/respond. Implementing this won't be simpler, so we'll only attempt it if there's a specific need for it.

**Comment by esemeniuc** [comment]
Would love to see this, I don't enjoy having to maintain reconnection logic in my loops

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/898

**Comment by nihohit** [comment]
pubsub support has been added with RESP3 support.
