### ISSUE TITLE
Pubsub loses channel messages when dynamic subscribing channels in the same pubsub

### ISSUE THREAD

**Issue by milabobo** [redis-rs/redis-rs#310]
redis-rs version: 0.15.1
Environment: MacOS
Cargo version: 1.42

Hey, guys:
        I found pubsub might lose channel messages when subscribing another channel in handing incoming messages, for startup, i subscribe channel "foo", then i publish some messages to the channel, after receiving some messages from the channel, i try to subscribe another channel within the message handing loop, then i found some messages lost. I have written a test code below:

```Rust
use std::thread;
use std::time::Duration;
use redis::{self, cmd};

fn main() -> Result<(), Box<dyn std::error::Error>>  {
    let client = redis::Client::open(format!("redis://127.0.0.1:6379"))?;
    let clone_client = client.clone();
    // receive message from foo channel
    thread::spawn(move || {
        let mut conn = client.get_connection().unwrap();
        let mut pubsub = conn.as_pubsub();
        pubsub.subscribe("foo").unwrap();
        loop {
            let msg = pubsub.get_message().unwrap();
            let channel = msg.get_channel_name();
            let content: i32 = msg.get_payload().unwrap();
            println!("receive channel {}, message {}", channel, content);
            if content == 5 {
                // subscribe bar channel using the same pubsub
                println!("sub bar channel");
                pubsub.subscribe("bar").unwrap();
            }
        }
    });
    // send message to foo channel
    thread::sleep(Duration::from_secs(1));
    let mut clone_conn = clone_client.get_connection()?;
    let mut m = 10;
    while m > 0 {
        m -= 1;
        cmd("PUBLISH").arg("foo").arg(m).query::<i32>(&mut clone_conn)?;
    }
    cmd("PUBLISH").arg("bar").arg(0).query::<i32>(&mut clone_conn)?;
    thread::sleep(Duration::from_secs(20));
    Ok(())
}
```

Messages printed

> receive channel foo, message 9
> receive channel foo, message 8
> receive channel foo, message 7
> receive channel foo, message 6
> receive channel foo, message 5
> sub bar channel
> receive channel foo, message 3
> receive channel foo, message 2
> receive channel foo, message 1
> receive channel foo, message 0
> receive channel bar, message 0

Message **4** lost.

**Comment by Terkwood** [comment]
Nicely done!  I think a good first step for whoever looks into this PR would be to encapsulate your test case within the existing test suite, so that we can get a convenient green light when we finally figure out how to solve the problem.

**Comment by enzious** [comment]
![image](https://user-images.githubusercontent.com/4645608/117217504-19ed2080-adc7-11eb-87dd-88ca03389789.png)
I think I figured this out, but for async. The subscribe event has a result that's read but the buffer grabs more than what it needs (See first red square).

Then when switching to pubsub, it starts wherever the decoder for Connection stops, thus creating an invalid start point that it can't move forward from (See second red square).

**Comment by enzious** [comment]
So that "fixes" going from `PubSub` to the `on_message` Streams, but if you drop the `impl Stream`... how do you get the leftover buffer from the `Framed<...>` stream so that it can be returned to the `Connection<..>`?

**Comment by enzious** [comment]
It looks like Golang redis doesn't read the response for subscribe/publish:
https://github.com/go-redis/redis/blob/8b2a7107ee84d7fc6d018981fc121eb5ff913d4b/pubsub.go#L126

**Comment by enzious** [comment]
For the sync version, I think it is the case of a pubsub message coming in while the subscribe request is being sent.

< pubsub message comes in
> subscribe request
< subscribe function reads pubsub message instead of subscribe response
[subscribe response is left hanging]

Async experiences two separate issues:
- The same issue as above
- The request response buffer overconsuming

**Comment by nihohit** [comment]
This issue happens in the sync pub/sub, but not the async pub/sub, because the async pub/sub requires a mutable reference both for `on_message` and for `subscribe`, which means that the stream can't receive messages while calling "subscribe".

proposed solution: https://github.com/redis-rs/redis-rs/pull/910

**Comment by enzious** [comment]
> This issue happens in the sync pub/sub, but not the async pub/sub, because the async pub/sub requires a mutable reference both for `on_message` and for `subscribe`, which means that the stream can't receive messages while calling "subscribe".
> 
> proposed solution: #910

If you exit pubsub at the wrong time, you may be trick up the parser by receiving a published message while reading the response of your unsubscribe request.
