### ISSUE TITLE
Plan for Redis 6 supports

### ISSUE THREAD

**Issue by weihanglo** [redis-rs/redis-rs#312]
Redis just released 6.0.0 GA yesterday. There are many interesting features need client-side supports, such as 

- [x] #305 TLS
- [x] #329 RESP3 protocol
- [x] #330 Access Control Lists (ACL)
- [ ] #331 Client-side caching
- [x] #333 STRALGO LCS 

What is the plan and the roadmap to support Redis 6? I would love to do some works.

Edited: This issue would collect update information about Redis 6 major features in its best efforts.

**Comment by seanpianka** [comment]
Does this crate work with 6.0.x, even though there is no client-side support for the listed features?

**Comment by badboy** [comment]
> Does this crate work with 6.0.x, even though there is no client-side support for the listed features? Or do users of this crate have to ensure they're using 5.x?

No, the old protocol still works and thus you can use this crate against a newer Redis just fine. You won't get support for some newer features and we might lack nice wrappers for newer commands.

> What is the plan and the roadmap to support Redis 6? I would love to do some works.

I personally have no plan to write specific support for Redis 6 features, both because I have no requirement for it and also not enough time for redis-rs.
If someone wants to work on this it's appreciated (I can't guarantee quick review though, but maybe it's then time to expand maintainership of redis-rs)

**Comment by Terkwood** [comment]
I plan to open individual tickets to track the issues mentioned that aren't TLS (that one looks close to merge). Please let me know if you have any objections to that. It will help break down the effort into smaller chunks of work.

**Comment by Terkwood** [comment]
Please see #329, #330, and #331:  stubbed issues raised as sub-tasks for this overall effort.  We welcome comments on the design and implementation detail that will help advance those individual tasks.

**Comment by Terkwood** [comment]
And with #333 (STRALGO LCS), we should have tickets representing all the new features in Redis 6.

**Comment by Terkwood** [comment]
We found in #345 that the CI environment is running Redis 5.  This causes tests that use new features from Redis 6 to fail when run by Travis. 

For now I would recommend that we make all new commands specific to Redis 6 _opt-in_, and _not_ part of the default feature set.  This will let us continue to make quick progress on developing the new features.  We could then explore the feasibility of upgrading the CI environment from Redis 5 to Redis 6, separately. 

This is a bit of an ugly compromise!  But solving CI issues isn't something that we can expect any individual contributor to be very excited about, so I think this is the best way to maintain our forward momentum on Redis 6 feature development.

**Comment by Terkwood** [comment]
Related: Travis doesn't show any useful options for redis server config, at first blush.

https://docs.travis-ci.com/user/database-setup/#redis

👷

**Comment by Terkwood** [comment]
Raised #347 to troubleshoot the fact that we're running Redis 5 in the Travis CI environment and seeing failures on Redis-6-dependent features.  

@weihanglo, if you get a chance to add this to your punch list of things we need for Redis 6, in the issue description, that will be super awesome.  Thank you.  :sun_behind_small_cloud:

**Comment by gferon** [comment]
@Terkwood while skimming through the documentation of Redis 6.0, I realized it supports client authentication. I plan on adding support for this in a separate PR. It should be as easy as finding a good way to propagate the client certificate and set the [identity](https://docs.rs/native-tls/0.2.4/native_tls/struct.TlsConnectorBuilder.html#method.identity) method on the `TlsConnector`.

**Comment by Terkwood** [comment]
Great!

**Comment by onelson** [comment]
I started to plug away at some sorted set commands added in v6.2, but got stuck trying to reconcile the windows CI (which I didn't see a clear way to get a recent redis running on) and the breaking changes to ACL. #474 was to be the first of several command additions, but my path forward was unclear :cry:

**Comment by nihohit** [comment]
only one task left, no need for this tracking issue. closing.
