### ISSUE TITLE
Support flushall command?

### ISSUE THREAD

**Issue by EmreAtes** [redis-rs/redis-rs#315]
Is the flushall command supported? I couldn't find it in the docs.

If it is not, are there plans to support the flushall command? It seems straightforward, so I can try to send a pull request for it as well.

**Comment by EmreAtes** [comment]
Oh I forgot about `redis::cmd("FLUSHALL").query<()>(con)`. I'll just use that. You can close the issue.

**Comment by badboy** [comment]
If a nice wrapper around it is missing we'd be happy to receive a PR for it.

**Comment by EmreAtes** [comment]
Okay. I checked `src/commands.rs` and it looks like they are arranged by category. I'll add a "Database commands" category, and it looks like the commands `flushall`, `flushdb`, `dbsize`, `save`, `shutdown` look like they would be easy to implement and add under this category.

I'll get back to it within this month.

**Comment by nihohit** [comment]
Closing, since as @EmreAtes the command is supported.
