### ISSUE TITLE
AIO is_open

### ISSUE THREAD

**Issue by Luminoth** [redis-rs/redis-rs#316]
I'm not sure if it's intentional or not, but it looks like redis::aio::ConnectionLike is missing the is_open method that redis::ConnectionLike has. Is there something else that can be used to check that or is it not actually necessary for async connections?

**Comment by badboy** [comment]
That might just be an oversight, it might also be a tiny bit more complicated to implement (though I haven't checked, I could be wrong)

**Comment by Marwes** [comment]
The real question is why do you want to check if the connection is open?

The only real way to check if a connection still accepts requests is to just do the request and see if it succeeds (this is indeed how `is_open` is computed it just indicates if the connection was open on the last request, `fn was_open_on_last_request` may be more accurate).

**Comment by Luminoth** [comment]
Oh interesting, I actually didn't realize that was what it was doing. I've basically been doing something like this with the sync connection:

```
fn redis_method() {
    ensure_redis_connect(); // calls is_open() and if it's false, calls connect (which is ok to fail itself)
    do_a_redis_thing();  // if this errors, that's ok, next time we come through, we'll shore up the connection
}
```

I can add tracking for that myself, it's just been convenient to have that is_open() method.

**Comment by Marwes** [comment]
The better way is to just call `do_a_redis_thing` without checking if it is connected. You are going to need to handle errors in `do_a_redis_connection` anyway so doing any verification beforehand doesn't remove any later checks (this is roughly the same thing as you shouldn't check if a file exists before deleting it, just delete it and handle the `does not exist` error after the fact since you may race with another process deleting the same file).

**Comment by Luminoth** [comment]
In that instance what handles connecting / reconnecting?

**Comment by Marwes** [comment]
When you see an error which would indicate that you need to reconnect (ie, mark the connection as closed if you want a `is_open` method) you can start the reconnect right there.

**Comment by Luminoth** [comment]
Alrighty. I'll probably end up wrapping it in some way so I don't have to update every error handler to also deal with the reconnect tracking. I'll keep an eye out tho in case the is_open() makes its way to the async client.

**Comment by nihohit** [comment]
@Luminoth can this issue be closed?

**Comment by Luminoth** [comment]
Yep, I believe so
