### ISSUE TITLE
ConnectionManager gets stuck on the connection in connect_tcp

### ISSUE THREAD

**Issue by matuzalemsteles** [redis-rs/redis-rs#323]
I have a peculiar and very strange case, I'm using `get_tokio_connection_manager` to have a ConnectionManager instance, apparently it works well locally and inside a dockerfile on a local k8s but when I send it to production on a k8s with cilium, the code is blocked or waiting for the connection on `connect_tcp` using Tokio, I am trying to debug to find out how to reproduce but it is very difficult to know what is happening if nothing is returned.

I thought it was a blocked connection on Redis but other services are able to communicate very well with it, I can't think of what problem it might be. Any ideas or suggestions?

**Comment by Cightline** [comment]
I believe I'm having the same issue and I can't figure out how to resolve it.

**Comment by Cightline** [comment]
Ok I managed to get this to work. It seems like all of the "hangs" were from using a password in the Redis connection string. 

```
let redis_client = redis::Client::open("redis://host.com:15216/").unwrap();

let redis_cm = redis_client.get_tokio_connection_manager().await.unwrap();

println!("Got redis connection manager");

let string_result: String = redis::cmd("AUTH").arg(&[redis_password]).query_async(&mut redis_cm.clone()).await.unwrap();
```

**Comment by nihohit** [comment]
@matuzalemsteles do you have a reproduction to share? if not, I'll close the ticket due to inactivity.
