### ISSUE TITLE
Support RESP3 protocol

### ISSUE THREAD

**Issue by Terkwood** [redis-rs/redis-rs#329]
[Basic usage: try out the HELLO command](https://redis.io/commands/hello).

[Deeper dive: read the RESP3 repository](https://github.com/antirez/resp3).

This issue is a subset of fulfilling overall Redis 6.0 support.  See #312.

This ticket is a stub, for now.  If anyone wants to throw technical specification into the comments, we'll gladly edit the description to include the relevant details.

**Comment by nihohit** [comment]
RESP3 is now mostly supported, the rest of the tasks are tracked in https://github.com/redis-rs/redis-rs/issues/749
