### ISSUE TITLE
Support STRALGO LCS

### ISSUE THREAD

**Issue by Terkwood** [redis-rs/redis-rs#333]
This ticket is a stub for the effort to support the STRALGO LCS (longest common subsequence) command.

You can read more here: https://redis.io/commands/stralgo

We're happy to update this ticket's description with additional design & implementation detail as needed. 

Eventually Redis will have additional string algos supported under STRALGO, but (in an effort to keep work scope small) the goal of this ticket is just to add the LCS command in such a way that it leaves the option for additional algorithms to be added later.

See also: #312

**Comment by nihohit** [comment]
STRALGO was deprecated. If there's interest, PRs for LCS are welcome.
