### ISSUE TITLE
Example/feature request: async transactions

### ISSUE THREAD

**Issue by davechallis** [redis-rs/redis-rs#353]
I've been struggling to get transactions working with async, so an example or some docs on that would be super helpful.

E.g. an async version of: 

```
use redis::Commands;
let key = "the_key";
let (new_val,) : (isize,) = redis::transaction(&mut con, &[key], |con, pipe| {
    let old_val : isize = con.get(key)?;
    pipe
        .set(key, old_val + 1).ignore()
        .get(key).query(con)
})?;
println!("The incremented number is: {}", new_val);
```

Though I don't know if that's currently possible, or whether it needs a new `transaction_async` or similar function adding.

**Comment by davechallis** [comment]
In case it helps anyone, I did this using a macro in the end, any improvements or alternative suggestions welcome though.

It requires the caller to create their own `pipe().atomic()`, but is otherwise similar to the current `transaction` function (it takes a block to execute as the 3rd argument instead of a function though).

```rust
macro_rules! async_transaction {
    ($conn:expr, $keys:expr, $body:expr) => {
        loop {
            cmd("WATCH").arg($keys).query_async($conn).await?;

            if let Some(response) = $body {
                cmd("UNWATCH").query_async($conn).await?;
                break response;
            }
        }
    };
}
```

Full example of usage:

```rust
use redis::{pipe, cmd, AsyncCommands, RedisResult};

macro_rules! async_transaction {
    ($conn:expr, $keys:expr, $body:expr) => {
        loop {
            cmd("WATCH").arg($keys).query_async($conn).await?;

            if let Some(response) = $body {
                cmd("UNWATCH").query_async($conn).await?;
                break response;
            }
        }
    };
}

#[tokio::main]
async fn main() -> RedisResult<()> {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let mut async_conn = client.get_async_connection().await?;

    let key = "the_key";

    let (new_val,): (isize,) = async_transaction!(&mut async_conn, &[key], {
        let old_val: isize = async_conn.get(key).await?;
        pipe().atomic()
            .set(key, old_val + 1).ignore()
            .get(key)
            .query_async(&mut async_conn)
            .await?
    });
    println!("The incremented number is: {}", new_val);

    Ok(())
}
```

**Comment by lroux-at-jellysmack** [comment]
Hello @mitsuhiko, are you open for a PR to implement a `redis::aio::transaction` async function with the same prototype as `redis::transaction` ?
I think I can do this today if you're okay !

**Comment by vifino** [comment]
I stumbled into this today and would love to have async transaction support in the redis crate.
I'll try the macro.
Thank you, @davechallis!

**Comment by tasn** [comment]
@lroux-at-jellysmack, can you please share that code? 🙏🏻

**Comment by Walther** [comment]
Friendly bump - any updates on this? Being able to use transactions even in an `async` context would be sweet, including with the `ConnectionManager` (cc https://github.com/redis-rs/redis-rs/issues/598 )

**Comment by lroux-at-jellysmack** [comment]
> @lroux-at-jellysmack, can you please share that code? 🙏🏻

Hello @tasn, sorry I think I ended up failing and giving up unfortunately :/

**Comment by tasn** [comment]
Thanks @lroux-at-jellysmack. Tbh, we gave up on transactions anyway as we are using redis-cluster nowadays which doesn't support them it seems (or at least in this lib).

**Comment by johalun** [comment]
+1 for this, just what I need! I'll try the macro for now. Thanks a bunch for sharing that.

**Comment by threema-danilo** [comment]
Note: If you're using a multiplexed connection (`ConnectionManager`) from multiple async tasks with CAS transactions, from what I understand, this is currently unsound (because multiple `WATCH` calls from multiple tasks can interleave, and transactions could cancel each other). Since transaction state in Redis is connection-scoped, my current workaround is opening a separate connection for each transaction. See #565 for more details.

**Comment by nihohit** [comment]
Transactions can be used using `pipeline` objects.
