### ISSUE TITLE
blpop/brpop methods block async code

### ISSUE THREAD

**Issue by nsavch** [redis-rs/redis-rs#361]
Hi,

Considering code like this

```
use async_std::prelude::*;
use redis::AsyncCommands;

async fn run_blop(name: &str, mut conn: redis::aio::MultiplexedConnection) {
    println!(
        "Entering future {} at {:?}",
        name,
        std::time::Instant::now()
    );
    let _res: Option<()> = conn.blpop(name, 10).await.unwrap();
    println!("exiting future {} at {:?}", name, std::time::Instant::now());
}

#[async_std::main]
async fn main() -> std::io::Result<()> {
    let client = redis::Client::open("redis://127.0.0.1").unwrap();
    let conn = client.get_multiplexed_async_std_connection().await.unwrap();
    run_blop("first", conn.clone())
        .join(run_blop("second", conn.clone()))
        .await;
    Ok(())
}
```
You would expect that both `first` and `second` future will be completed at the same time, yet one future is completed exactly 10 seconds after another one, which means that blpop command blocks the thread, which doesn't make much sense - it's typical wait for IO event so it should never block.

**Comment by weihanglo** [comment]
Hmm.... It seems to be the desired behavior as described [in the official BLPOP documentation](http://redisio/commands/blpop).

> [BLPOP](https://redis.io/commands/blpop) is a blocking list pop primitive. It is the blocking version of [LPOP](https://redis.io/commands/lpop) because it blocks the connection when there are no elements to pop from any of the given lists.

Though `redis::aio::MultiplexedConnection` can send commands concurrently, underneath the hood it reuse one shared connection which I think would be blocked when sending `BLPOP` `BRPOP`.

**Comment by mlcruz** [comment]
I'm not sure if blocking on async is the correct/idiomatic choice here. Possibly blocking the executor thread when calling an async method is a huge footgun and is not the expected behavior, resulting in some very easy to miss bugs (Ex: hanging due to blocking the entire thread after a server dc in the middle of a blpop)

Maybe it would be better to just not provide an async b[l/r]pop for aio clients instead.

**Comment by Marwes** [comment]
It is not blocking the executor though, it is just the current future that is "blocked" (stuck in a pending state). As the multiplexed connection runs multiple commands on the same connection this has the consequence of blocking other, concurrent commands as well which can be a footgun, but the basic async connection which only runs one command at a time does not have this problem so it is not an async specific issue.

**Comment by mlcruz** [comment]
> It is not blocking the executor though, it is just the current future that is "blocked" (stuck in a pending state). As the multiplexed connection runs multiple commands on the same connection this has the consequence of blocking other, concurrent commands as well which can be a footgun.

I see, this makes perfect sense. 

Thanks for taking your time to explain it to me!
