### ISSUE TITLE
Box unnecessary?

### ISSUE THREAD

**Issue by Lucretiel** [redis-rs/redis-rs#369]
https://github.com/mitsuhiko/redis-rs/blob/739692f3d5cd0910342188911d07cf20064f1ae6/src/connection.rs#L95

Is there any reason for this to be boxed? It's technically a breaking change to unbox it, but there's not really any reason for it to be boxed (other than a size reduction from 64 to 40 bytes (but if that's the motivation, why not wrap the entire thing in a `Box`? Why just the one field?))

**Comment by nihohit** [comment]
the field is no longer boxed.
