### ISSUE TITLE
Support TCP keepalive?

### ISSUE THREAD

**Issue by atuk721** [redis-rs/redis-rs#374]
This module seems not to implement TCP keepalive.
Now, especially using subscribe, this cannot recognize TCP half connection when Redis server has gone.

I think this will be able to support by using TCP keepalive.

**Comment by abonander** [comment]
This is especially annoying when using Azure Cache for Redis as it has a 10 minute idle timeout that cannot be changed: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection#idle-timeout

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/886
