### ISSUE TITLE
Why is the r2d2 module not public? 

### ISSUE THREAD

**Issue by ibraheemdev** [redis-rs/redis-rs#385]
Why is the [`rd2d` module](https://github.com/mitsuhiko/redis-rs/blob/master/src/r2d2.rs) not public? This means enabling the `rd2d` features provides no functionality, and the [`r2d2-redis`](https://github.com/sorccu/r2d2-redis) crate is essentially a copy of [`rd2d.rs`](https://github.com/mitsuhiko/redis-rs/blob/master/src/r2d2.rs). How are pooled connections supposed to be managed? I can't find any documentation regarding this...

**Comment by ibraheemdev** [comment]
Oh, I got it now. I'll try to add an example and docs for r2d2 pooling

**Comment by invis87** [comment]
Hi, @ibraheemdev , I am new to redis and writing some "cache-service" on top of it. I don't want to open new connection for every request, so connection pool is what I am looking for. Could you tell how to create it here? 
Also why not to use r2d2-redis?

**Comment by ibraheemdev** [comment]
The functionality provided by `rd2d-redis` is built in to the `redis` crate through the `r2d2` module. Here is a simple example of a pooled connection:

```rust
use redis::Commands;

fn main() {
    // get redis client
    let client: redis::Client = redis::Client::open("redis://127.0.0.1/").unwrap();

    // create r2d2 pool
    let pool: r2d2::Pool<redis::Client> = r2d2::Pool::builder().build(client).unwrap();

    // get a connection from the pool
    let mut conn: r2d2::PooledConnection<redis::Client> = pool.get().unwrap();

    // use the connection as usual
    let _: () = conn.set("KEY", "VALUE").unwrap();
    let val: String = conn.get("KEY").unwrap();
    println!("{}", val)
}
```

**Comment by invis87** [comment]
Thanks much!

Looks like README should be fixed, cause now there is:
`To open a connection you need to create a client and then to fetch a connection from it. In the future there will be a connection pool for those, currently each connection is separate and not pooled.`
