### ISSUE TITLE
Defaults when handling Nil responses is a little tedious. 

### ISSUE THREAD

**Issue by wellinthatcase** [redis-rs/redis-rs#389]
I'm not entirely sure how to go about this, but this would be much easier if Nil responses were wrapped in an `Err` rather than `Ok`. 

Nil responses aren't successful responses. They're failures. These failures cannot be perceived as actual errors. This leads to incompatibility with every unwrap option we have. Including, but not limited to `unwrap_or_default`, and `unwrap_or_else`. 

If anyone has a workaround solution to effectively and efficiently handle Nil responses, please let me know. I'm quite stuck on figuring one out.

EDIT: In retrospect, this would confuse "no results" with "definite error". I'm still quite clueless on how to handle it, though.

**Comment by seanpianka** [comment]
The following code calls `redis::Connection::get` to retrieve the value for a key, but it panics with a `redis::ErrorKind::TypeError` and a message about the response being `nil`: 

`Response was of incompatible type: "Response type not btreeset compatible" (response was nil)`

Here's the relevant code:
```rust
fn get(key: String) -> Result<BTreeSet<String>, StoreReadError> {
    let client = match redis::Client::open("redis_url_here...") {
        Ok(rc) => rc,
        Err(e) => panic!(format!("failed to connect to redis: {:?}", e)),
    };
    let mut conn: redis::Connection = match client.get_connection() {
        Ok(conn) => conn,
        Err(e) => return Err(StoreReadError::FailedToRead { cause: e.to_string() }),
    };
    match conn.get::<String, BTreeSet<String>>(key) {
        Ok(ov) => Ok(ov),
        // If there is no previous BTreeSet inserted for this key, it returns an
        // error about the value being `nil`
        Err(e) => panic!("{}", e),
    }
}
```
Should I be manually checking for `e.kind()` to be `TypeError` and if so, returning a default value? 🤔 

Here's my workaround:

```rust
fn get(key: String) -> Result<BTreeSet<String>, StoreReadError> {
    let client = match redis::Client::open("redis_url_here...") {
        Ok(rc) => rc,
        Err(e) => panic!(format!("failed to connect to redis: {:?}", e)),
    };
    let mut conn: redis::Connection = match client.get_connection() {
        Ok(conn) => conn,
        Err(e) => return Err(StoreReadError::FailedToRead { cause: e.to_string() }),
    };
    match conn.get::<String, BTreeSet<String>>(key) {
        Ok(ov) => Ok(ov),
        Err(e) => match e.kind() {
            ErrorKind::TypeError => Ok(BTreeSet::new()),
            _ => {
                println!("{:?}", e.kind());
                Err(StoreReadError::FailedToRead { cause: e.to_string() })
            }
        },
    }
}
```

**Comment by nihohit** [comment]
Closing. 
1. As mentioned, "no response" isn't an error.
2. This would be a massively breaking change.
