### ISSUE TITLE
Failure on aio::ConnectionManager using async_std

### ISSUE THREAD

**Issue by DavidBM** [redis-rs/redis-rs#401]
Hi! 

I see that the version 0.17.0, in the line https://github.com/mitsuhiko/redis-rs/blob/7dab213218c543d31dd5bb6b3fea2344249e6fad/src/aio.rs#L1058 is not under a `#[cfg(feature = "tokio-comp")]` flag, so it always tries to use tokio even when it isn't on there. 

This causes problems on redis 0.17.0 when calling the method `ConnectionManager::new`. I think adding some login in order to check what executor was used (not only using the cfg flags) would make it work. 

I see that Master diverges a lot from the 0.17.0 and it may be already fixed, but I think a patch release would be good in order to fix ManagedConnections under async_std.

I hope it helps!

**Comment by Marwes** [comment]
This should be fixed on master at least, not sure how to do about a patch release (though I don't have release access yet anyway).

**Comment by DavidBM** [comment]
Maybe just waiting for the next version would be best. Do you know if master is ready to release under 0.18 or if we will need to wait?

**Comment by nihohit** [comment]
bug was fixed.
