### ISSUE TITLE
Recommend pattern for implementing retry logic?

### ISSUE THREAD

**Issue by curiousdev** [redis-rs/redis-rs#402]
Given usage like below:

```rust
    let key = "myKey";
    let result: RedisResult<Option<i32>> = cmd("GET").arg(key).query_async(&mut conn).await;
```

What's the recommended pattern and ErrorKind where we can retry?
https://github.com/mitsuhiko/redis-rs/blob/f60933a467013de40bdf4a40288b551e09857160/src/types.rs#L42

**Comment by nihohit** [comment]
As an unofficial guide, you can look at 
https://github.com/redis-rs/redis-rs/blob/cbe47c67247725c2b6baa73ecb51ac32917521d6/redis/src/types.rs#L628

**Comment by nihohit** [comment]
clsoing due to inactivity.
