### ISSUE TITLE
Pubsub async stream blocked on next() when output buffer limit is reach

### ISSUE THREAD

**Issue by hyche** [redis-rs/redis-rs#414]
The sample code is simple:

```
let client = redis::Client::open(uri).unwrap();                                      
let mut con = client.get_async_connection().await?.into_pubsub();
con.subscribe(channel).await?;
let mut stream = con.on_message();
while let Some(msg) = stream.next().await { // loop hangs forever because stream not producing any values
// do something with msg
}
```

In case of closing connection manually using `redis-cli client kill`, the loop will break, but it doesn't break if redis closes connection due to overcoming of output buffer limits. I expect the behaviors are same for both cases. Further investigation, I put a `println(&msg)` on https://github.com/mitsuhiko/redis-rs/blob/master/src/aio.rs#L180, and it prints out lots of `Err(bytes remaining on stream)`, which causes the loop hangs forever.

Is there current any workaround for this, or how can I handle the error ?

**Comment by hyche** [comment]
Is there any update on this issue ?

**Comment by Marwes** [comment]
No update, but it seems like the stream could return a `Result` instead. Potentlially also detect when an error indicates end-of-stream and stop at that point.

I noticed that the `Decoder` doesn't handle `decode_eof` as well as it could in #472, but unfortunately that does not fix your problem. We'd be happy to take a PR for adding/changing `on_stream*` such that it handles errors better.

**Comment by nihohit** [comment]
@hyche do you still see this happening?
Can you provide a test case?

**Comment by nihohit** [comment]
clsoing due to inactivity.
