### ISSUE TITLE
is there support for async commands under cluster connection? 

### ISSUE THREAD

**Issue by NikosEfthias** [redis-rs/redis-rs#421]

**Comment by Marwes** [comment]
There is https://github.com/Marwes/redis-cluster-async, haven't gotten around to merging it back here but it probably should be at some point.

**Comment by NikosEfthias** [comment]
I am using that at the moment but redis.rs itself doesnt support async cluster is that right ?

**Comment by Marwes** [comment]
Nope, it doesn't

**Comment by rogeriob2br** [comment]
Inspired by r2d2-cluster-redis (sync) and redis-cluster-async (without pool), I created mobc-redis-cluster based on mobc-redis. https://github.com/rogeriob2br/mobc-redis-cluster.

**Comment by BratSinot** [comment]
> There is https://github.com/Marwes/redis-cluster-async, haven't gotten around to merging it back here but it probably should be at some point.

But this doesn't support tls...

**Comment by Alkeryn** [comment]
sorry for the necrobump but any news on this ? :)

**Comment by ChosunOne** [comment]
Any updates here?

**Comment by tasn** [comment]
We (at https://github.com/svix/svix-webhooks) are trying to use https://github.com/Marwes/redis-cluster-async (thanks @Marwes!) but it doesn't work as nicely as just having it in the library directly. There are a few issues by not having it implement the same traits that make using both interchangeably (that is, different backends) a pain. :(

How hard would it be to add it directly to redis-rs? Maybe it's something we can help with?

**Comment by namkai** [comment]
Happy to help as well!

**Comment by Marwes** [comment]
I'd expect it to be pretty easy to merge back here. Merging the sync and async code (as much as possible) ma be a bit harder but isn't strictly necessary. I can't promise that I am able to review it though as I am not very active here anymore.

**Comment by tasn** [comment]
@Marwes, who would be the most active maintainer other than you then (to help get this in)? Because looking at the commit history it's all you. :)

**Comment by Marwes** [comment]
There isn't anyone else unfortunately cc https://github.com/mitsuhiko/redis-rs/issues/602

**Comment by tasn** [comment]
@mitsuhiko, do you reckon anyone at Sentry would be up for the task?

**Comment by mitsuhiko** [comment]
Nope. Not likely. Would need outside contributions.

**Comment by utkarshgupta137** [comment]
@djc @jaymell Is work active on getting async cluster support merged in? If not, I can take a crack at it.
Also, please reopen the issue.

**Comment by djc** [comment]
I'm not aware of anyone currently working on this.

**Comment by utkarshgupta137** [comment]
I will begin working on it in that case.

Also, I've gone through the most popular redis crates and the only 2 crates have async cluster support:
- https://github.com/redis-rs/redis-cluster-async
- https://github.com/aembke/fred.rs

Am I missing any other crate?

**Comment by Dessix** [comment]
It’s worth noting that Fred’s cluster support does not function under TLS, as it reevaluates the same certificates with the destination IP as the hostname, causing failures even if that IP could be a resolution of the DNS name originally used to reach the cluster.

I have been unable to work around this in a way that checks only the cluster host SNI, while requiring the cert to be used by but not compliant with the other hosts in the cluster, but that seems like a viable workaround with minimal architectural differences that doesn’t sacrifice the security provided by SNI.
