### ISSUE TITLE
HashMap doesn't implement ToRedisArgs

### ISSUE THREAD

**Issue by vaffeine** [redis-rs/redis-rs#444]
Hi,

Thanks for this awesome library.

The only problem I have with it currently is that it doesn't implement `ToRedisArgs` for `std::collections::HashMap`. Is there any reason it can't be implemented the same way it is done for `BTreeMap`? The code below seems to work:
```
impl<T: ToRedisArgs + Hash + Eq + Ord, V: ToRedisArgs> ToRedisArgs
    for HashMap<T, V>
{
    fn write_redis_args<W>(&self, out: &mut W)
    where
        W: ?Sized + RedisWrite,
    {
        for (key, value) in self.iter() {
            // otherwise things like HMSET will simply NOT work
            assert!(key.is_single_arg() && value.is_single_arg());

            key.write_redis_args(out);
            value.write_redis_args(out);
        }
    }

    fn is_single_arg(&self) -> bool {
        self.len() <= 1
    }
}
```

**Comment by gibranamparan** [comment]
Any answer to this question?

**Comment by ajawalker** [comment]
I'd also love to see an implementation for HashMap, unless there's some technical reason why (in which case I'd be curious to know why).

**Comment by djc** [comment]
(There's now a PR for this, see #722.)
