### ISSUE TITLE
Support MINID stream length-capping strategy released in Redis 6.2

### ISSUE THREAD

**Issue by scooter-dangle** [redis-rs/redis-rs#458]
With the release of Redis 6.2, `MINID` is now available for [`XTRIM`](https://redis.io/commands/xtrim) and [`XADD`](https://redis.io/commands/xadd).

I started to look at what it would take to add support, and it feels like it would require some backward-incompatible interface changes. The current `MAXLEN` enum is called [`StreamMaxlen`](https://docs.rs/redis/0.20.0/redis/streams/enum.StreamMaxlen.html), which would need to be renamed. (I'm dubious of adding a separate enum, since I think it would over-complicate the command interface.)

I propose modifying that enum like this:
```rust
/// Utility enum for passing `MAXLEN|MINID [= or ~] threshold|id`
/// arguments into `StreamCommands` for XADD and XTRIM.
/// The enum value represents the count.
#[derive(PartialEq, Eq, Clone, Debug)]
pub enum StreamSizeLimit {
    /// Match an exact count
    MaxlenEquals(usize),
    /// Match an approximate count
    MaxlenApprox(usize),
    /// All entries before an ID
    MinidEquals(String),
    /// All entries before a point _somewhere_ before an ID
    MinidApprox(String),
}
```
I would also move `xadd_maxlen` and `xadd_maxlen_map` to `xadd_size_limited` and `xadd_size_limited_map`. (Technically would _add_ the latter 2 and mark the former 2 as deprecated.)

#### Naming

Any thoughts on names of the enum, its variants, or the `xadd_*` functions?

#### Graceful deprecation

Do we want to provide some assistance in helping users discover the change? I think it's likely that most usages of `StreamMaxlen` are in strict creation of the variants—not in matching on them. In that case, temporarily retaining the current variants and providing a type alias should point people in the right direction with warnings prior to making it a breaking change.

```rust
/// Utility enum for passing `MAXLEN|MINID [= or ~] threshold|id`
/// arguments into `StreamCommands` for XADD and XTRIM.
/// The enum value represents the count.
#[derive(PartialEq, Eq, Clone, Debug)]
pub enum StreamSizeLimit {
    #[deprecated(
        since = "0.21.0",
        note = "Use StreamSizeLimit::MaxlenEquals instead. Changed to match increase in API surface in Redis 6.2"
    )]
    /// Match an exact count
    Equals(usize),
    #[deprecated(
        since = "0.21.0",
        note = "Use StreamSizeLimit::MaxlenApprox instead. Changed to match increase in API surface in Redis 6.2"
    )]
    /// Match an approximate count
    Approx(usize),
    /// Match an exact count
    MaxlenEquals(usize),
    /// Match an approximate count
    MaxlenApprox(usize),
    /// All entries before an ID
    MinidEquals(String),
    /// All entries before a point _somewhere_ before an ID
    MinidApprox(String),
}

#[deprecated(
    since = "0.21.0",
    note = "Use StreamSizeLimit instead. Changed to match increase in API surface in Redis 6.2"
)]
/// TODO
pub type StreamMaxlen = StreamSizeLimit;
```

#### ID as `String` or `(u64, u64)` or `(u64, Option<u64>)`

The addition of `String`-holding variants forces the enum to no longer derive `Copy`. Given how recent `MINID` is, I don't know if there will yet be data on how often it's used with IDs constructed from scratch from timestamps vs IDs returned as strings from previous `XREAD` calls. My instinct would be to stick with `String` for now and modify the variants (or add additional variants) in the future if they seem useful.

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1361
