### ISSUE TITLE
Is it's possible to use this crate for listen redis to server-push events 

### ISSUE THREAD

**Issue by eyalsatori** [redis-rs/redis-rs#466]
Hi , 

I want to implement a client cash in my app - and use the `CLIENT TRACKING ` command for receive events about record invalidation (following this [article](https://redis.io/topics/client-side-caching)) . 

I was thinking about opening TOKIO task , the awaiting on the connection that should receive the event from the server , but I can't understand from the doc if currently it's supported by the lib. 
 
So i will be happy for any help with that ..

**Comment by nihohit** [comment]
client-side caching currently isn't supported, but there's ongoing work on adding RESP3 support, after which I hope to add client side caching, too.

**Comment by nihohit** [comment]
duplicate of.
