### ISSUE TITLE
Request: FromRedisValue for fixed arrays

### ISSUE THREAD

**Issue by kamulos** [redis-rs/redis-rs#468]
I might be wrong, but I was thinking with const-generics coming in a few days to 1.51.0: would it be possible to implement `FromRedisValue` for generic array sizes? So if I already know what size the answer will be, I can just put it into an stack array and process it from there.

**Comment by Marwes** [comment]
Yes, that would work. Today it is implemented up to size 32 arrays however which is likely more than enough for most uses. Since the feature is so recent I think it makes sense to wait a bit before requiring a rustc update though.

**Comment by kamulos** [comment]
For the time being, size 32 arrays would be enough for me. How would I use that? I tried this:

```
let val: [u8; 16] = con.hget("some:key", "val")?;
```
which rustc comments with:

```
the trait `FromRedisValue` is not implemented for `[u8; 16]`
```

**Comment by ThomAub** [comment]
I was also looking for something similar but I think currently there is no support for fixed size array. 
I found in the [doc  of the trait](https://docs.rs/redis/0.20.0/redis/trait.FromRedisValue.html) the implementation for `Vec<T>` [here](https://docs.rs/redis/0.20.0/src/redis/types.rs.html#1092) 

If this is something of interest I could try to make a PR for it ? With first a macro to implement it for size up to 32 and find a way to make it const generic afterwards ?

**Comment by kamulos** [comment]
Looking at that code it seems to me that the data is in a `Vec` anyways. So it might be more inefficient to copy it to a static array. But on the other hand I need it in a static array in my program most of the time. So doing that manually  every time seems like unnecessary effort. I'd be really interested in a trait implementation.

**Comment by nihohit** [comment]
solved in https://github.com/redis-rs/redis-rs/pull/981
