### ISSUE TITLE
Support ipv6 link-local addresses

### ISSUE THREAD

**Issue by socs** [redis-rs/redis-rs#470]
URL parsing fails on ipv6 link-local addresses, eg

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let _ = redis::Client::open("[fe80::1%foo]:6379")?; // -> Error: Redis URL did not parse
    Ok(())
}
```

This works with redis-cli
```
# redis-cli -h fe80::1%foo -p 6379
[fe80::1%foo]:6379> ping
PONG
```

The limitation stems from rust-url library which follows a url spec that [omits zone identifier](https://url.spec.whatwg.org/#host-representation) on ipv6 ll addresses.
Perhaps a custom parser could be used by redis-rs, such as the one in redis-cli, so that ipv6 ll addresses is accepted.

**Comment by djc** [comment]
Should be fixed with https://github.com/redis-rs/redis-rs/pull/679.
