### ISSUE TITLE
Async-std support for `ConnectionManager`

### ISSUE THREAD

**Issue by kotx** [redis-rs/redis-rs#477]
In `ConnectionManager::new(...)`:
> This requires the connection-manager feature, which will also pull in the Tokio executor.

I would like the avoid having two runtimes (`async-std` and `tokio`), so it would be nice if `ConnectionManager` worked with async-std. Would this be possible/practical?

**Comment by nihohit** [comment]
It is. `get_tokio_connection_manager` is supported also on async-std, and should be renamed.

https://github.com/redis-rs/redis-rs/pull/913
