### ISSUE TITLE
Async pubsub hang

### ISSUE THREAD

**Issue by kowu-zf** [redis-rs/redis-rs#487]
Using an async subscriber can lead to an infinite loop, if a pubsub message is received before the subscribe/unsubscribe response.
Luckily is already being addressed by https://github.com/mitsuhiko/redis-rs/pull/486

reproducer attached nevertheless, run ./bug stress and ./bug hang in parallel, hang might hang.
```rust
use anyhow::Result;
use redis::Commands;
use tokio_stream::StreamExt;

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    let arg = std::env::args().nth(1);

    match arg.as_deref() {
        Some("hang") => hang().await,
        Some("stress") => stress(),
        _ => panic!("usage: ./bug [hang|stress]"),
    }
}

async fn hang() -> Result<()> {
    let conn = redis::Client::open("redis://127.0.0.1")?
        .get_async_connection()
        .await?;
    let mut pubsub = conn.into_pubsub();

    pubsub.subscribe("foo").await?;
    pubsub.subscribe("fooo").await?;

    let mut onmsg = pubsub.into_on_message();

    println!("{:?}", onmsg.next().await);

    Ok(())
}

fn stress() -> Result<()> {
    let mut conn = redis::Client::open("redis://127.0.0.1")?.get_connection()?;

    loop {
        conn.publish("foo", "bar")?;
    }
}
```

**Comment by kowu-zf** [comment]
This Issue still occurrs in the 0.20.2 release.

**Comment by Marwes** [comment]
Yes, because https://github.com/mitsuhiko/redis-rs/pull/486 is not merged as it lacks a test and needs to be rebased

**Comment by nihohit** [comment]
If you're using Redis/Valkey v6 or newer, you can use the RESP3 pubsub in order to use a regular connection with pubsub - https://docs.rs/redis/latest/redis/#resp3-async-pubsub
If not, I hope that in the next version the async pubsub connection could be split, which will allow this behavior.
https://github.com/redis-rs/redis-rs/pull/1144

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1144
