### ISSUE TITLE
Missing flush commands

### ISSUE THREAD

**Issue by ManevilleF** [redis-rs/redis-rs#497]
Hello,

I'm using an async connection (`redis::aio::Connection`) and for testing purposes I want to  execute`FLUSHALL` before my tests.

But I can't find any `AsyncCommand` to do this and `redis::cmd("FLUSHALL")` does nothing.

**Comment by ManevilleF** [comment]
Ok I managed to use the `FLUSHALL` command using:

`redis::cmd("FLUSHALL").query_async(&mut connection).await.unwrap();`

But I wonder if this should be a built in command

**Comment by TilBlechschmidt** [comment]
Counter-argument: `FLUSHALL` is one of, if not **the** most dangerous command one could use on an instance. Maybe it is a good thing that it isn't directly accessible 😉 

(Albeit I'm not sure for myself if it is a valid one, worth a thought though)

**Comment by kardasis** [comment]
I was hoping to use FLUSHDB to clean up after integration tests.  If this is still on the table, I could take a stab at it.

**Comment by djc** [comment]
Yeah, PRs welcome.
