### ISSUE TITLE
No way to send subscribe/unsubscribe cmd after calling `pubsub.on_message()`

### ISSUE THREAD

**Issue by shekohex** [redis-rs/redis-rs#509]
Hi 👋🏼 
As of now, there is no way, in async `PubSub` to call `subscribe` or any other function actually, after calling the `on_message` function.

As per Redis docs [here](https://redis.io/commands/subscribe), a pubsub connection can actually send other commands while in the pubsub state:

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING, RESET and QUIT commands.

But in our case, or should I say my current use case, I need to send more `SUBSCRIBE` or `UNSUBSCRIBE` commands **while at the same time holding the Stream of messages from calling the `on_message` function** but that is not possible.

Here is my current example:

```rust
//! A SharePubSub, v1
//!
//! In this example, I'm trying to implement a Shared version of `PubSub` where we can
//! use only one Redis PubSub connection that would be shared between all of our connected clients.
//! 
//! This could be possible if we ran the receiving message stream on a background task
//! and at the same time, we could use mpsc/boradcast channels to control the background task.
//! 
//! **Note** imports are omitted from this code to make it simple to read
//! for the full file go here: https://gist.github.com/shekohex/b5def27bddb934b40e731292edcca8f7

/// A Command used internally to control the inner pubsub connection
/// from the background task.
enum Cmd {
    Subscribe(String),
    Unsubscribe(String),
    Disconnect,
}

#[derive(Clone)]
pub struct SharedPubSub {
    controller_tx: Sender<Cmd>,
    msg_tx: BroadcastSender<Arc<Msg>>,
}

impl SharedPubSub {
    pub fn new(mut inner: PubSub) -> Self {
        let (controller_tx, controller_rx) = mpsc::channel(50);
        let (msg_tx, _) = broadcast::channel(100);
        let msg_sender = msg_tx.clone();
        let background_task = async move {
            tracing::debug!("background task started ..");
            // convert normal Receiver to ReciverSrream.
            let cmd_stream = ReceiverStream::new(controller_rx);
            // get a message stream.
            let msg_stream = inner.on_message();
            // now, combine both of them in one stream.
            let mut data_stream = futures::stream::select(
                msg_stream.map(Either::Left),
                cmd_stream.map(Either::Right),
            );
            while let Some(data) = data_stream.next().await {
                match data {
                    Either::Left(msg) => {
                        // we got the message from pubsub, broadcast it
                        // to all subscribed Rxs.
                        // ignore the result, we don't really care.
                        let _ = msg_sender.send(Arc::new(msg));
                    }
                    Either::Right(cmd) => {
                        match cmd {
                            Cmd::Subscribe(channel) => {
                                tracing::debug!(
                                    "attempt to subscribe to: {}",
                                    channel
                                );
                                inner.subscribe(&channel).await?;
                                tracing::debug!("subscribed to: {}", channel);
                            }
                            Cmd::Unsubscribe(channel) => {
                                tracing::debug!(
                                    "attempt to unsubscribe from: {}",
                                    channel
                                );
                                inner.unsubscribe(&channel).await?;
                                tracing::debug!(
                                    "unsubscribed from: {}",
                                    channel
                                );
                            }
                            Cmd::Disconnect => {
                                tracing::warn!("Disconnect Cmd Received!");
                                break;
                            }
                        };
                    }
                };
            }
            Result::<_, Error>::Ok(())
        };
        // run the background task.
        tokio::spawn(background_task);
        Self {
            controller_tx,
            msg_tx,
        }
    }

    pub async fn subscribe(
        &self,
        channel: impl Into<String>,
    ) -> Result<BroadcastReceiver<Arc<Msg>>, Error> {
        // issue the Cmd to the background task.
        self.controller_tx
            .send(Cmd::Subscribe(channel.into()))
            .await?;
        // get new message stream from the broadcast channel.
        let rx = self.msg_tx.subscribe();
        Ok(rx)
    }

    pub async fn unsubscribe(
        &self,
        channel: impl Into<String>,
    ) -> Result<(), Error> {
       // tell the background task pubsub we are not interested 
       // anymore on this channel.
        self.controller_tx
            .send(Cmd::Unsubscribe(channel.into()))
            .await?;
        Ok(())
    }
}
```

But here is the issue, this code does not compile, for obvious reasons.
Here is the error:

```rust
error[E0499]: cannot borrow `inner` as mutable more than once at a time
  --> src/shared_pubsub.rs:56:33
   |
38 |             let msg_stream = inner.on_message();
   |                              ----- first mutable borrow occurs here
...
56 |                                 inner.subscribe(&channel).await?;
   |                                 ^^^^^ second mutable borrow occurs here
...
79 |         };
   |         - first borrow might be used here, when `stream` is dropped and runs the destructor for type `futures::stream::Select<futures::stream::Map<impl futures::Stream, fn(Msg) -> Either<Msg, shared_pubsub::Cmd> {Either::<Msg, shared_pubsub::Cmd>::Left}>, futures::stream::Map<ReceiverStream<shared_pubsub::Cmd>, fn(shared_pubsub::Cmd) -> Either<Msg, shared_pubsub::Cmd> {Either::<Msg, shared_pubsub::Cmd>::Right}>>`

error[E0499]: cannot borrow `inner` as mutable more than once at a time
  --> src/shared_pubsub.rs:64:33
   |
38 |             let msg_stream = inner.on_message();
   |                              ----- first mutable borrow occurs here
...
64 |                                 inner.unsubscribe(&channel).await?;
   |                                 ^^^^^ second mutable borrow occurs here
...
79 |         };
   |         - first borrow might be used here, when `stream` is dropped and runs the destructor for type `futures::stream::Select<futures::stream::Map<impl futures::Stream, fn(Msg) -> Either<Msg, shared_pubsub::Cmd> {Either::<Msg, shared_pubsub::Cmd>::Left}>, futures::stream::Map<ReceiverStream<shared_pubsub::Cmd>, fn(shared_pubsub::Cmd) -> Either<Msg, shared_pubsub::Cmd> {Either::<Msg, shared_pubsub::Cmd>::Right}>>`

error: aborting due to 2 previous errors;
```

The main reason here is this 'cannot borrow `inner` as mutable more than once at a time'
which because the `on_message` function requires both `mut` and also a lifetime (any reason?).

Also, Using `Arc<Mutex<PubSub>>` or even `RwLock` not going to work here, since we would have to lock to call `on_message` and the lock would be held for as long as the background task is running, and we can't acquire the lock again to issue another `subscribe` or `unsubscribe` commands to the inner `PubSub`.

Any idea how to work around this? because creating a Redis connection per client is not an option really.

Related issues: #484

**Comment by Marwes** [comment]
In that case we should add methods on `PubSub` to allow those additional methods to be called. I believe that would work for you?

**Comment by shekohex** [comment]
> In that case we should add methods on `PubSub` to allow those additional methods to be called. I believe that would work for you?

Yes. Indeed, although I don't know how that could work?
Any Idea how you could achieve this? I tried to do so in my fork .. but found it a bit hard actually.
but yes, if this possible would be great!

Currently, I made a workaround for this, I redesigned my pubsub flow, instead of subscribing on demand I made my all user's channels prefixed by a key and use pattern subscribe `psubscribe` to subscribe to this pattern `user:*:channel`  beforehand and then convert the pubsub into pure Rust stream of `Msg` and use a broadcast channel (`mpmc`) that goes with the stream and forward all the messages to the `tx` side of the channel. then I can freely clone the `rx` for each user, and filter the messages that flow into the `rx` stream by `channel_name` for this specific user.

I did that last night, and wrote a couple of unit tests.. and made a huge simulation of up to 10k users exchanging messages over a single Redis pubsub without any issue nor a single misrouted message!

**Comment by Marwes** [comment]
I guess you would also want to add a `async fn next(&mut self) -> Option<RedisResult<Msg>>` so you wouldn't need to use `on_message`

**Comment by rbtying** [comment]
> I guess you would also want to add a `async fn next(&mut self) -> Option<RedisResult<Msg>>` so you wouldn't need to use `on_message`

I think you actually don't want this to hold an &mut self reference: imagine the case where you are multiplexing the get-next-message future and want to subscribe to a new channel. If you drop the future, you may miss a message, as the future could have been completed but not yet polled. So you probably want to select against the future-- in which case it needs to be possible to hold both the next-message future and the new-subscription future at the same time.

**Comment by Bajix** [comment]
Just a thought, but something like a next message future I think is suboptimal when compared to the alternative of
using crossbeam deque and atomic counter based task spawning. This design you work steal in batches and then as this is entirely atomic based it only needs '&self' and is very well suited to thread local use. Crossbeam is astonishingly performant and this makes for less scheduling overhead. For a lot of use cases, you could move a stealer handle into a spawn_blocking and work steal process everything while only pausing when there's no work and we're waiting to spawn the next task handler. Also the on_message could use tokio::task::spawn as needed and simply be a callback with stealer handles that are called whenever new work is to be had after all had previously been stolen.

**Comment by dsluijk** [comment]
Hello! I've run into the same issues. As there is currently no way to do this easily with the `redis` crate, I decided to make my own solution. You can find it on [crates.io](https://crates.io/crates/redis-subscribe), and on [GitHub](https://github.com/nexiumapp/redis-subscribe). I would love it if this crate is redundant in the future, but in the mean time it's a solution for me.

**Comment by iceisfun** [comment]
Could a get_message_timeout be added? In the python implementation for this get_message takes a timeout and returns None if the timeout elapses without a new message.

**Comment by Marwes** [comment]
@iceisfun  If you use the async version you can use a `timeout` future to get that behavior https://docs.rs/tokio/1.15.0/tokio/time/fn.timeout.html

**Comment by richardhenry** [comment]
The following pattern seems to be a decent workaround for this issue, allowing you to subscribe or unsubscribe while otherwise listening for messages. Let me know if this is a bad idea for some non-obvious reason — it seems to work just fine. I'd love better support for this in the library.

``` rust
pub enum PubSubCmd {
    Subscribe(String),
    Unsubscribe(String),
}

async fn main() -> Result<(), Error> {
    let mut redis = ...
    let (cmd_tx, mut cmd_rx) = mpsc::channel::<PubSubCmd>(32);

    loop {
        let cmd: Option<PubSubCmd>;

        loop {
            let mut stream = redis.on_message();

            select! {
                value = stream.next() => {
                    if let Some(msg) = value {
                        // Handle a message here.
                    } else {
                        // The Redis pub/sub connection was dropped and we can exit.
                        cmd = None;
                        break;
                    }
                }
                value = cmd_rx.recv() => {
                    // If value is Some: Break out of the inner loop, update the connection, then listen again.
                    // If value is None: The cmd_tx was dropped and we can exit.
                    cmd = value;
                    break;
                }
            }
        }

        match cmd {
            Some(PubSubCmd::Subscribe(channel)) => redis.subscribe(channel).await?,
            Some(PubSubCmd::Unsubscribe(channel)) => redis.unsubscribe(channel).await?,
            None => return Ok(()), // Exit
        };
    }
}
```

**Comment by nihohit** [comment]
If you're using Redis/Valkey v6 or newer, you can use the RESP3 pubsub in order to use a regular connection with pubsub - https://docs.rs/redis/latest/redis/#resp3-async-pubsub
If not, I hope that in the next version the async pubsub connection could be split, which will allow this behavior.
https://github.com/redis-rs/redis-rs/pull/1144

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1144
