### ISSUE TITLE
Feature request: Add PubSub to MultiplexedConnection

### ISSUE THREAD

**Issue by Bajix** [redis-rs/redis-rs#533]
According to the Redis [documentation](https://redis.io/topics/client-side-caching) on server-assisted client side caching as of Redis 6 the RESP3 protocol can run queries while receiving invalidation messages on the same connection. This implies that a multiplexed connection can now be used for PubSub, the currently only Connection structs can currently receive messages.

**Comment by yurenji** [comment]
+1 

I think this issue is related to  https://github.com/mitsuhiko/redis-rs/issues/509

**Comment by Bajix** [comment]
Yea I suppose what that other issue really would want is PubSub on Multiplexed and not a change to regular connection PubSub. It's also possible to add support for invalidation without adding PubSub to Multiplexed, though ideally both would be supported and the latter enables the former by way of the compatibility layer designed in the Redis spec should first-class support for invalidation not take precedence.

**Comment by yurenji** [comment]
I have a use case which is related to this issue: The program needs to subscribe 100-300 channels (I suppose spawn a task for each subscribe) and write received data in a HashMap (or [dashmap](https://docs.rs/dashmap/4.0.2/dashmap/)) to share state, and in the main thread another task will do some calculation based on the hashmap data.  

Is there a suggested way to implement this? Or can I implement this without a pubsub MultiplexedConnection?

**Comment by sarendsen** [comment]
+1

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/898

**Comment by nihohit** [comment]
multiplexed connection now supports RESP3 pubsub. closing.
