### ISSUE TITLE
AsyncIter's Stream impl is broken

### ISSUE THREAD

**Issue by talchas** [redis-rs/redis-rs#537]
For each call into `poll_next()`, it restarts `this.next_item()` from the start, which would result in resending the command (or parts of the command, or throwing away the already-read first half of a response, or...). It would need to store the pinned Future if it returned Pending, and reuse that Future on the next call to poll_next(), until that Future is done. Take a look at futures's Unfold implementation for what it would look like.

**Comment by jaymell** [comment]
Fixed by #597
