### ISSUE TITLE
Sentinel support?

### ISSUE THREAD

**Issue by guaychou** [redis-rs/redis-rs#539]
How to create client with sentinel support that can auto listen and watch the master node changes?

**Comment by doyshinda** [comment]
I took a stab at implementing a SentinelClient in my [fork](https://github.com/doyshinda/redis-rs/tree/sentinel). It supports querying for the master directly or subscribing to updates (you'll receive a message through a crossbeam channel when master node changes).

**NOTE:** This code has not been fully tested and should not be used in production.

**Comment by aljazerzen** [comment]
For anyone in the future: I've needed this and made [my own library](https://github.com/aljazerzen/redis-sentinel-rs) that correctly implements sentinel connection and can be used as extension to this crate.

It's a fork of some other library, but with a major overhaul.
