### ISSUE TITLE
redis::commands: Support floating point timeout arguments

### ISSUE THREAD

**Issue by PiDelport** [redis-rs/redis-rs#543]
`redis::commands` currently uses integer seconds for the `timeout` argument of the blocking list pop commands, but Redis 6 switched to interpreting these arguments as floating point seconds.

Switching these arguments from `usize` to `impl Into<f64>` should work?

**Comment by Marwes** [comment]
If they support sub-second granularity we may as well take `Duration` as a the type, perhaps?

**Comment by PiDelport** [comment]
@Marwes: Yeah, `Duration` would be ideal.

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/988
