### ISSUE TITLE
Redis stream xadd vs xread

### ISSUE THREAD

**Issue by b00f** [redis-rs/redis-rs#544]
`xadd_map` function accepts `BTreeMap` of key-value pairs, however `xread` returns `HashMap` of key-value pairs.

We are working on serialization and deserialization crate for redis ([here](https://github.com/b00f/serde-redis/tree/main)), and this mismatched type will cause difficulties for the user to use the serde crate.

Is there any explanation for this weird behaviour?

**Comment by Terkwood** [comment]
Honestly, I just think this API mismatch wasn't discussed during the streams work, and can be considered an oversight, rather than something intentional
