### ISSUE TITLE
`tokio::select` with async ConnectionManager and channel for cancelation

### ISSUE THREAD

**Issue by BratSinot** [redis-rs/redis-rs#553]
Greetings!

I have some problem with task cancellation. So, example:
```rust
let mut redis = ConnectionManager::new(REDIS_CLIENT.clone()).await?;
<...>
let (tx, mut cancel) = mpsc::channel(1);
let task = tokio::task::spawn(async move {
    loop {
        let data = tokio::select! {
            data = redis.xread_options::<_, _, StreamReadReply>(mwi, &now, &opts) => data,
            _ = cancel.recv() => break,
        };
<...>
    }
});
```
When I send `tx.send(()).await;`, yeah, loop are breaking. But, future with `redis.xread_options` (from what I read) just suspends without releasing data. So, as result, I got dangling connection to Redis DB.

And I noticed one more thing: if xread get some data after abortion, connection will be closed.

**Comment by maximebedard** [comment]
Hello! I'm getting a similar behaviour with intervals where the call to xread_options doesn't seem to be cancellation safe.

```rust
let conn = redis_client.get_tokio_connection().await.unwrap();
let mut interval = tokio::time::interval(Duration::from_secs(1);
loop {
  tokio::select! {
    // data would get printed twice
    data = redis.xread_options::<_, _, StreamReadReply>(mwi, &now, &opts) => println!("{:?}", data);
    _ interval.tick() => {},
  }
}
```

Not sure if anyone would happen to have an idea 🤔

**Comment by bbaldino** [comment]
I think I'm running into this as well.  I've got an actor-style struct which listens for both control messages (on an mpsc queue) and an `xread_options` call in a tokio::select.  When the non-xread_options branch hits, I'm seeing scenarios where the redis `xread_options` call isn't cancelled and I end up reading the same message twice from the redis stream.

**Comment by nihohit** [comment]
related: https://github.com/redis-rs/redis-rs/issues/851
The call is cancellation safe, its just that your expectation towards cancellation are incorrect. 
Cancellation only cancells receiving the request. It doesn't cancel sending the request to the server (unless the call is cancelled before it started), and it doesn't cancel the state that is set on the server's side for the connection. 

So, cancellation can't cancel the network communication, and it can't cancel the server-side state. It can only cancel waiting for the result.

**Comment by nihohit** [comment]
although [maximebedard](https://github.com/maximebedard)'s issue stems from the usage of the now depracted `aio::Connection`.
