### ISSUE TITLE
How to close a connection?

### ISSUE THREAD

**Issue by jiashiwen** [redis-rs/redis-rs#569]
hi:
I want to know how to close a open connection.
thx

**Comment by Parth** [comment]
When a connection is dropped it will be closed, what are you trying to do?

**Comment by jasongoodwin** [comment]
i had some similar issues with connections staying open for a long time and consuming a lot of resources (OSX). I ended up using the r2d2 feature.

**Comment by llvvrui** [comment]
I have a require how to close connection?

**Comment by djc** [comment]
Just drop the `Connection` value.
