### ISSUE TITLE
Scan blocks forever using next from futures_util::stream::StreamExt

### ISSUE THREAD

**Issue by Roger** [redis-rs/redis-rs#583]
This is quite interesting bug, using `MultiplexedConnection` or `ConnectionManager` (that I guess is because is using `MultiplexedConnection` internally), also having more than 10 keys in redis (I think this is because then it actually paginates, using the cursor) and using `Stream` trait, ie. `StreamExt::next`. I found this first trying to run `StreamExt::collect` on the on the result of scan. Using `next_item` instead of `next` works as expected (I wasn't expecting that, because `next` implementation actually uses `next_item`).

This is a minimal way to trigger the issue:
```rust
 use futures_util::stream::StreamExt;
 use redis::AsyncCommands;

 #[tokio::main]
 async fn main() {
     let client = redis::Client::open("redis://127.0.0.1/").unwrap();
     let mut conn = client.get_multiplexed_tokio_connection().await.unwrap();
     for i in 0..11 {
         let _: () = conn.append(format!("test/{}", i), i).await.unwrap();
     }

     let mut values = conn.scan_match::<&str, String>("test/*").await.unwrap();
     while let Some(v) = values.next().await {
         println!("{}", v);
     }
 }
```

**Comment by dizda** [comment]
Hi,

I have the same issue here,

```rust
use redis::aio::MultiplexedConnection;
use redis::{AsyncCommands, AsyncIter, RedisResult};
use tokio_stream::StreamExt;

async fn scan_keys(con: &mut MultiplexedConnection, pattern: String) -> RedisResult<()> {
    let iter: AsyncIter<String> = con.scan_match(pattern).await?;
    let mut keys: Vec<String> = iter.collect().await;
    info!(?keys, "scanned keys found");

    for key in keys {
        info!(%key);
    }
}
```

Blocks forever, probably because having 50+ keys on redis.

**Comment by thalesfragoso** [comment]
> I wasn't expecting that, because next implementation actually uses next_item

This is a bug on the `poll_next` implementation of `AsyncIter`. It creates a new future on each call, polls it once and then drops it. Instead, it should hold on to the future until it returns `Poll::Ready`, and, if the returned value was `Some`, create another one and repeat the process until `Poll::Ready(None)` is returned.

**Comment by Roger** [comment]
oh, right, this blocks when `next_item` returns `Poll::Pending`, that seems to happen when new data is needed from redis and that's why only happens when you have more than 10 items in the iterator.

I wonder if it's possible to fix this, without breaking compatibility, since `Stream` is implemented on top of `AsyncIter` and we can't hold state there, I guess we need to convert `AsyncIter` into an struct that is able to hold the `next_item` future until is ready

**Comment by Roger** [comment]
Maybe instead of doing `AsyncIter` an `Stream`, add a method to create an `Stream` from `AsyncIter` ie.

```rust
impl<'a, T: FromRedisValue + 'a> AsyncIter<'a, T> {
    ...
    pub fn stream(self) -> impl futures::Stream<Item = T> + 'a {
        Box::pin(futures::stream::unfold(self, |mut cur_self| async {
            cur_self.next_item().await.map(|item| (item, cur_self))
        }))
    }
}
```

And use it like:
```rust
let values = conn.scan_match::<&str, String>("test/*").await.unwrap();
let mut values = values.stream().collect::<Vec<_>>().await;
```
