### ISSUE TITLE
Call to a potentially blocking function in aio::connect_simple

### ISSUE THREAD

**Issue by thalesfragoso** [redis-rs/redis-rs#591]
`connect_simple` (which is async) calls `get_socket_addrs`:
https://github.com/mitsuhiko/redis-rs/blob/b8eb47303c5728e943b914cd10dc35d1fceee05c/src/aio.rs#L459

Which will end up calling the libstd implementation of `ToSocketAddrs`  for `str`, this will block if the str is a hostname:
https://github.com/mitsuhiko/redis-rs/blob/b8eb47303c5728e943b914cd10dc35d1fceee05c/src/aio.rs#L496

The usual way to solve this is to wrap the call to `to_socket_addrs` in a "spawn_blocking", both `tokio` and `async-std` have utility functions for that. I guess we could either add `spawn_blocking` to the `RedisRuntime` trait, or a more specific method, like `get_socket_addrs` or `lookup_host`. I think I would prefer the most general `spawn_blocking`, since it can be useful for other stuff.

I can provide a PR once there's a minimal consensus on the proper solution.

**Comment by tasn** [comment]
Related to #379
