### ISSUE TITLE
Example for subscribe/unsubscribe, subscribe_once or timeout?

### ISSUE THREAD

**Issue by niuhuan** [redis-rs/redis-rs#592]
I want subscribe a message (only one), return error if wait time out. but i not found the way.

```rust
let time_out_sec = 30;
let client: Client;
let mut sub = self.get_async_connection().await?.into_pubsub();
sub.subscribe("key").await?;
 // todo       
```

**Comment by younes-io** [comment]
Have you checked [this example](https://github.com/mitsuhiko/redis-rs/blob/c005735470e487b0029d4c544867dc4ced670b4a/examples/async-pub-sub.rs)?

**Comment by niuhuan** [comment]
I don't known how to set timeout.
