### ISSUE TITLE
async-std-comp feature pulls in tokio dependency

### ISSUE THREAD

**Issue by UgnilJoZ** [redis-rs/redis-rs#593]
The Cargo feature `async-std-comp` depends on the `aio` feature, which in turn depends on a few `tokio/*` features.

Is this necessary, e.g. are things in tokio actually used when using another async runtime?

**Comment by Marwes** [comment]
Yes, the tokio `AsyncRead/Write` traits are used (but nothing else) which forces tokio to be pulled in. This could be changed but :shrug: the final binary would barely contain any extra code, if any.

**Comment by nihohit** [comment]
closing as answered.
