### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by jqnatividad** [redis-rs/redis-rs#594]
Especially with the itoa reaching v1 and dtoa 0.4.8 replaced by ryu v1. 

https://github.com/mitsuhiko/redis-rs/pull/588

**Comment by djc** [comment]
I think this will need to be 0.22, since #576 changed the available features. I have not yet audited the rest of the PRs to see if there are API-incompatible changes, but I wouldn't be surprised if there were more.

**Comment by djc** [comment]
#666 prepares a 0.21.6 release.

**Comment by djc** [comment]
0.21.6 has been released, thanks!
