### ISSUE TITLE
Redis ClusterClient doesn't work with non default user

### ISSUE THREAD

**Issue by gildaf** [redis-rs/redis-rs#595]
(release 0.21.5)
The cluster client will fail to execute commands if the user is not "default" . 

Reproduce:
setup a redis cluster and add an acl file to all nodes ([helper script](https://gist.github.com/gildaf/4f48c71451528c56bd7ebf7f60cb09a5)). 
now connect to one node and execute a command
```rust
let client = redis::cluster::ClusterClient::open(vec!["redis://gil:somepass@localhost:5001"]).unwrap();
let mut connection = client.get_connection().unwrap();
let res: RedisResult<()> = connection.set("x", "3");
```
The `set` command will fail with `Password authentication failed` Error.

**Comment by jaymell** [comment]
Fixed by #596
