### ISSUE TITLE
the trait `redis::ConnectionLike` is not implemented for `ConnectionManager`

### ISSUE THREAD

**Issue by azerpas** [redis-rs/redis-rs#598]
## Setup
- redis-rs v0.21.5

## Code
```rs
#[tokio::main]
#[test]
async fn connection_manager_can_use_transaction() -> Result<()> {
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let manager = redis::aio::ConnectionManager::new(client).await?;
    
    let (new_val, val) : (isize, String) = redis::transaction(&mut manager, &["task_id"], |con, pipe| {
        let old_val : isize = redis::cmd("GET").arg("task_id").query(con)?;
        redis::pipe()
            .cmd("INCR").arg("task_id")
            .cmd("GET").arg("task_id")
            .query(con)
    })?;

    println!("{:?}", task_groups);

    Ok(())
}
```

## Error
`the trait redis::ConnectionLike is not implemented for ConnectionManager`
```
error[E0277]: the trait bound `ConnectionManager: redis::ConnectionLike` is not satisfied
    --> src/main.rs:181:63
     |
181  |     let (new_val, val) : (isize, String) = redis::transaction(&mut manager, &["task_id"], |con, pipe| {
     |                                            ------------------ ^^^^^^^^^^^^ the trait `redis::ConnectionLike` is not implemented for `ConnectionManager`
     |                                            |
     |                                            required by a bound introduced by this call
     |
```

While on [docs.rs](https://docs.rs/redis/latest/redis/aio/struct.ConnectionManager.html#impl-ConnectionLike)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/19282069/164708644-a036d30d-8b89-4a6f-a5f9-e3e480950c4d.png">

(cc @tixwell)

**Comment by LeoRowan** [comment]
So `ConnectionManager` doesn't implement `redis::ConnectionLike`, but instead it implements `redis::aio::ConnectionLike`, which is actually a different trait. Confusing, I know.

Instead of using `.query(con)`, you want to use `.query_async(con)` (which accepts an `impl redis::aio::ConnectionLike`).

Imho, `redis::aio::ConnectionLike` should probably be renamed to `redis::aio::AsyncConnectionLike` to prevent this sort of confusion.

**Comment by azerpas** [comment]
> So `ConnectionManager` doesn't implement `redis::ConnectionLike`, but instead it implements `redis::aio::ConnectionLike`, which is actually a different trait. Confusing, I know.
> 
> Instead of using `.query(con)`, you want to use `.query_async(con)` (which accepts an `impl redis::aio::ConnectionLike`).
> 
> Imho, `redis::aio::ConnectionLike` should probably be renamed to `redis::aio::AsyncConnectionLike` to prevent this sort of confusion.

That's what I thought... 

Does anyone know how I could use the `redis::transaction` function with `redis::aio::ConnectionLike` ?
Am I restrained to the use of low level API with `MULTI`, `EXEC`, etc commands?

**Comment by LeoRowan** [comment]
Yeah, I'm pretty sure `redis::transaction` is broken with `aio`. I remember seeing a few issues about it, and there's a workaround for it involving a macro. I don't remember the issue number, so you may have to do a little searching.

**Comment by nihohit** [comment]
`aio::ConnectionLike` is implemented for `connection_manager`, and `pipeline` objects can be used on it for transactions.

**Comment by nihohit** [comment]
@clbarnes true! And there are a couple of PRs trying to tackle that problem.
