### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by Marwes** [redis-rs/redis-rs#602]
I picked up maintenance of this crate a couple of years ago as it was heavily used at my work at the time. Since then I have switched jobs so I no longer have a direct motivator to continue maintenance.

If anyone is feeling that they can and want to take over, please let me know.

cc https://github.com/mitsuhiko/redis-rs/issues/376

**Comment by doyshinda** [comment]
I am willing to help out, though I'm a bit hesitant about the "take over" part.

I believe it would be beneficial to have at least 2 active maintainers to share the load.

**Comment by namkai** [comment]
I am also happy to help out but I don't think I have the experience with Redis or Rust required to fully take over.

**Comment by jaymell** [comment]
I'm also happy to take over (or share) the maintainership of this repo. We rely on it quite heavily at work, so my employer is supportive of this, though even if they weren't I'd have been happy to do it in my free time. :)

I'm very familiar with Redis, especially cluster mode, and quite competent in Rust. I co-wrote [a PR on the adjacent redis-cluster-async](https://github.com/Marwes/redis-cluster-async/pull/9), and I'm also in charge of a private fork (with changes that aren't ready for upstream yet) at my company.

**Comment by Marwes** [comment]
Having someone that can merge PRs and do new releases to crates.io is the most important part so if you think you can do that @jaymell then I'd be happy to give you access to crates.io. I don't seem to actually have permission to give access to the github repo so either @mitsuhiko needs to give access, or we fork this to a github organization where we have control.

**Comment by Marwes** [comment]
Secondly, I see that both @mitsuhiko and @badboy still have access to redis on crates.io. Since you haven't done any releases in some time I'd probably remove you (and if everything goes well with moving to a new maintainer I will remove myself/I should be removed as well).

**Comment by svix-james** [comment]
Thanks. I'd be happy to manage PR merging and releases and can probably create a github action to automate this.

**Comment by mitsuhiko** [comment]
I'm happy to transfer this repository.

**Comment by mitsuhiko** [comment]
What I did for now is create an organization for the crate. We can figure out stuff from there.

**Comment by djc** [comment]
I'm also using this crate for work, so happy to help with maintenance.

**Comment by mitsuhiko** [comment]
I sent some invites out :)

**Comment by jaymell** [comment]
Thanks for the invite -- I'm humbled and will do my best to be a good steward.

**Comment by djc** [comment]
@jaymell do you hang out in any chat venues like the Rust community Discord, the Tokio Discord, Matrix or Gitter? Might be nice to coordinate a bit how we organize things.

**Comment by NathanielCurnick** [comment]
I use this crate a lot at work, I would be happy to help out in maintaining it!

**Comment by djc** [comment]
Anyone who wants to help out, please start by reviewing open PRs and/or triaging issues!

**Comment by Marwes** [comment]
> Could we possibly bring https://github.com/Marwes/redis-cluster-async under the new organization as well with the goal of getting the functionality merged into the current repo eventually?

Done.

**Comment by tdyas** [comment]
If there is need for more maintainers, I can help out in a secondary capacity since my company uses this crate in production.

Also, I suggest creating a chat channel somewhere (e.g., Slack, Discord, etc.) to foster more direct communication among all interested parties. Maybe a channel on the Tokio Discord would be a good place (even though this crate is not Tokio-specific)?

**Comment by djc** [comment]
I don't think we have an urgent need right now, though I'll definitely be watching out for regular contributors to see if there's someone else we could recruit.

I'll discuss the creation of a chat channel with @jaymell.

**Comment by tasn** [comment]
@djc, maybe it's time to close this ticket (so people don't think this crate is unmaintained)?

**Comment by djc** [comment]
Fair enough!

**Comment by djc** [comment]
Update: I've decided to step down as a maintainer for now, since I have quite a lot on my plate already, I'm not very familiar with some aspects of the crate (for example, clustering) and in my opinion the code needs a lot of work which I'm unable to do. I've turned off the notification spew but am happy to answer specific questions if someone mentions me.

**Comment by utkarshgupta137** [comment]
@jaymell I've changed jobs & I'm no longer using Redis, but I'd be happy to assist.
