### ISSUE TITLE
connection pool for sync redis connections

### ISSUE THREAD

**Issue by nonirosenfeldredis** [redis-rs/redis-rs#621]
Hi, I want to add connection pool of sync redis connections. something quite like the python client impl. its a non blocking pool . any objections or directions I should follow?

**Comment by djc** [comment]
You can use the r2d2 crate.

**Comment by nonirosenfeldredis** [comment]
got it . I will add some explanation in the r2d2 file and sample code how to use it

**Comment by nonirosenfeldredis** [comment]
Hi @djc I want to create PR for add some sample example code as comment to r2d2. how can I get write access to this Repo?

**Comment by djc** [comment]
You wouldn't get write access to this repository, you'd use the `Fork` button in the upper right to create a fork of this repo in your own account/org, submit a branch there and then create a PR from that.

**Comment by nihohit** [comment]
closing since the question was answered.
