### ISSUE TITLE
1.51 support broken due to async-global-executor upgrade

### ISSUE THREAD

**Issue by djc** [redis-rs/redis-rs#624]
2.1.0 requires 1.59. Some discussion in https://github.com/async-rs/async-global-executor/issues/10.

**Comment by jaymell** [comment]
What if we were to as a short-term measure pin the `async-std` version as follows:
```async-std = { version = "= 1.8.0", optional = true}
```

**Comment by djc** [comment]
Yeah, I guess that's reasonable, although we won't want to release with that.
