### ISSUE TITLE
create chat channel for crate support

### ISSUE THREAD

**Issue by tdyas** [redis-rs/redis-rs#626]
As suggested by https://github.com/redis-rs/redis-rs/issues/602#issuecomment-1129563367, maybe create a chat channel somewhere to allow users and developers of this crate to discuss support and development-related issues? (Opening as a separate issue so the idea does not get lost since the other issue is now closed.)

One idea would be a channel on the Tokio Discord if they allow Tokio-adjacent projects to have channels there.

**Comment by djc** [comment]
This already happened. I think this is an invite link? https://discord.gg/VpcsmtbQ

**Comment by tdyas** [comment]
That worked. Maybe that could go into the README?

**Comment by djc** [comment]
I think this particular link is only valid for like 7 days? Not sure how to a permalink.

**Comment by tdyas** [comment]
You can disable expiration of invite links. See https://support.discord.com/hc/en-us/articles/208866998-Invites-101
