### ISSUE TITLE
Pub/Sub subscribe to multiple channels

### ISSUE THREAD

**Issue by HFF-dev** [redis-rs/redis-rs#629]
I am fairly new to rust and I am trying to subscribe to multiple (not fixed length) of channels on one pubsub connection. Passing a slice of strings to `psub.subscribe()` compiles fine , but connection closes instantly and no messages are received.

This is my implementation:

        pub async fn start_pubsub<T, U: redis::ToRedisArgs>(
            client: &Client,
            channels:U,
            closure: T
        ) -> Result<(), ApiError> where T: FnOnce(PubSub) {
            let mut pubsub = client.get_async_connection().await?.into_pubsub();
        
            
            pubsub.subscribe(&channels).await?;
            closure(pubsub);
            Ok(())
        }

If i pass a str with a single channel name, everything works just fine.

Do i need to call subscribe individualy on each of the channels? What would be the overhead if my list contains 50+ channels?

**Comment by djc** [comment]
Maybe try with `channels: &[U]` or `channels: Vec<U>`?

**Comment by djc** [comment]
Well, I'm pretty sure there must be a way to make it work. Maybe somehow debug what happens on the wire?

**Comment by djc** [comment]
What command are you issuing before `start_pubsub`?

**Comment by HFF-dev** [comment]
Pretty much only create_client()

        let conn = create_client(con_str.to_string())
                    .await
                    .expect("Can't connect to redis");

        let (tx, rx) = mpsc::channel(10_000);
        let consumer = |pubsub: PubSub| {
            let mut msg_stream = pubsub.into_on_message();
            tokio::spawn(async move {
                while let Some(msg) = msg_stream.next().await {
                    // ... message processing
                    match tx.send(Result::<_, Status>::Ok(processed_message)).await {
                            Ok(_) => {}
                            Err(_item) => {
                                break;
                            }
                        }
                }
            });
        };
        
        let channels = request_channels.as_slice();
        start_pubsub(&conn, channels, consumer).await?;

**Comment by djc** [comment]
Well, I don't know what's going on here. It could be there's a bug in this library, but I think it needs more debugging before we understand what's going on.

**Comment by HFF-dev** [comment]
Upon further investigation i can see that under some circumstances, the pubsub stream instantly yields Option with value None..

This is working fine, awaits and yields the message just fine from all 3 channels A, B and C 

    pubsub.subscribe("A").await?;
    let channels = ["B","C"];
    pubsub.subscribe(&channels).await?;
    let mut msg_stream = pubsub.into_on_message();
    let pubsub_msg: String = msg_stream.next().await.unwrap().get_payload().expect("msg");
    println!("{:?}", pubsub_msg);

This causes a panic right away:

      let channels = ["A","B"];
      pubsub.subscribe(&channels).await?;
      let mut msg_stream = pubsub.into_on_message();
      let pubsub_msg: String = msg_stream.next().await.unwrap().get_payload().expect("msg");

      ^^^^ panicked at 'called `Option::unwrap()` on a `None` value'

Kind of shooting in the dark, but could it be that the subscribe messages are not handled correctly if passing multiple channels in one SUBSCRIBE command (the output is much longer when subscribing to multiple channels at once) and this somehow slips into msg_stream?

**Comment by HFF-dev** [comment]
I can definitely confirm that the issue was caused by the response to SUBSCRIBE commands.  I cloned the crate localy and applied the patch from https://github.com/redis-rs/redis-rs/pull/486 - the issue no longer exists and everything works as expected.

**Comment by djc** [comment]
Great, thanks for digging in! I pinged the original submitter of that PR, if they don't respond please open a new PR that merges their changes into current main.

**Comment by nihohit** [comment]
@HFF-dev can you still reproduce this with recent versions? I've tried, and it seems like the issue was fixed.

Closing, since this is an old issue. Feel free to reopen if you still see this happening.
