### ISSUE TITLE
WEIGHTS option for ZUNIONSTORE/ZINTERSTORE

### ISSUE THREAD

**Issue by ndd7xv** [redis-rs/redis-rs#634]
I was working through writing some of the code from [Redis in Action](https://redis.com/ebook/redis-in-action/) and reached a point where the author uses [ZINTERSTORE in order to scale the scores of a ZSET by .5.](https://github.com/josiahcarlson/redis-in-action/blob/1f9af9493b0dad758fd7ff807ef20dbabcf550e3/python/ch02_listing_source.py#L185) I poked around the docs and source for redis-rs but couldn't find anything related to the weights option.

Is it currently possible to use WEIGHTS (as described [here](https://redis.io/commands/zunionstore/)) in this library, and if not, would it be possible to add this functionality? I'd be willing to try my hand at a PR but may need help if stuck.

**Comment by djc** [comment]
A PR would be welcome!
