### ISSUE TITLE
Why `Connection` should be `&mut` rather than `&` when execute commands?

### ISSUE THREAD

**Issue by stackinspector** [redis-rs/redis-rs#638]
Is this a deliberate restriction because `Connection` cannot be safely shared between threads?

**Comment by djc** [comment]
A `Connection` is, at its core, a `TcpStream`, and sending or receiving on that stream requires a mutable reference to it. If multiple threads would be writing to the same socket concurrently, I don't think it's obvious how you'd order the outgoing bytes on the wire.

**Comment by kamulos** [comment]
I am using a `MultiplexedConnection` in my program. To me it feels wrong that (through `ConnectionLike`) it takes a mutable reference. Of course this can always be handled by just cloning it, but it is certainly different than other database drivers.

I have however no idea how this could be improved.

**Comment by djc** [comment]
What other database drivers are you comparing it to?

**Comment by LuisOsta** [comment]
Yeah this is something I also noticed which I didn't love compared to using the `mongodb` Rust crate
