### ISSUE TITLE
PubSub should support PING and other commands redis allows

### ISSUE THREAD

**Issue by tugtugtug** [redis-rs/redis-rs#639]
According to https://redis.io/docs/manual/pubsub/#:~:text=The%20commands%20that%20are%20allowed,the%20mode%20with%20Ctrl-C%20.
A subscriber connection can still ping the server. 

However, the current implementation seems to have purposely disabled such functions. We rely on it for server end connection management.

Can we please allow pings for the PubSub connections?

---- EDIT ---

The code seems extremely confusing with the `pubsub` boolean field. The `pubsub` does not seem to be ever set when PubSet is in use and intentionally so, as
https://github.com/redis-rs/redis-rs/blob/624a59a34b3b205c44e26a0391be1757d54a7e10/src/connection.rs#L718,
so technically, this `pubsub` flag is only used if a previous PubSub connection failed to unsubscribe all channels. Maybe name it `pending_unsubscribe` to be more accurate.

Since the PubSub takes the connection and hides it as an internal member, other than the exposed interfaces, the connection really is only accessible after either the PubSub is dropped or is transformed into a connection again.
So, is it possible to just provide a new function for PubSub to send ping? I'm unfamiliar with the reader, so not sure if that would break if one creates the on_message stream (for the async implementation), then sends a ping, as that now requires multiplexing of the responses.

**Comment by djc** [comment]
Unfortunately I don't have a lot of capacity to allocate to this crate. I think it would make sense to add a `ping()` API to `PubSub` and I would be happy to review a PR implementing it, but I won't be able to work on it much (nor do have I time right now to investigate how it should work exactly).

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/898

**Comment by nihohit** [comment]
If you're using Redis/Valkey v6 or newer, you can use the RESP3 pubsub in order to use a regular connection with pubsub - https://docs.rs/redis/latest/redis/#resp3-async-pubsub

**Comment by nihohit** [comment]
implemented in https://github.com/redis-rs/redis-rs/pull/1341 .
