### ISSUE TITLE
Debug impl for `MultiplexedConnection` & `Pipeline`

### ISSUE THREAD

**Issue by elpiel** [redis-rs/redis-rs#649]
Hello,
First of all, thanks for the amazing work on the `redis` crate!
I'm trying to use the `tracing` crate for an async application with tokio & tokio-console, however, I'm unable to use the `#[instrument]` attribute on async function as there is no Debug impl for `MultiplexedConnection` & `Pipeline`

Would you consider such addition to the code?
`aio::Pipeline` seems the most difficult part to implement. What information and other considerations should be taken into account for implementing Debug for Pipeline?

**Comment by djc** [comment]
Yes, I would be open to having `Debug` implementations for these. I don't have much of an idea about what should be in them, please submit a PR using your best judgement and I'll review from there.

**Comment by elpiel** [comment]
Ok, let me take a look and see what I can impl
