### ISSUE TITLE
Async, connection-pooled Cluster client

### ISSUE THREAD

**Issue by zombiezen** [redis-rs/redis-rs#658]
Perhaps I have missed something, but is there not an equivalent of `redis::aio::ConnectionManager` for Redis Cluster?

**Comment by djc** [comment]
Are you aware of https://github.com/redis-rs/redis-cluster-async already?

**Comment by zombiezen** [comment]
Yes, but it looks like it does not pool connections? https://docs.rs/redis_cluster_async/latest/redis_cluster_async/struct.Client.html#method.get_connection seems to open a new connection each time.

**Comment by djc** [comment]
I don't think `redis::aio::ConnectionManager` is really a pool -- as I understand it, it's just a connection that knows how to reconnect when its inner connection drops. For pooling, I recommend looking at deadpool or bb8 (though I don't know if a connection manager for the cluster thing already exists).

**Comment by jaymell** [comment]
There is an example using bb8 with the `redis-cluster-async` lib here: https://github.com/svix/svix-webhooks/blob/main/server/svix-server/src/redis/cluster.rs

**Comment by Owez** [comment]
Small note to anyone attempting this: pubsub is hard with async + connection pooling with deadpool

**Comment by casret** [comment]
@djc Do you happen to know why they are maintained as 2 seperate crates?

**Comment by djc** [comment]
They were historically developed separately/by different people. No good reason now...

**Comment by nihohit** [comment]
Closing since cluster connection has been merged.
