### ISSUE TITLE
Question regarding best practices on managing connections

### ISSUE THREAD

**Issue by stevenhansel** [redis-rs/redis-rs#665]
I have been using this library for quite a while and the way I use it is that I just create one `Connection` with `client.get_connection()` and then share it through all of my application (by wrapping it with `Arc<Mutex<Connection>>`. I have found that if the host connection is lost, then it will just throw an error. I was thinking on how to handle the reconnect logic and it make me think, is `client.get_connection()` an expensive operation? If not, I think I will just try create a new connection whenever I want to execute a Redis command. In summary, my question is what's the best practice on managing connections, do you just create one and share it through the whole application lifetime or can you just `get_connection()` every time you want to execute a command?

**Comment by djc** [comment]
Normally people will use a connection pool, for example using the deadpool or bb8 crates.

**Comment by stevenhansel** [comment]
@djc Thank you for answering my question, straight to the point! Closing this issue as my problem is resolved 👍

**Comment by marcustut** [comment]
What about when using Redis Sentinel? In the case that a connection fails do I still need to manually request for a new connection as well?
