### ISSUE TITLE
AclInfo: Expect a valid ACL flag

### ISSUE THREAD

**Issue by garyhai** [redis-rs/redis-rs#682]
Implementation of `FromRedisValue` for `AclInfo` misses "allchannels" flag and therefore fail to call `conn.acl_getuser` with `not_convertible_error`

```rust
use redis::{acl::AclInfo, Client, Commands};

const CONN_INFO: &str = "redis://127.0.0.1";

fn main() {
  let client = Client::open(CONN_INFO).unwrap();
  let mut conn = client.get_connection().unwrap();
  let info: AclInfo = match conn.acl_getuser("default") {
    Err(e) => {
      dbg!(e);
      return;
    }
    Ok(info) => info,
  };
  dbg!(info);
}
```
output:
```sh
[src/main.rs:10] e = Response type not convertible: "Expect a valid ACL flag" (response was [97, 108, 108, 99, 104, 97, 110, 110, 101, 108, 115])
```

To fix the issue, in acl.rs:
```rust
let flags = flags
                    .as_sequence()
                    .ok_or_else(|| {
                        not_convertible_error!(flags, "Expect a bulk response of ACL flags")
                    })?
                    .iter()
                    .map(|flag| match flag {
                        Value::Data(flag) => match flag.as_slice() {
                            b"on" => Ok(Rule::On),
                            b"off" => Ok(Rule::Off),
                            b"allkeys" => Ok(Rule::AllKeys),
                            b"allcommands" => Ok(Rule::AllCommands),
                            b"nopass" => Ok(Rule::NoPass),
                            b"allchannels" => Ok(Rule::Pattern("&*".into()),
                            _ => Err(not_convertible_error!(flag, "Expect a valid ACL flag")),
                        },
```

**Comment by djc** [comment]
Thanks for the report! Would you mind submitting a PR for this?

**Comment by garyhai** [comment]
I'd be happy to submit a PR for the bug. But a more complete change involves structural changes to the Rule, causing compatibility issues. And there are more flags to add with latest version of redis. It is best to be carefully designed by professional team.

**Comment by djc** [comment]
I guess as the volunteer maintainer of this crate I would qualify as professional, but I'm also very busy with maintaining a number of other crates in addition to working at my day job. So this is unlikely to get done unless you (or someone else motivated to work on this) can make some progress on it.

**Comment by garyhai** [comment]
Thank you for your selfless contribution to this project. Let me try to fix this bug without breaking compatibility.
