### ISSUE TITLE
Handle timeouts in redis::aio

### ISSUE THREAD

**Issue by jkutlusan** [redis-rs/redis-rs#683]
It does not currently seem possible to set timeouts on connecting, reading and writing in redis::aio. It is unclear whether using tokio::time::timeout around redis::aio requests would lead to corruption of the underlying connection.

What is the best way to go around implementing timeouts around redis::aio requests, and can I contribute?

**Comment by jaymell** [comment]
Thanks for creating the issue: Timeouts in the async connections are definitely something that needs to be addressed. I've been looking into this recently as the lack of them is causing intermittent issues in my day job. :sweat_smile: I'm hoping we can have something working relatively soon, but nevertheless, PRs are always welcome. :smile:

**Comment by jkutlusan** [comment]
Thanks for getting back so quickly. Job-wise I am also quite interested in timeouts. If you’ve already started looking into this, is there any existing work that you’ve done towards it which might help? If not, can you give some details on the general direction to look in, and any potential pitfalls? I would be glad to take a look, although can’t guarantee to come up with anything useful.

**Comment by djc** [comment]
I believe the `aio::MultiplexedConnection` should avoid corruption of the underlying connection in case of timeouts.

**Comment by vamshiaruru-virgodesigns** [comment]
Hi all, any progress on this? Or any work arounds? I'm new to rust and considering moving one of my services from node.js to rust, and am evaluating what libraries to use.

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/834
https://github.com/redis-rs/redis-rs/pull/833

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/835

**Comment by nihohit** [comment]
Closing as solved.
