### ISSUE TITLE
Getting type inference error on an async block

### ISSUE THREAD

**Issue by dvtkrlbs** [redis-rs/redis-rs#684]
Minimal Reproduction
While I understand that normally PUBLISH command returns the number of clients that have received the message. It is not clear why this type is not hardcoded in the response and example does not specify any type parameters on publish.
```rs
use redis::{AsyncCommands, Client};

#[tokio::main]
async fn main() {
    let client = Client::open("redis://127.0.0.1").unwrap();
    let conn = client.get_async_connection().await.unwrap();

    let worker = async { conn.publish("test", "test").await.unwrap() };
}
```

```
error[E0698]: type inside `async` block must be known in this context
 --> src/main.rs:8:31
  |
8 |     let worker = async { conn.publish("test", "test").await.unwrap() };
  |                               ^^^^^^^ cannot infer type for type parameter `RV` declared on the associated function `publish`
  |
note: the type is part of the `async` block because of this `await`
 --> src/main.rs:8:54
  |
8 |     let worker = async { conn.publish("test", "test").await.unwrap() };
  |                                                      ^^^^^^

For more information about this error, try `rustc --explain E0698`.
error: could not compile `redis-example` due to previous error                                                                        ^^^^^^
```
I am using
```toml
redis = { version = "0.21.6", features = ["tokio-comp"] }
tokio = { version = "1.21.1", features = ["full"] }
```

**Comment by dvtkrlbs** [comment]
I solved this by using the lower level command system and manually passing the connection type and the output type as i64. But I don't know what to pass as the second parameter on the higher level publish function because it takes 3 parameters.

**Comment by jaymell** [comment]
You need to include a type for the return value, even if you don't actually need the return value. So something like this should work for you:

```
    let worker = async { let _: i32 = conn.publish("test", "test").await.unwrap(); };
```

**Comment by djc** [comment]
I like to spell it `conn.publish::<_, _, i32>()`, but yeah, that should do the trick.

**Comment by alekspickle** [comment]
Does it really necessary? Any plans to fix it, or is it a desired behavior?

**Comment by the-a-man-006** [comment]
Yes, this error seems unnecessary and results in ugly statements needlessly qualifying the type parameters; please fix this...
