### ISSUE TITLE
question: changelog 0.21.6

### ISSUE THREAD

**Issue by giraffate** [redis-rs/redis-rs#688]
Is this changelog for 0.21.6?
https://github.com/redis-rs/redis-rs/blob/0.21.x/CHANGELOG.md#0215-2022-01-10

It isn't included in main branch: https://github.com/redis-rs/redis-rs/blob/main/CHANGELOG.md
I tried to create a PR for it but couldn't find the branch policy.

**Comment by djc** [comment]
Huh, yeah, I must have missed that. If you can fix it on the branch, that would be great, we can merge the branch into main later.

**Comment by giraffate** [comment]
Thanks! I created https://github.com/redis-rs/redis-rs/pull/689
