### ISSUE TITLE
ConnectionManager misaligns subsequent commands when `pipe()` has wrongtype commands

### ISSUE THREAD

**Issue by kvcache** [redis-rs/redis-rs#698]
# Description
## Observed
When you use a ConnectionManager and have a WRONGTYPE-destined command in the pipe, the following commands in the pipe get vended out to the following commands using the connection.

## Expected
When you use a ConnectionManager and have a `pipe()` that has any result combination, the commands in that pipe are drained before the expression is completed - or at least the previous failed commands' results are not observable by subsequent commands.

## A little exposition
While obviously this repro is naive, sometimes values in the wild are not what you expect them to be. However, by leaving the connection in a broken/misaligned state the following commands are always wrong which is potentially catastrophic. Consider:
* fetch a configuration blob and then a thumbnail for user A in a pipe
* then fetch just a thumbnail for user B in a separate usage of the ConnectionManager

If User A's configuration blob isn't exactly right then user B gets user A's thumbnail!

### What I'm doing
I'm using `bb8`'s connection manager. It (by default) does a PING and looks for a PONG on connection checkout (tbh i'd rather pay that cost on connection return and might pr a configuration for it), which will resist (though not necessarily eliminate) the misalignment risk.

### Other stuff I experimented with
By editing the macros in `aio` I was able to tease the repro to work, though I only tried reconnecting more aggressively than is likely to be intended.
```rust
/// Handle a command result. If the connection was dropped, reconnect.
macro_rules! reconnect_if_dropped {
    ($self:expr, $result:expr, $current:expr) => {
        if let Err(ref e) = $result {
            if e.is_connection_dropped() {
                $self.reconnect($current);
            }
        }
    };
}

/// Handle a connection result. If there's an I/O error, reconnect.
/// Propagate any error.
macro_rules! reconnect_if_io_error {
    ($self:expr, $result:expr, $current:expr) => {
        if let Err(e) = $result {
            $self.reconnect($current);
            return Err(e);
        }
    };
}
```

# How to repro
Start redis listening on localhost:6379 like `docker run -p 6379:6379 --rm redis`

`cargo.toml`
```toml
[package]
name = "bugreport"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
redis = { version = "0.22.1", features = ["tokio-comp", "connection-manager"] }
```

`main.rs`
```rust
use redis::AsyncCommands;

#[tokio::main]
async fn main() {
    let mut connection_manager = redis::aio::ConnectionManager::new(
        redis::Client::open("redis://localhost:6379").unwrap()
    ).await.unwrap();

    // Put a list in redis
    let _: () = connection_manager.lpush("key", "value").await.unwrap();

    // Execute a pipe with a wrongtype at the beginning
    let _: Result<(String, usize), redis::RedisError> = redis::pipe()
        .get("key") // WRONGTYPE
        .llen("key")
        .query_async(&mut connection_manager)
        .await;

    // And now the connection is in a broken state
    let _: Vec<String> = connection_manager.lrange("key", 0, -1)
        .await
        .expect("should be able to get a list but instead I get the llen");
}
```

Observe:
```
thread 'main' panicked at 'should be able to get a list but instead I get the llen:
 Response was of incompatible type: "Response type not vector compatible."
 (response was int(1))', src/main.rs:20:72
```

**Comment by jaymell** [comment]
Thank you for reporting the issue and the steps to reproduce. We've recently encountered a similar issue in a different context but had not been able to reproduce consistently, so this is greatly appreciated.

**Comment by jaymell** [comment]
The issue is occurring in the underlying `MultiplexedConnection`, which, as @kvcache noticed, is not properly handling subsequent requests in the pipeline if one command fails. I've raised a [tentative PR](https://github.com/redis-rs/redis-rs/pull/699), but it's a bit rushed, so want to do some further investigation and solicit feedback before merging. 

Thanks again for reporting the issue here. I recently noticed this issue, which is obviously very concerning, under heavy load using the [redis-cluster-async fork](https://github.com/redis-rs/redis-cluster-async) but was not able to reproduce or get to a root cause.

**Comment by kvcache** [comment]
@jaymell Thanks for looking into this so quickly; I also appreciate that you even took the time to re-express the repro as a regression test :heart:

The shape of the solution seems reasonable on the surface (keep accumulating responses until you get them all) but I'm not terribly deep in this crate. Looking forward to watching the PR!
