### ISSUE TITLE
redis-sentinel

### ISSUE THREAD

**Issue by omer-shtivi** [redis-rs/redis-rs#703]
Hello,
Is there a plan to support redis with Sentinel in order to discover which replica is the master?
https://redis.io/docs/management/sentinel/#:~:text=Configuration%20provider.%20Sentinel%20acts%20as%20a%20source%20of%20authority%20for%20clients%20service%20discovery%3A%20clients%20connect%20to%20Sentinels%20in%20order%20to%20ask%20for%20the%20address%20of%20the%20current%20Redis%20master%20responsible%20for%20a%20given%20service.%20If%20a%20failover%20occurs%2C%20Sentinels%20will%20report%20the%20new%20address.

**Comment by djc** [comment]
There is no plan that I am aware of, though @jaymell may have better context on this.

**Comment by omer-shtivi** [comment]
Thanks @djc  for the response.
If I will contribute the code myself, will you accept it?
Looks like a very common deployment module, and I would like to get rid of our haproxy which seams is causing us troubles.

**Comment by nihohit** [comment]
Sentinel support was added.
