### ISSUE TITLE
test function `test_object_commands` of `test_basic.rs` is failed intermittently

### ISSUE THREAD

**Issue by 0xWOF** [redis-rs/redis-rs#713]
https://github.com/redis-rs/redis-rs/blob/c10919a02d329f267298651d6ce3648fc741915c/redis/tests/test_basic.rs#L1109-L1142

In this code, result of `con.object_idletime` is mostly 0.
But when CI machine is slow, result of `con.object_idletime` can be 1 or even more.

I think there are two options.
- option 1: remove `con.object_idletime` assert.
    - consider `con.object_idletime` as not testable because result of `con.object_idletime` is affected by CI performance
- option 2: change assert to result of `con.object_idletime` is equal or less than 1.
    - this patch can reduce possibility of CI failure

**Comment by djc** [comment]
Seems reasonable to try option 2 for now and see how it goes.
