### ISSUE TITLE
[Feature Request] Support user-specified routing rules for custom commands

### ISSUE THREAD

**Issue by joehu888** [redis-rs/redis-rs#732]
The cluster feature lacks the ability to support user-specified routing rules for custom commands. For example, I have a Redis module M that provides a command called M.FOO. I'd like M.FOO to be executed on all masters. We cannot do that today without forking out redis-rs and modifying cluster_routing.rs, because the routing rules are hard-coded: https://github.com/redis-rs/redis-rs/blob/main/redis/src/cluster_routing.rs#L24. Since M.FOO is a new command "unknown" to cluster_routing.rs, it falls into the default routing rule, which is not what I want.

So, I'm proposing a new feature that extends the library to support user-specified routing rules for custom commands.

Just as an example, one way to do it is to decorate the command object with a routing rule. e.g.,

    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;
    let rs = redis::cmd("M.FOO").arg("arg1").arg("arg2").set_routing(Some(RoutingInfo::AllMasters)).query(&mut con);

The existing code RoutingInfo::for_routable will be modified to call cmd.get_routing. If the value is None, then fall back to the default routing rule.

**Comment by djc** [comment]
Sounds reasonable. I don't have much cluster experience, @jaymell any thoughts?

**Comment by jaymell** [comment]
Yes in general I think this sounds like a good idea.

**Comment by joehu888** [comment]
Thanks for the feedback. I'd like to work on it and submit a PR.

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/899

**Comment by jaymell** [comment]
I think we can safely mark this completed now that #899 has been merged.
