### ISSUE TITLE
Remove “tokio” mention from name of runtime agnostic `Client::get_tokio_connection_manager()`

### ISSUE THREAD

**Issue by LeoniePhiline** [redis-rs/redis-rs#737]
Connection manager appears to be runtime agnostic.

**Comment by LeoniePhiline** [comment]
I would prepare a PR, but I am not sure what you would prefer:

- Add a method with an agnostic name (`Client::get_connection_manager()`), which does the same? (Deprecating `Client::get_tokio_connection_manager()`)
- Or straight-out renaming `Client::get_tokio_connection_manager()` to `Client::get_connection_manager()`? This would of course be a breaking change.

**Comment by djc** [comment]
Probably makes sense to add the agnostic name while deprecating the tokio name?

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/pull/913
