### ISSUE TITLE
How to set timeout when executing redis:: cmd command

### ISSUE THREAD

**Issue by baoyachi** [redis-rs/redis-rs#738]
E.g:

```diff
let mut conn = client.get_async_connection().await.unwrap();
+ let val: usize = redis::cmd("MEMORY").arg("USAGE").arg("foo_key").query_async(&mut conn).await.unwrap();
```

So, how to control `redis::cmd` command timeout?

**Comment by djc** [comment]
You can wrap the future in `tokio::time::sleep()` or equivalent for your runtime of choice.

**Comment by dinhani** [comment]
`tokio::time::timeout` or `tokio::time::timeout_at`

**Comment by djc** [comment]
Sorry, yes `timeout`.
