### ISSUE TITLE
Feature request: Automatic serialization and deserialization of objects to JSON

### ISSUE THREAD

**Issue by daniel7grant** [redis-rs/redis-rs#740]
Redis.rs already supports some JSON-specific commands (with `serde` and `serde-json`), but there is no built-in way to `get` and `set` non-primitive structures. For example, even saving and reading a simple `struct` is impossible without serializing and deserializing manually:

```rust
#[derive(Serialize, Deserialize)]
struct Address {
    street: String,
    city: String,
}

fn main() -> Result<()> {
    let addr = Address { street: "street".to_string(), city: "city".to_string() };
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;
    // Set in Redis
    let serialized_addr = serde_json::to_string(&addr)?;
    con.set("address", serialized_addr)?;
    // Get from Redis
    let get_addr: String = con.get("address")?;
    let deserialized_addr: Address = serde_json::from_str(&get_addr)?;
}
```

If we want to allow to get and set this as a parameter, another way is to implement the two traits `FromRedisValue` and `ToRedisArgs` respectively. However, this is non-trivial, to say the least. It would make for a better developer experience if Redis.rs could make the implementation for these automatic.

There are two ways to do this, the easiest would be to implement `FromRedisValue` and `ToRedisArgs` for every type that implement `Deserialize` and `Serialize` (`impl <T>FromRedisValue for T where T: Deserialize`). From a library user perspective, this would be the simplest, as one would only have to derive the serde traits. However this would create some collateral damage, because Rust doesn't ([yet](https://rust-lang.github.io/rfcs/1210-impl-specialization.html)) have trait specialization, so it would collide with all types that `Serialize` is implemented for (including all numerics, strings and `Vec<u8>`).

Probably a more standard way would be to provide a derive macro (`#[derive(FromRedisValue, ToRedisArgs)]`). This would generate a default implementation, that would use `serde_json` to serialize the struct to JSON (probably a safe default for most applications).

A naive implementation of this could be this (mind the panic in the deserialization):

```rust
impl FromRedisValue for Address {
    fn from_redis_value(v: &Value) -> RedisResult<Self> {
        match *v {
            Value::Data(ref bytes) => match serde_json::from_slice(&bytes) {
                Ok(t) => Ok(t),
                Err(_) => invalid_type_error!(v, "Response type not JSON serializable."),
            },
            _ => invalid_type_error!(v, "Response type not JSON serializable."),
        }
    }
}

impl ToRedisArgs for Address {
    fn write_redis_args<W>(&self, out: &mut W)
    where
        W: ?Sized + RedisWrite,
    {
        let mut buf = serde_json::to_vec(&self).unwrap(); // Maybe it shouldn't panic?
        out.write_arg(&buf)
    }
}
```

What do you think about this feature? I would love to contribute to this, as much as I can.

**Comment by djc** [comment]
I'm currently not inclined to include this functionality in this crate. It seems relatively opinionated functionality that could just as well be implemented in a separate crate (a procedural macro crate that generates `FromRedisValue` and `ToRedisArgs` implementations using serde_json). In my view, this project already has a maintenance backlog and a pretty limited supply of maintainer attention, so I don't think this would be a good addition at this time.

**Comment by daniel7grant** [comment]
Thanks for the answer! I understand your point and I respect it if you don't want to include it in your crate.

My motivation for this feature request involves two important patterns. One is probably the most ubiquitous usage of Redis: **caching**. It is a realistic expectation to be able to *just put* structs into the cache and then *just get them back* as the same struct (e.g. database cache, API cache). Automatic serialization would make this use-case very simple. The other is the emerging pattern of using Redis as a main **database**. This usually involves putting structs into Redis with `model:id`. These are usually serialized into RedisJSON and updated with `JSON.*` operations. I think this is another case where automatic JSON serialization would be useful, so we could persist data with simple `get` and `set` operations, without a need for a separate data mapping layer.

I understand your concerns about maintaining this in the main crate, but I think it makes the most sense to distribute the derive macros with the corresponding traits. If you are low on maintainer time, I would love to contribute with a PR (hopefully it is simply the above code snippet wrapped into a proc macro). And if you still think it wouldn't be a good fit for this crate, I could probably implement it in a separate crate.

**Comment by djc** [comment]
We do already have support for RedisJSON commands, did you find that already?

Just reviewing the PR is not the only issue, maintaining this means tracking the additional complexity and potential coherence over time basically forever. Feel free to implement it in a separate crate -- I know from experience that creating a wrapper type over a Redis connection is a very useful pattern.

**Comment by daniel7grant** [comment]
Yep, I checked out the RedisJSON commands, but it was kind of messy for me. It was a mix of Redis quirks (e.g. `JSON.*` results are wrapped in brackets) and Rust quirks (Vec and String have alternate ToRedisValue implementations, so it parses to weird things). I like that the documentation notes in a comment that JSON commands responses "will always be a Vec", but it is very little information for someone who is not in the know about RedisJSON protocol. I would expect my library to figure out `JSON.STRLEN` to return a number, not a stringified `Vec<u32>`.

I looked at different crates (e.g. [redis-utils](https://crates.io/crates/redis_utils) and [redis-derive](https://crates.io/crates/redis-derive)), but I didn't really like their solutions, so I ended up writing my own crate: [redis-macros](https://crates.io/crates/redis-macros). I eventually implemented the [derive macros](https://github.com/daniel7grant/redis-macros#simple-usage) for `FromRedisValue` and `ToRedisArgs`, so one can simply derive and use it:

```rust
#[derive(Serialize, Deserialize, FromRedisValue, ToRedisArgs)]
struct User { ... }

con.set("user", User { ... })?;
let stored_user: User = con.get("user")?;
```

For the RedisJSON commands, I ended up implementing [another type `Json`](https://github.com/daniel7grant/redis-macros#json-wrapper-with-redisjson), which can unwrap the brackets in the RedisJSON output:
```rust
let Json(id): Json<u32> = con.json_get("user", "$.id")?;
```

With this, you can extract most values in a simple way without manually parsing JSON (similarly how you can pass structs to `json_set` and `redis-rs` will serialize it for you). It even works with `String`s and `Vec`s.

Thanks for your help, it was fun to implement my own crate. Feel free to close this issue, I hope it will point folks in the right way if they need similar JSON machinations.

**Comment by daniel7grant** [comment]
I created the https://github.com/redis-rs/redis-rs/pull/769 pull request with explanations and references to the `redis-macros` crate. Feel free to remove the references if I went too overboard, I just wanted to include the crate where I would look for a similar functionality. I will soon improve he docs.rs documentation of the `redis-macros` crate too.
