### ISSUE TITLE
Can anyone provide an example on How do I run the scan command in cluster mode.

### ISSUE THREAD

**Issue by sunxingsong** [redis-rs/redis-rs#747]

**Comment by djc** [comment]
No, sorry. There are plenty of other venues you can ask for help (users.rust-lang.org, Reddit threads, StackOverflow) though you should likely ask a more specific question showing what you have tried so far and why it doesn't work.

This repository is intended mainly for maintenance of the core redis project and unfortunately we don't have much time/energy to spend on support for open questions like this.
