### ISSUE TITLE
set_multiple not obviously == MSET

### ISSUE THREAD

**Issue by randomairborne** [redis-rs/redis-rs#763]
There is no way to MSET override using this library- the Commands mset_nx cannot replace, and the args() method on redis::Cmd does not support lists of tuples, which would be much nicer.

**Comment by djc** [comment]
What about [`set_multiple()`](https://docs.rs/redis/latest/redis/trait.Commands.html#method.set_multiple)?

**Comment by randomairborne** [comment]
Oh, I completely missed that. Would be cool if it was documented as mset, so it was easier to search for. Sorry.

**Comment by djc** [comment]
If you'd be able to submit a documentation improvement as a PR, that would be great!

**Comment by djc** [comment]
I'd be on board with adding `mset()` and deprecating `set_multiple()` in favor of it.

**Comment by randomairborne** [comment]
I’d ditto this. I feel like the functions should follow redis naming.

**Comment by djc** [comment]
@randomairborne want to change up your PR? Sorry for the churn!

**Comment by randomairborne** [comment]
PR changed up

**Comment by jaymell** [comment]
Fixed by #766
