### ISSUE TITLE
Is PubSub still a WIP? If so, what are the features that are yet to be implemented?

### ISSUE THREAD

**Issue by debugger22** [redis-rs/redis-rs#770]
This is not a valid issue but I failed to find any discussion forum to ask this question.

**Comment by liyuntao** [comment]
+1 for the feature

**Comment by Preen** [comment]
+1

**Comment by jaymell** [comment]
Sorry, the documentation for Pubsub is so old as to be confusing. I will try to get this updated soon and am hoping we will have additional functionality in the not-too-distant future.

**Comment by nihohit** [comment]
pubsub can be considered complete.
