### ISSUE TITLE
ZRANGE does not show any data

### ISSUE THREAD

**Issue by chungquantin** [redis-rs/redis-rs#771]
## Issue
I am trying to use ZRANGE to get data from sorted set but it does not show anything. Even though my key is correct, the return is still empty. You can see the below image which has the data return from the console using `redis-cli` and the data return from my code using `redis-rs`. I am not sure if there is anything wrong with my code. 

<img width="1048" alt="Screen Shot 2023-02-06 at 16 58 59" src="https://user-images.githubusercontent.com/56880684/217097232-5e5c49de-3ae1-46da-b6b2-5f75ea6d0ba1.png">

## Context
Here is the version of `redis-rs` that I am using
```toml
redis = { version = "0.22.3", optional = true, features = ["tokio-comp"] }
```

**Comment by djc** [comment]
I'm pretty sure you shouldn't be stuffing `&[id, "0".to_string(), "-1".to_string()]` in one `arg()` call -- use one `arg()` call per argument instead (which would also avoid the string conversions for numbers).

**Comment by chungquantin** [comment]
The problem is solved by identifying the correct Rust type for `recent_tweets_id`. Above I declare `recent_tweets_id : () = ...` which returns a void. It should be `recent_tweets_id: Vec<String> = ...` because `ZRANGE` returns a list of string
