### ISSUE TITLE
Redis pipeling return a tuple is not a best practice 

### ISSUE THREAD

**Issue by chungquantin** [redis-rs/redis-rs#776]
## Current issue
Using Redis pipeline for querying data returns a tuple which is not a best practice. The problem can be obviously demonstrated by this below code. 
```rs
// Return void ()
let data = redis::pipeline().cmd("LRANGE").arg("...").cmd("LRANGE").arg("...").execute(connection);
// Return only one vector of string
let data : (Vec<String>) = redis::pipeline().cmd("LRANGE").arg("...").cmd("LRANGE").arg("...").execute(connection);
// Return only two vectors of string
let data : (Vec<String>, Vec<String>) = redis::pipeline().cmd("LRANGE").arg("...").cmd("LRANGE").arg("...").execute(connection);
```
In that way, if user does not declare the type, there will be nothing returns from the request. Same error happened in this ticket: https://github.com/redis-rs/redis-rs/issues/771

One more limitation of this design is that if I want to build a Redis pipeline to `GET` based on the dynamic given number, there's no way I can do that because the lib requires me to identified data in the tuple. Can see more details on Rust forum: https://users.rust-lang.org/t/how-to-define-tuple-type-repeatedly-with-a-dynamic-size-provided/88891

## Suggestion
The api `cmd` should identify the right type of Redis command. For example, `LRANGE` must be `Vec<String>` or `GET` must be `String`. Even though I know it is a bit hard to do that due to the design of Rust type system.

**Comment by djc** [comment]
The entire design of the library is predicated upon parametrization with return types. I'm not sure it's realistic to change this within this library, and the design is definitely flexible in a way that your proposed design would not be (for example, support for deserializing into a type defined by the caller/in a different crate).

**Comment by nihohit** [comment]
This change would break backwards compatibility. Closing, unless a good enough reason will be raised.
