### ISSUE TITLE
Wierd signature of StreamId::contains_key

### ISSUE THREAD

**Issue by Ayush1325** [redis-rs/redis-rs#781]
I was wondering why [`StreamId::contains_key`](https://github.com/redis-rs/redis-rs/blob/0d0133ce43a65e4835645887f6cad1c73857b194/redis/src/streams.rs#L456) has `&&str` for key type. 

Is it just for backward compatibility reasons since it will be a breaking change? Maybe it should be removed in the next major release?

**Comment by djc** [comment]
I agree that this is weird. Please submit a PR, we can see when we can merge it.
