### ISSUE TITLE
`CLUSTER SLOTS` deprecated

### ISSUE THREAD

**Issue by jaymell** [redis-rs/redis-rs#787]
Consider using `CLUSTER SHARDS` instead

**Comment by nihohit** [comment]
@barshaul investigated this, and while the command is indeed deprecated, it's unlikely to be removed, and it's easier to parse than `CLUSTER SHARDS`, since all the results return in the same order regardless of the queried node. The additional info in `CLUSTER SHARDS` is also not very relevant.
