### ISSUE TITLE
Does the feature "cluster" support async?

### ISSUE THREAD

**Issue by 2ico** [redis-rs/redis-rs#800]
I'm not able to use .query_async() with ClusterConnection in version 22.3

**Comment by jaymell** [comment]
Async clustered support is pending and there are other issues tracking it. If you need something immediately you can use [redis-cluster-async](https://github.com/redis-rs/redis-cluster-async), on which the pending mainline support is based.

**Comment by 2ico** [comment]
Ok thank you
