### ISSUE TITLE
Unable to parse Inline Commands

### ISSUE THREAD

**Issue by Will-Low** [redis-rs/redis-rs#801]
Per the RESP protocol spec, Redis is able to parse/handle commands in the "[Inline Command](https://redis.io/docs/reference/protocol-spec/#inline-commands)" format. However, when trying to parse these commands using the `redis::Parser`, parsing fails.

For example, this test will fail:
```
#[test]
fn when_parsing_an_inline_command_then_parsing_is_successful() {
    let inline_command = b"PING\r\n";
    assert!(parse_redis_value(inline_command));
}
```
The error message in question is: `` parse error: Parse error at 1
Unexpected `73`
Unexpected `80` ``

Note: The `inline_command` bytes above were generated using the `telnet` example at the above link and verified using Wireshark.

**Comment by jaymell** [comment]
Hi. You're correct that the parser does not support the format you're trying to use. Since this is a higher-level library, I'm not sure this is something we'd want to support. Can you explain your use case a bit?

**Comment by jaymell** [comment]
Technically speaking you can parse ingoing and outgoing with no problem, it's just your outgoing command is technically not in correct format. The "inline" format you reference is kind of a shortcut that's supported for easier command line usage.
