### ISSUE TITLE
Proposal: Allow Value to contain errors

### ISSUE THREAD

**Issue by philippgl** [redis-rs/redis-rs#805]
I am sending multiple commands in a pipeline and some of them might return an error. Because `Value::Bulk(Vec<Value>)` cannot contain errors, I get the first error in `Bulk` and all other values are gone.

Example
As response to 
```
PING
SET foo bar
EVALSHA aaaaaa
```
i get something like:
```
NOSCRIPT No matching script. Please use EVAL.
```
but I want to get something like:
```
PONG
Ok
NOSCRIPT No matching script. Please use EVAL.
```

I currently cannot get `Value::Bulk`-Replies with errors and the RedisError currently contains server/connection errors as well as errors sent by the server.

I have issue #746 as well (see also https://github.com/redis-rs/redis-rs/issues/366#issuecomment-673630807) and IMHO the cleanest solution would be to extend the Value enum, so it can contain an error from the server and add something like ~~`.wrap()` (or `.ok()`) to "split" the `Value` as it is now into a `RedisResult<Value>`. In addition to pipelines this might also occur in lua scripts. I also provide `.first_error()` and `map_value_error()` in an extension trait for RedisResult. Calling `.first_error` converts an `Ok(Value)` to an Err(RedisError), if it contains a nested `Value::Error` somewhere inside (like in the current implementation) and `map_value_error()` only maps an `Ok(Value::Error)` to `Err(RedisError)`, but keeps nested errors.

In the lua script case, it might even make sense to complete the script and still return a Value::Bulk, which contains an error (among other things).

The new enum variant would look like Value::Error(ErrorKind, String) with String containing the current detail.

I can help with this, because I need to see the errors in my pipeline on the client side.

Maybe I could automatically apply this `wrap` after the parsing. If the Error is not inside a Bulk, I do not loose Information.

Transactions in redis usually return `ok` for the `multi` and `queued` for each command in the pipeline, unless there is an error in the queued commands. Then the error is returned instead of the queued and the result for the exec becomes something ExecAbortError.  In the current implementation, the returned values for the normal commands are ignored and the result of the exec is returned, unless there is an error and then the first error is returned instead. As i now ignore all errors ignored by the ` req_packed_commands`, I only get the `ExecAbortError` instead of the reason, why it aborted.

**Comment by jaymell** [comment]
My concern here is that this would be a dramatic change to the library and its API. Could we not accomplish the goal of better surfacing/handling of pipeline errors by modifying `ConnectionLike::req_packed_commands` to return `Vec<RedisResult>`? In my view, this would be a much less intrusive change. Any thoughts?

**Comment by philippgl** [comment]
I already tried to solve the returned value in different ways and this was the only way I could handle nested values in a sane way.

If an error is at the top level, I convert it into a `RedisResult`, so this proposal only affects `Value::Bulk` (with nested errors).

My main concern with the `ConnectionLike::req_packed_commands` returning the Vec<RedisResult> is, that this only handles Error on the next level and does not really match the structure of the redis reply. The redis bulk reply could contain a nested bulk reply, which contains an Error. As the `Vec<RedisResult>` does not match the redis reply, the code gets a lot more complicated.

I also had concerns with backward compatibility, but the new Value::Error is actually quite rare, as the redis usually replies with Nil, if you try to read an unset value and my current implementation only uses the new `Value::Error`, if it is nested.

Regarding backwards compatibility, this breaks the `test_pipeline_with_err` and `test_pipeline_transaction_with_errors`. The first I fixed by adding calling my new `.first_error()` in the test, but the intended way would be to expect the returned value. For the `test_pipeline_transaction_with_errors`, I get the `ExecAbortError` now instead of the first error that occurred. This should probably be fixed in the Pipeline struct, but that would require even more changes. In the example above the redis replies with something like:

```
QUEUED
QUEUED
NOSCRIPT No matching script. Please use EVAL.
ExecAbortError
```

If the Pipeline would set the offset to 0, it could return something like:
```
ExecAbortError
ExecAbortError
NOSCRIPT No matching script. Please use EVAL.
```
(or even just change the test to expect `ExecAbortError` or call `.first_error()` to return the first error as before, but currently i really ignore offset values)

So the transactional pipelines are more broken than i wanted to break them, but the redis documentation also does not really recommend them anyway:
> Something else to consider for transaction like operations in redis are [redis scripts](https://redis.io/commands/eval) which are transactional. Everything you can do with a Redis Transaction, you can also do with a script, and usually the script will be both simpler and faster.

And this matches my experience as you cannot react to issues in the middle of a transactional pipeline, I find their use very limited.

**Comment by jaymell** [comment]
> My main concern with the ConnectionLike::req_packed_commands returning the Vec is, that this only handles Error on the next level and does not really match the structure of the redis reply. The redis bulk reply could contain a nested bulk reply, which contains an Error. As the Vec<RedisResult> does not match the redis reply, the code gets a lot more complicated.

Pardon my ignorance here, but can you give me an example of such a scenario, i.e., when we might get a response from the server with this structure?

**Comment by nihohit** [comment]
implemented in https://github.com/redis-rs/redis-rs/pull/1093
