### ISSUE TITLE
Where is my librejson.so?

### ISSUE THREAD

**Issue by fantas1a** [redis-rs/redis-rs#815]
Hi,

I need to specify the absolute path of REDIS_RS_REDIS_JSON_PATH before any compiling or installation. But I do not have the librejson.so file. May I know if there are any pre-requirements for this? Do I need to install a Redis first to have the librejson.so file?

Thank you very much!

**Comment by jaymell** [comment]
I'm not clear exactly what you're trying to do. If you're trying to use this crate for the "RedisJSON" functionality, you'll need to go run Redis w/ that module loaded. There are instructions for doing so here: https://redis.io/docs/stack/json/

**Comment by nihohit** [comment]
closing as answered.
