### ISSUE TITLE
Documentation incorrectly states aio is enabled by default

### ISSUE THREAD

**Issue by dbrenot-pelmorex** [redis-rs/redis-rs#822]
When trying to use redis::AsyncCommands, I need to add aio to the features list. While this is fine, the documentation on crates.io states this is enabled by default. Please update the documentation to eliminate confusion.

Thanks!

**Comment by dbrenot-pelmorex** [comment]
Correction, is enabled, but "tokio-comp" or the other runtime needs to be enabled. Would be good to have this mentioned in the cargo docs rather than just in the git docs.

**Comment by jaymell** [comment]
Can you post a link or snippet of text indicating what you're referring to? I'm not following.

**Comment by dbrenot-pelmorex** [comment]
![snip1](https://user-images.githubusercontent.com/120058075/229683810-10f5879a-bca2-406e-99f1-8d8aaf48eb94.png)
![snip2](https://user-images.githubusercontent.com/120058075/229683824-1d0b9a26-e6e1-4928-a8dc-7ad7b31bb616.png)

The first image is from cargo while the second is from this git repository. In order to use async, you need to follow the directions in the second picture. These directions are nowhere to be found on the cargo docs, so there was a bit of confusion when setting it up today.

**Comment by dbrenot-pelmorex** [comment]
Sorry just to note, the documentation still doesn't mention the requirement on tokio-comp/async-std-comp. Without those the async won't work, and this is only mentioned in the git docs
