### ISSUE TITLE
cluster async pipeline supporting keys that belongs to different nodes

### ISSUE THREAD

**Issue by hellojaewon** [redis-rs/redis-rs#840]
Hi, I'm in difficulty in using async cluster with pipeline.

https://github.com/redis-rs/redis-rs/blob/5c81077c63aa30afc523e7fcb1842fa900ae364a/redis/tests/test_cluster_async.rs#LL83C10-L83C10

As above comment said, it seems to currently cluster async pipeline does not support that.
Even, test cluster async uses redis::pipe instead of redis::cluster::cluster_pipe that has limitation for some [commands](https://github.com/redis-rs/redis-rs/blob/5c81077c63aa30afc523e7fcb1842fa900ae364a/redis/src/cluster_pipeline.rs#L51). Therefore, when I use some commands that are not allowed in cluster pipeline it works anyway.
However, if I compose multiple keys that belong to different nodes in the same pipe it returns an MOVED error.

When I try to use cluster_pipe(), there is no async interface in cluster_pipeline.rs so that was not possible.
I think we need async interfaces in cluster_pipeline.rs.

Does anybody know about this? or any other help to resolve it?

**Comment by jaymell** [comment]
You are correct that there is currently no async support for the cluster-pipeline feature. As you mentioned, you can use `redis::pipe` with a cluster-client, provided that you're able to ensure beforehand that the commands you wish to pipeline are all going to same node, as there is no support for handling multi-node requests.

**Comment by nihohit** [comment]
this issue was fixed in https://github.com/redis-rs/redis-rs/pull/986 - now the pipeline will return a cross slots error in such situations.
