### ISSUE TITLE
ConnectionManager power example

### ISSUE THREAD

**Issue by alekspickle** [redis-rs/redis-rs#841]
I am trying to test connction manager. Am I doing something stupid and I should go get a pool or is this a valid showcase for a manager?

```
      use redis::Client;
      use futures::future;
    
      async fn run() {
         let client = Client::open("");
         let manager = client.get_tokio_connection_manager().await.unwrap();
         let futs = (0..50).map(|i| async {
             let con = manager.clone();
             let key = format!("key-{i}");
             let val = format!("value-{i}");
             let _: () = con.set(key, val).await.unwrap();
             Ok(())
         });
         let _: Result<Vec<()>> = future::try_join_all(futs).await;
         let futs = (0..50).map(|i| {
             let con = manager.clone();
             let key = format!("key-{i}");
             conn.get(key)
         });
         let vals: Result<Vec<String>> = future::try_join_all(futs).await;
         let vals = vals?;
    
         Ok(())
      }

```

**Comment by dbrgn** [comment]
From what I can tell, this looks valid.

To quote from the docs:

> A `ConnectionManager` is a proxy that wraps a [multiplexed connection][multiplexed-connection] and automatically reconnects to the server when necessary.
>
> Like the [`MultiplexedConnection`][multiplexed-connection], this manager can be cloned, allowing requests to be be sent concurrently on the same underlying connection (tcp/unix socket).

This means all commands will be sent to the same connection. They are processed sequentially by Redis, but that's always the case since Redis is single-threaded.

The docs also list some more notes on how exactly `ConnectionManager` behaves: https://docs.rs/redis/latest/redis/aio/struct.ConnectionManager.html

**Comment by alekspickle** [comment]
I'm having troubles with type inference for redis calls in that closures though:
```

the trait bound `Result<_, _>: FromRedisValue` is not satisfied
    --> src/redis.rs:178:12
     |
22   |        con.get(key).await?
     |            ^^^ the trait `FromRedisValue` is not implemented for `Result<_, _>`

```

**Comment by jaymell** [comment]
You need to indicate to these functions the return type. One option is something like this:
```
con.get::<String>(key).await?
```

**Comment by alekspickle** [comment]
Then it would just complain that only 1 of 3 generics are specified
```

error[E0107]: this associated function takes 2 generic arguments but 1 generic argument was supplied

19   |        con.get::<String>(key);
     |                      ^^^   ------ supplied 1 generic argument
     |                      |
     |                      expected 2 generic arguments
     |
note: associated function defined here, with 3 generic parameters: `K`,  `RV`
    --> /home/pickle/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.23.0/src/commands/mod.rs:86:8
     |
66   | / implement_commands! {
67   | |     'a
68   | |     // most common operations
86   | |     fn get<K: ToRedisArgs>(key: K) {
     | |        ^^^ -               -
1861 | |     }
1862 | | }
help: add missing generic arguments
19   |        con.get::<String, V, RV>(key, val);

```

**Comment by alekspickle** [comment]
I do get to the borrowing errors of `con` if I specify something like `<String,String,String>` for example, but this seems dumb
