### ISSUE TITLE
Strange issue with tokio::select and MultiplexedConnection

### ISSUE THREAD

**Issue by bbaldino** [redis-rs/redis-rs#851]
After working around [this issue](https://github.com/redis-rs/redis-rs/issues/848) by using MultiplexedConnection, I'm still seeing some odd behavior.  I've got a small repo [here](https://github.com/bbaldino/redis_tokio_test/tree/a9961090e7497f3815b5e3a2cde5ab291f97512d) that illustrates the issue.  

What I'm trying to do:
A worker calls `tokio::select` in a loop.  There are two branches: [one is the receive side of a `tokio::sync::mpsc::channel`](https://github.com/bbaldino/redis_tokio_test/blob/a9961090e7497f3815b5e3a2cde5ab291f97512d/src/main.rs#L46)  for handling control messages, [the other is a call to `xread_options`](https://github.com/bbaldino/redis_tokio_test/blob/a9961090e7497f3815b5e3a2cde5ab291f97512d/src/main.rs#L60) to do a redis read on a (dynamic) set of streams.  In the [test code](https://github.com/bbaldino/redis_tokio_test/blob/a9961090e7497f3815b5e3a2cde5ab291f97512d/src/main.rs#L143), I:

1. send an "AddSubscriber" control message
2. pause for 1 second
3. send another "AddSubscriber" control message
4. add a redis message to the stream added for the second subscriber
5. --> that message is never read/received

I'd expect there should be 3 calls to XREAD here:
1. After step 1 (when the first "subscriber" is added, the first call to `xread_options` will be made)
2. After step 3 (a second control message breaks out of the select, so after it's handled select will be called again)
3. After step 4 (a redis message breaks out of the select, so after it's handled select will be called again)

But I only end up seeing it called _once_, and I'm not sure why.  Some things--like removing the call to sleep--seem to fix the issue for some reason.  Also, if the message sent is on the _first_ stream, instead of the second, it will be received.

Some example output of `redis-cli monitor`:
In the working scenario:
```
1684881441.252919 [0 172.17.0.1:50734] "XREAD" "BLOCK" "0" "COUNT" "1" "STREAMS" "1786645176" "0"
1684881442.254479 [0 172.17.0.1:50748] "XADD" "1786645176" "*" "data" "hello2"
1684881442.254566 [0 172.17.0.1:50734] "XREAD" "BLOCK" "0" "COUNT" "1" "STREAMS" "1786645176" "2405263214" "0" "0"
1684881442.254958 [0 172.17.0.1:50734] "XREAD" "BLOCK" "0" "COUNT" "1" "STREAMS" "1786645176" "2405263214" "1684881442254-0" "0"
```
In the failing scenario:
```
1684881705.688617 [0 172.17.0.1:33896] "XREAD" "BLOCK" "0" "COUNT" "1" "STREAMS" "3580070946" "0"
1684881706.690166 [0 172.17.0.1:33912] "XADD" "2629257068" "*" "data" "hello2"
```

**Comment by jaymell** [comment]
I'm not sure I totally follow your example, but the likely problem is you're blocking the connection with `XREAD BLOCK 0`, which is unfortunately a commonly encountered issue with blocking commands on multiplexed connections. In a similar situation I've had to set timeouts on the read (i.e., a non-zero duration for `XREAD BLOCK`) to avoid blocking other commands attempting to use the connection.

Other things that might help are having a dedicated connections for the blocking reads and/or using connection pooling.

**Comment by bbaldino** [comment]
Oh, so does `BLOCK 0` not play nicely with async then? The intention was to suspend until a read occurred.

**Comment by jaymell** [comment]
Correct -- `BLOCK 0` blocks the entire connection and is thus best avoided if you need the connection to properly do multiplexing.

**Comment by bbaldino** [comment]
Ok, I don't actually need the connection multiplexing--I've only got this one reader on the connection (I'm using `MultiplexedConnection` due to [this issue](https://github.com/redis-rs/redis-rs/issues/848), but I'm still seeing this problem.  I tried to make the test code as simple as I could, but let me know if there's anything I can clarify--does it repro for you?

**Comment by jaymell** [comment]
It looks to me like things are working as "expected" given the code. The worker blocks reading the first key that's created. The `XADD` is called with the second key, but the worker is still blocked trying to get data on the first key. Does that make sense? Am I missing something?

**Comment by bbaldino** [comment]
I was expecting that the read would be cancelled when the second "subscriber" is added: the select should cancel all other branches, from what I understand.  Then it will re-enter the select with a new call to read, which would try reading from both the first and second streams, and should then read the message.

**Comment by jaymell** [comment]
Ok, I see where the confusion is, but I'm not sure that there's anything "wrong" happening here. We don't intend for the underlying connection to the server to be terminated when the cancellation happens, which I think would be the only "clean" way to terminate the blocking call..

**Comment by bbaldino** [comment]
Ok, so it sounds like `MultiplexedConnection` just isn't compatible with `tokio::select` then?  For that to be the case, I believe the futures need to be stateless/able to be cancelled cleanly if another branch finishes before it?

**Comment by nihohit** [comment]
`MultiplexedConnection` is compatible with `tokio::select`, it's just that the requests can't be cancelled - once the send has started, it will complete, and if the sent request causes the server to block the connection, then the connection will be blocked until the server will unblock the connection.
The blocking is server-side state, not client-side, so cancelling won't change it. The only options are to either unblock the connection (using `CLIENT UNBLOCK`), or close it and open a new connection.

Closing, since behavior is correct.
