### ISSUE TITLE
Streams example doesn't work

### ISSUE THREAD

**Issue by JohnAllen** [redis-rs/redis-rs#856]
If I copy this file into a main.rs file and install redis this example doesn't work. I get `consider adding a main function` which clearly it has a main function.

Not sure the issue but thought you might want to know.

https://github.com/redis-rs/redis-rs/blob/main/redis/examples/streams.rs

**Comment by JohnAllen** [comment]
If you remove `#![cfg(feature = "streams")]` it does. *shrugs*

**Comment by jaymell** [comment]
You don't want that line in your own project; it's only relevant for the example code.

**Comment by JohnAllen** [comment]
yeah I figured that out after spending twenty minutes trying to get it to work.
