### ISSUE TITLE
Development section of README is unclear/incorrect for MacOS users

### ISSUE THREAD

**Issue by sarisssa** [redis-rs/redis-rs#865]
The current guidelines in the README stipulate that we need to include the absolute path to the RedisJSON module **(Usually called librejson.so)** in our environmental variables.

This is misleading for MacOS users because we do not have access to this file when we build the Redis JSON package and the actual file we need to link in our env variables is `librejson.dylib`. 

The README should be updated to reflect this so that MacOS users who wish to test this crate can be onboarded more quickly and do not have to look for a `librejson.so` file that does not exist. 

Edit: Just noticed that this is relevant in terms of issue #815

**Comment by jaymell** [comment]
Do you think you'd be able to submit a PR? :pray:

**Comment by sarisssa** [comment]
No worries and will submit a PR on this.

**Comment by jaymell** [comment]
Fixed by https://github.com/redis-rs/redis-rs/pull/869
