### ISSUE TITLE
Cluster Async Panic: No targets to choose from

### ISSUE THREAD

**Issue by ajosecueto** [redis-rs/redis-rs#867]
My microservices after some requests panics with this error:

thread 'thread 'actix-rt|system:0|arbiter:1actix-rt|system:0|arbiter:6' panicked at '' panicked at 'No targets to choose fromNo targets to choose from', thread '', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.23.0/src/cluster_async/mod.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.23.0/src/cluster_async/mod.rsactix-rt|system:0|arbiter:3::' panicked at '927927No targets to choose from::', 2323/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.23.0/src/cluster_async/mod.rs

I'm using a Elastic Cache on cluster mode.

**Comment by jaymell** [comment]
Hi, thanks for the report. I *think* this issue will likely be prevented with some changes that have been recently merged to main (but not yet released). We've tried to eliminate situations that caused connections to individual nodes will be rebuilt, which makes this kind of error more likely. If you're consistently hitting this issue, you may try testing with the latest changes by specifying the crate as a git dependency. 

One other note is to check and consider increasing your systems' `ulimit` settings. I've had similar issues occur under heavy load on systems with a low ulimits.

**Comment by ajosecueto** [comment]
> Hi, thanks for the report. I _think_ this issue will likely be prevented with some changes that have been recently merged to main (but not yet released). We've tried to eliminate situations that caused connections to individual nodes will be rebuilt, which makes this kind of error more likely. If you're consistently hitting this issue, you may try testing with the latest changes by specifying the crate as a git dependency.
> 
> One other note is to check and consider increasing your systems' `ulimit` settings. I've had similar issues occur under heavy load on systems with a low ulimits.

Thanks @jaymell for your fast answer, I will check the ulimit too.

I will specify this crates to git while its will released.

**Comment by nihohit** [comment]
@ajosecueto, was this issue fixed in 0.25.0?

**Comment by nihohit** [comment]
Closing as solved.
