### ISSUE TITLE
Extending SET command to support more options

### ISSUE THREAD

**Issue by RokasVaitkevicius** [redis-rs/redis-rs#876]
I'm using your package in my learning project and found that `SET` command lacks support for options that redis supports, like NX/PX etc.

These extra options can be found here: https://redis.io/commands/set/

Of course I was able to make it work with just building the command using `cmd` and `arg`, but it's quite cumbersome:
```rust
let redis_result: Result<Value, redis::RedisError> = redis::cmd("SET")
     .arg(ket)
     .arg(value)
     .arg("NX")
     .arg("GET")
     .arg("EX")
     .arg(20)
     .query(&mut connection);
```

Maybe instead of that it would be better to extend `set` command to support some sort of options argument, similar to what node.js [redis](https://github.com/redis/node-redis/tree/master#redis-commands) packages does:

```js
await client.set('key', 'value', {
  EX: 10,
  NX: true
});
```

What do you think?

**Comment by jaymell** [comment]
I think a richer API here is reasonable. Are you able to submit a PR? There are some possible examples you might take from the stream implementation, e.g., `StreamClaimOptions` and `StreamReadOptions` might present some reasonable approaches for this.

**Comment by RokasVaitkevicius** [comment]
Nice, thanks for some pointers. I'll try to submit a PR in a day or two.

**Comment by RokasVaitkevicius** [comment]
I've added PR: https://github.com/redis-rs/redis-rs/pull/879 and I need some of your help on a couple of things I've raised.
