### ISSUE TITLE
HashMap isn't inserted into the redis storage

### ISSUE THREAD

**Issue by loldruger** [redis-rs/redis-rs#891]
```rust
let client = redis::Client::open("redis://redis/").ok().unwrap();
let redis = redis::aio::ConnectionManager::new(client).await;

...

let mut data = HashMap::new();

data.insert("access_token".to_string(), "...");
data.insert("expires_at".to_string(), "...");

redis.set(res_user.id.clone(), data)
    .await
    .map_err(|err| {
        println!("{:?}", err.detail());
        StatusCode::INTERNAL_SERVER_ERROR
})?;
```

I got HashMap which type is HashMap<String, String>, It isn't inserted into the redis storage. its error appears `ResponseError` when err of closure calls .kind(), `syntex error` when err calls detail(). 

I have tried to insert HashMap with simple primitive types and restart redis server. but it still shows error. what is the problem?

**Comment by nihohit** [comment]
`data` is a complex structure, which is automatically converted to multiple arguments while `set` can only take 2 arguments. Either convert `data` to string before the call, or use hset to better represent your data as a hash map.

@jaymell, this isn't the first issue with users complaining about some connection type expanding to multiple arguments. I'm not sure we can fix this without massively breaking the package, but it's something to keep an eye for.
