### ISSUE TITLE
Update redis cache value

### ISSUE THREAD

**Issue by EvilWatermelon** [redis-rs/redis-rs#920]
Hi,

is there a function that makes it possible to update the value of a key?

**Comment by jaymell** [comment]
Well, a normal `SET` will do that. But if you mean to only update a key that already exists, we recently merged `set_options`, which supports options like `XX` which may accomplish what you're looking for: https://docs.rs/redis/0.23.1/redis/struct.Cmd.html#method.set_options

**Comment by EvilWatermelon** [comment]
I looked into the doc but I didn't understand how to use this struct's functions in order to update an existing key. Can you give me an example?

**Comment by EvilWatermelon** [comment]
I looked into the redis doc and `SET` is enough because it overwrites the value of an existing key.
