### ISSUE TITLE
Sharing connection with AWS Lambda

### ISSUE THREAD

**Issue by ymwjbxxq** [redis-rs/redis-rs#948]
Hello all,

Is it possible to share the Redis connection with consecutive execution of a Lambda?

I tried all that I knew (little), 
OnceLock, lazy_static

Simple code:
```
#[tokio::main]
async fn main() -> Result<(), Error> {
    setup_tracing();

    let client = redis::Client::open(
        "rediss://xxx.eu-central-1.amazonaws.com:6379/",
    )?;
    let redis_conn: redis::aio::Connection = client
        .get_async_connection()
        .await
        .map_err(|e| anyhow::anyhow!("error connecting redis::aio::Connectionto redis: {:?}", e))?;

      run(service_fn(|event: Request| {
        function_handler(&redis_conn, event)
    }))
    .await
}

pub async fn function_handler(conn: &redis::aio::Connection, event: Request) -> anyhow::Result<impl IntoResponse> {
        let keys: Vec<String> = conn.keys("my_key").await?;
        println!("keys found: {:?}", keys);
        
         Ok((StatusCode::OK, json!(null)))
}

```

Whatever syntax I use always get:
```
cannot borrow `*conn` as mutable, as it is behind a `&` reference
`conn` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Is there a method to share the connection? 

Thank you in advance for any help you can give.

**Comment by nihohit** [comment]
Hi, try using `get_async_multiplexed_connection`, which is cheaply clonable. Then you can clone from the shared reference, and send on the clone.

**Comment by ymwjbxxq** [comment]
> get_async_multiplexed_connection

Hi Nihohit,

Thanks for the suggestion. I now do this:
```
#[tokio::main]
async fn main() -> Result<(), Error> {
    setup_tracing();

    let client = redis::Client::open(
        "rediss://xxx.eu-central-1.amazonaws.com:6379/",
    )?;
    let redis_conn = client
        .get_multiplexed_async_connection()
        .await
        .map_err(|e| anyhow::anyhow!("error connecting redis::aio::Connectionto redis: {:?}", e))?;

      run(service_fn(|event: Request| {
        function_handler(&redis_conn, event)
    }))
    .await
}

pub async fn function_handler(redis_conn: &redis::aio::MultiplexedConnection,, event: Request) -> anyhow::Result<impl IntoResponse> {
        let mut redis_conn = redis_conn.clone();
        let keys: Vec<String> = redis_conn.keys("my_key").await?;
        println!("keys found: {:?}", keys);
        
         Ok((StatusCode::OK, json!(null)))
}
```

I was reading this
https://blog.logrocket.com/using-redis-in-a-rust-web-service/

And they said:
> Using redis-rs directly (async)
Now, it’s time to implement the first way to interact with Redis — using one connection per request. The idea is to create a new connection for every request. This approach is fine if there isn’t a lot of traffic, but it won’t scale well with hundreds or thousands of concurrent requests.

I would appreciate your input on the following matter.
When it comes to optimizing Lambda's execution it is good practice to use the execution context for initialisation and connection (the main method).

Would the use of .clone() help solve the 1 connection per request? 

Thank you for your insight on this matter.

**Comment by nihohit** [comment]
I'm not an expert in regards to Lambda, but cloning a multiplexed connection doesn't create a new connection, just a new sender to an existing connection. So, given my limited context here, it sounds like saving a clone of a multiplexed connection in the context will be a good solution.

**Comment by nihohit** [comment]
@ymwjbxxq is there anything else you want from this issue, or can it be closed?

**Comment by ymwjbxxq** [comment]
Your advice worked like a charm. You can close it, and thanks again for your help.
