### ISSUE TITLE
How to RESTORE the value by DUMP command

### ISSUE THREAD

**Issue by zjwshisb** [redis-rs/redis-rs#953]
Hi Everyone:
When i use dump command to dump a key and get response value  Vec[u8],
Which value  type should i change to can be use in RESTORE command ?
I try to use String::from_utf8_lossy and get ERR DUMP payload version or checksum are wrong.
I try to use Vec[u8] and get value: FromUtf8Error.
I try to use binary string and also get  ERR DUMP payload version or checksum are wrong.
The origin server and target server is the same.

**Comment by nihohit** [comment]
This works for me:

```rs
#[test]
fn test_dump() {
    let ctx = TestContext::new();
    let mut con = ctx.connection();

    redis::cmd("SET").arg("foo").arg(42).execute(&mut con);

    let res: Vec<u8> = redis::cmd("DUMP").arg("foo").query(&mut con).unwrap();

    let _: () = redis::cmd("RESTORE")
        .arg("var")
        .arg(0)
        .arg(res)
        .query(&mut con)
        .unwrap();

    assert_eq!(con.get_del("var"), Ok(42usize));
}
```

Is this sufficient for your usecase? If not, can you share the failing code?

**Comment by zjwshisb** [comment]
@nihohit Thanks! it work! I make a mistake in other code
