### ISSUE TITLE
Async PubSub subscription to multiple channels doesn't work

### ISSUE THREAD

**Issue by Qumeric** [redis-rs/redis-rs#969]
I have the following line:`pubsub.subscribe(channels).await` where channels is `Vec<String>`

With normal pubsub, it works just fine but with `tokio` (aio) pubsub it works only if the size of `Vec` is 1 (or I pass `String` directly).

What is worse, it returns `Ok(())` so it looks like the subscription was successful but then `pubsub.on_message().next().await` returns `None`.

**Comment by Qumeric** [comment]
I am trying to subscribe to channels in a loop, it works but not always... Sometimes I still immediately get `None` from `stream.next()` even if I `sleep` before asking for it.

**Comment by nihohit** [comment]
@Qumeric can you provide a test to demonstrate the failure?

**Comment by nihohit** [comment]
couldn't repro locally. please reopen if you have a test or sample code.
