### ISSUE TITLE
Setting and getting raw bytes

### ISSUE THREAD

**Issue by 0xAlcibiades** [redis-rs/redis-rs#974]
Right now the crate errors trying to store a non utf-8 string, when redis itself has no such restriction, there is a get_payload_bytes method for pubsub, would the maintainers here be open to adding a similar getter/setter for raw bytes from a redis key?

**Comment by jaymell** [comment]
Hi, can you provide an example of what you're trying to do exactly?

**Comment by 0xAlcibiades** [comment]
> Hi, can you provide an example of what you're trying to do exactly?

So particularly I'm trying to set a binary value, a protobuf data structure, and then get it back out. The set works fine, but the get fails because the data is not valid utf-8. This works fine if I use pub/sub via this library and get_payload_bytes. So basically the reproducter would be to set a value to a key, where the value is not valid UTF8, and then try to get it back out with the higher level methods this library exposes.

**Comment by jaymell** [comment]
If I do something like reading a binary file into a Vec<u8> and setting/retrieving a key with that data, I have no issues, so I'm still not sure I understand fully what you're running into. Can you possibly paste a snippet of code as an example?

**Comment by 0xAlcibiades** [comment]
> If I do something like reading a binary file into a Vec and setting/retrieving a key with that data, I have no issues, so I'm still not sure I understand fully what you're running into. Can you possibly paste a snippet of code as an example?

What I'm running into is that the get fails as not being a utf-8 string. I'll write up a reproducer. What I end up having to do is base64 encode to a string. What I'm doing is using the get and set methods to store protobuf in a redis key.

**Comment by nihohit** [comment]
@0xAlcibiades is this still an issue? can it be reproduced?

**Comment by nihohit** [comment]
closing with no-repro. please reopen if you have a code sample.
