### ISSUE TITLE
Does Client struct support TLS?

### ISSUE THREAD

**Issue by omer-shtivi** [redis-rs/redis-rs#975]
Hello,
I need to support both TLS and authentication to a redis which isn't a cluster, is it supported?
I don't see a tls method on the Client struct.

**Comment by omer-shtivi** [comment]
You can set it up with rediss:// when calling the open()

**Comment by JonasMS** [comment]
@omer-shtivi I'm getting the following error when trying to use TLS by using `rediss://`:
```
can't connect with TLS, the feature is not enabled- InvalidClientConfig
```

Using the `tls` feature (which isn't listed in the docs) doesn't fix this
i.e. `redis = { version = "0.23.3", features = ["tls"] }`

Do you know how I can fix this?

**Comment by omer-shtivi** [comment]
@JonasMS you need also to use feature `tokio-native-tls-comp` (if you are using tokio) or `tokio-rustls-comp`, or `async-std-tls-comp`

**Comment by paul-asvb** [comment]
This worked for me in axum:

`
redis = { version = "0.24.0", features = [
    "tls",
    "aio",
    "tls-native-tls",
    "tokio-native-tls",
    "tokio-native-tls-comp",
    "tokio-comp",
] }
`

**Comment by 0xfffxfff** [comment]
> This worked for me in axum:
> 
> ```
> redis = { version = "0.24.0", features = [
>     "tls",
>     "aio",
>     "tls-native-tls",
>     "tokio-native-tls",
>     "tokio-native-tls-comp",
>     "tokio-comp",
> ] }
> ```

Thank you!
