### ISSUE TITLE
Connection not usable after parsing error. "broken pipe" when connection manager is used.

### ISSUE THREAD

**Issue by tsmt-iris** [redis-rs/redis-rs#984]
Hey

We have an application making large use of an async connection pool, timeseries and pipelines. Under the following conditions, a connection from the connection pool can "break" and result in a "broken pipe" error on next connection use:

- pipeline of `TS.RANGE` commands, which fail because the key is not available. `ERR TSDB: the key does not exist`
- pipeline **must be atomic**
- it must be **multiple commands** (single command in atomic seems to be ok)

I think timeseries is not really the issue here, but actually the fact that the connection breaks if the parsing fails and the parsing error is happening with the timeseries responses.

I was able to reproduce it in a minimal redis-rs repo. Notice that this won't produce the **broken pipe** error, but the check_connection() indicates that after the call is connection is somehow broken. Also, the `value: parse error` in the unwrap is something that we can see in our larger async system. It's just that the connection is not really usable anymore after the `pipe-multi-atomic` call (last one before the unwrap()).

It seems that in our larger system with connection manager this leads to a `broken pipe` error when the connection is checked out the next time. After we removed the `atomic()` in our larger systems, we did not see these errors anymore.

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::open("redis://127.0.0.1:6379")?;
    let mut connection = client.get_connection().unwrap();
    let flush = redis::cmd("FLUSHALL");

    println!("connection status pre: {}", connection.check_connection());
    let _: Result<Value, RedisError> = redis::cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").query(&mut connection);
    println!("connection status post single: {}", connection.check_connection());

    let _: Result<Value, RedisError> = redis::pipe().cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").query(&mut connection);
    println!("connection status post pipe-single: {}", connection.check_connection());

    let _: Result<Value, RedisError> = redis::pipe().cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").atomic().query(&mut connection);
    println!("connection status post pipe-single-atomic: {}", connection.check_connection());

    let _: Result<Value, RedisError> = redis::pipe().cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").query(&mut connection);
    println!("connection status post pipe-multi: {}", connection.check_connection());

    let _: Result<Value, RedisError> = redis::pipe().cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").cmd("TS.RANGE").arg("NOT_AVAILABLE").arg("-").arg("+").atomic().query(&mut connection);
    println!("connection status post pipe-multi-atomic: {}", connection.check_connection());

    let _: Value = redis::cmd("GET").arg("A").query(&mut connection).unwrap();
}
```

which results in the output (notice how the last line has check_connection() false. this is the same in our "big" environment and then results later in a "broken pipe" randomly)

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.52s
     Running `target/debug/rust-bench-redis`
connection status pre: true
connection status post single: true
connection status post pipe-single: true
connection status post pipe-single-atomic: true
connection status post pipe-multi: true
connection status post pipe-multi-atomic: false
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: parse error - ResponseError: Parse error at 0
Expected integer, got garbage
', src/main.rs:40:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Cargo.toml:
```
[package]
name = "rust-bench-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.23.3", features = ["cluster"]}
```

My Redis Stack Server info (is reproducable on docker/linux as well):
```
127.0.0.1:6379> info
# Server
redis_version:6.2.7
redis_git_sha1:e6f67092
redis_git_dirty:0
redis_build_id:a724769b3ec71874
redis_mode:standalone
os:Darwin 23.1.0 arm64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:kqueue
atomicvar_api:c11-builtin
gcc_version:4.2.1
process_id:16478
process_supervised:no
run_id:80cf9f877f5beea1d1d42926eae7485a5dfbf42b
tcp_port:6379
server_time_usec:1699434199684653
uptime_in_seconds:89861
uptime_in_days:1
hz:10
configured_hz:10
lru_clock:4935383
executable:/opt/homebrew/Caskroom/redis-stack-server/6.2.6-v0/bin/redis-server
config_file:/opt/homebrew/Caskroom/redis-stack-server/6.2.6-v0/etc/redis-stack.conf
io_threads_active:0
```

**Comment by tsmt-iris** [comment]
Here's also a log from our larger system where its difficult to share the code, but you can see what happens:

```
  2023-11-08T14:51:36.105726Z  WARN nucleus::datastore::redis::ts: Problem in timeseries: parse error - ResponseError: Parse error at 34
expected 3 more elements
    at lib/nucleus/src/datastore/redis/ts.rs:90 on main-workers ThreadId(27)

  2023-11-08T14:51:36.105930Z ERROR r2d2: broken pipe
    at /Users/ts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/r2d2-0.8.10/src/lib.rs:121 on main-workers ThreadId(5)
```

notice how the broken pipe is happening in another thread, since it's another compute element that is trying to reuse the connection afterwards. (poolsize=1 to provoke the error)

**Comment by nihohit** [comment]
Hi @tsmt-iris,
AFAIS parsing errors will always mean that the connection is unusable - the stream from the server contains garbage, and so the parser cannot know when the garbage message ends and where does the next, hopefully correct, message begins. Do you know whether the message from the server actually is malformed, and if so - why? Can this be reproduced with local tests?

Additionally, the issue seems to be at least partially that the connection pool reuses faulty connections. Might this be an issue for the r2d2 crate?

**Comment by cfzimmerman** [comment]
I encountered a similar issue. Adding more context about my case:
- redis crate version 0.24.0
- redis version 7.2.0

For me, making an `FCALL` to a Lua function that returns an error yields a parse error and broken pipe. This only happens when the erroring `FCALL` is not the last command in the pipe and the pipeline is flagged as atomic. Every other situation (including all that don’t return errors) are fine.

For example, calling a Lua function like this:
```
local function break_pipe(key_arr, args)
	return redis.error_reply("This causes a broken pipe")
end
```

From this (abbreviated):
```
redis::pipe()
    .atomic()
    .cmd("FCALL")
    .arg("break_pipe")
    .arg(0)
... more calls in transaction
```

Yields this from the pipeline with the FCALL:
```
RedisErr(
    parse error - ResponseError: Parse error at 32
    expected 1 more elements
    ,
)
```
More on error_reply here: https://redis.io/docs/interact/programmability/lua-api/

And this when trying to use the pipe again after that, which makes sense given the clarification above.
```
RedisErr(broken pipe,)
```

My short term fix is to just return errors as strings from Lua functions. Could there possibly be a missed case in the client library when parsing failed transactions? 
https://redis.io/docs/interact/transactions/
<img width="706" alt="Screenshot 2024-02-06 at 18 39 39" src="https://github.com/redis-rs/redis-rs/assets/70831620/af360202-f86d-41d1-83bb-2897f2b7e02a">

**Comment by nihohit** [comment]
@cfzimmerman can you write a test that will reproduce this error? if so, I could try to fix the bug.

**Comment by cfzimmerman** [comment]
I added a test to the existing suite. Feel free to clone/modify, copy/paste, or do whatever is easiest for you: https://github.com/redis-rs/redis-rs/compare/main...cfzimmerman:redis-rs:test-for-transaction-error

On my end, from the redis-rs/redis directory, `cargo test test_pipeline_transaction_with_errors --features "tokio-comp" -- --nocapture` ran green before changes. With the test I added, it panics on “Failed transaction should not interfere with future calls.“, which is the motivating issue. Taking out the subscope again makes the test pass.

Small note: after the transaction fails, the test case doesn’t generate “broken pipe” messages, it yields more parsing errors. I suspect that has to do with using a ConnectionManager in my other test and TestContext here.

If you have any questions or want help, just lmk! Grateful for your contributions to an overall phenomenal crate.

**Comment by nihohit** [comment]
@cfzimmerman , @tsmt-iris had this issue been solved in 0.25.0? An intended fix was part of the release.

**Comment by cfzimmerman** [comment]
Hi @nihohit. I can't speak for others, but the issue I mentioned is now resolved. Thank you!

**Comment by tsmt-iris** [comment]
@nihohit thanks a lot! not reproducable for me as well

**Comment by tgy3300** [comment]
> Hi @nihohit. I can't speak for others, but the issue I mentioned is now resolved. Thank you!

How to solve this problem, I also encountered this problem, my redis version is: 0.27.2

**Comment by nihohit** [comment]
@tgy3300 can you give me a code sample that reproduces the issue? specifically, with the connection type you're using and the order of operations that leads to this reproducing?

**Comment by tgy3300** [comment]
> @tgy3300您能给我一个重现该问题的代码示例吗？具体来说，您使用的连接类型以及导致此问题重现的操作顺序是什么？

```
redis = { version = "0.27.2", features = ["tokio-comp"] }

struct Test {
    redis_conn:MultiplexedConnection
}

impl Test {
    fn new(conn: MultiplexedConnection) -> Self {
        redis_conn: conn
    }
    
    fn get_data(&mut self) -> i64 {
        let sss: String = self.redis_conn.get("key").await.unwrap();
    }
}
```

外部多调用几次Test.get_data

**Comment by tgy3300** [comment]
> @tgy3300 can you give me a code sample that reproduces the issue? specifically, with the connection type you're using and the order of operations that leads to this reproducing?

```
redis = { version = "0.27.2", features = ["tokio-comp"] }

struct Test {
    redis_conn:MultiplexedConnection
}

impl Test {
    fn new(conn: MultiplexedConnection) -> Self {
        redis_conn: conn
    }
    
    fn get_data(&mut self) -> String {
        let sss: String = self.redis_conn.get("key").await.unwrap();
        sss
    }
}
```

Call Test.get_data externally a few more times

**Comment by nihohit** [comment]
@tgy3300 I'm not sure what "calling externally" means, but if I call `get` in a loop I don't see an error. Can you give a self-sustained example that reproduces the error consistently?
That is, a piece of code that doesn't require any external action beyond the example, and will always give the expected error. That's why I recommend using our testing infrastructure, since it allows you to setup a server and set values in a single test function.
