### ISSUE TITLE
Timeout parameter in .brpop changed from usize to f64 (or similar)

### ISSUE THREAD

**Issue by eythorhel19** [redis-rs/redis-rs#985]
Hi,

I am using the function brpop and the timeout parameter is defined as usize.

Redis has updated the parameter to be an double "Starting with Redis version 6.0.0: timeout is interpreted as a double instead of an integer.", so I was wondering if you could also adjust the parameter such that floating point numbers can be passed in as the timeout value.

Here is a link to the Redis doc page about the BRPOP function where I found out that redis had updated this.
https://redis.io/commands/brpop/

Is this something you can fix? I am currently using one second as the timeout which is a painfully long time.

Best regards,
Eythor

**Comment by nihohit** [comment]
Hi @eythorhel19,
I don't think that either one of the maintainers is able to work on this ATM, but this looks like a simple fix - care to try and do this?

**Comment by eythorhel19** [comment]
Yeah I can try it out :)

**Comment by eythorhel19** [comment]
Created a new pull request https://github.com/redis-rs/redis-rs/pull/988
