### ISSUE TITLE
redis 0.23.4 contains a breaking change

### ISSUE THREAD

**Issue by Xuanwo** [redis-rs/redis-rs#995]
FYI: https://github.com/mozilla/sccache/issues/1988#issuecomment-1827627261

Redis v0.23.4 appears incompatible with 0.23.3, which added a field within `ConnectionAddr::TcpTls`. This is a breaking change that could make users build failed.

```rust
error[E0063]: missing field `tls_params` in initializer of `ConnectionAddr`
   --> /home/vagrant/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.40.0/src/services/redis/backend.rs:276:17
    |
276 |                 ConnectionAddr::TcpTls {
    |                 ^^^^^^^^^^^^^^^^^^^^^^ missing `tls_params`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `opendal` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

Maybe we should yank `0.23.4` and bump to `0.24.0` instead?

**Comment by Xuanwo** [comment]
> Thank you for reporting. 0.23.4 has been yanked.

Thanks for the quick response.

**Comment by jaymell** [comment]
Yep, sorry for the inconvenience. I was not careful enough when going back through the merged PRs :sweat:

**Comment by PureWhiteWu** [comment]
Hello, maybe we can release a 0.24.0 instead?
